[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
version = "0.1.1"
license = "MIT"
repository = "https://github.com/tequdev/rshooks"
readme = "README.md"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_docs = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
indexing_slicing = "deny"
arithmetic_side_effects = "warn"
