//! Renders parsed header values back out in the exact literal styles the
//! hand-written `rshooks-core` translation uses (`docs/DESIGN.md` §4): plain
//! decimal for small counters/codes, underscore-grouped 8-digit hex for
//! bitflags, and the `(a << 16) + b` shift-add form for `sfcodes.h`.

use anyhow::{Context, Result, bail};

use crate::parse::parse_c_int;

/// Renders a C integer literal (`value.h`-style: bare decimal or bare hex,
/// with an optional `U`/`UL`/`ULL` suffix) as a Rust literal, preserving the
/// source radix: hex in becomes hex out (8 hex digits, grouped in two
/// groups of 4 with `_`, e.g. `0x00010000` -> `0x0001_0000`), decimal in
/// becomes plain decimal out.
pub fn render_literal(c_expr: &str) -> Result<String> {
    let (value, is_hex) = parse_c_int(c_expr)?;
    if is_hex {
        render_hex32(value)
    } else {
        Ok(value.to_string())
    }
}

fn render_hex32(value: i64) -> Result<String> {
    let bits: u32 = u32::try_from(value)
        .with_context(|| format!("hex literal {value} does not fit in 32 bits"))?;
    let digits = format!("{bits:08x}");
    let (hi, lo) = digits.split_at(4);
    Ok(format!("0x{hi}_{lo}"))
}

/// Parses and renders `sfcodes.h`'s uniform `((AU << 16U) + BU)` shape into
/// the Rust translation's `(a << 16) + b` form (outer grouping parens
/// dropped, inner shift parens kept, `U` suffixes dropped). Every define in
/// `sfcodes.h` is generated by the same upstream script into exactly this
/// shape, so a expr that doesn't match it is a parse error rather than a
/// fallback.
pub fn render_shift_add(c_expr: &str) -> Result<String> {
    let s = c_expr.trim();
    let s = s
        .strip_prefix('(')
        .ok_or_else(|| anyhow::anyhow!("expected outer '(' in sfcodes expr {c_expr:?}"))?
        .strip_suffix(')')
        .ok_or_else(|| anyhow::anyhow!("expected outer ')' in sfcodes expr {c_expr:?}"))?
        .trim();

    let s = s
        .strip_prefix('(')
        .ok_or_else(|| anyhow::anyhow!("expected inner '(' in sfcodes expr {c_expr:?}"))?;
    let close = s
        .find(')')
        .ok_or_else(|| anyhow::anyhow!("expected inner ')' in sfcodes expr {c_expr:?}"))?;
    let shift_group = &s[..close];
    let after = s[close + 1..].trim();

    let (a_text, b_text) = shift_group
        .split_once("<<")
        .ok_or_else(|| anyhow::anyhow!("expected '<<' in sfcodes expr {c_expr:?}"))?;
    let a = parse_c_int(a_text)?.0;
    let b = parse_c_int(b_text)?.0;

    let c_text = after.strip_prefix('+').ok_or_else(|| {
        anyhow::anyhow!("expected '+' after shift group in sfcodes expr {c_expr:?}")
    })?;
    let c = parse_c_int(c_text)?.0;

    Ok(format!("({a} << {b}) + {c}"))
}

/// A member value from `tx_flags.h`/`ls_flags.h` is either a bare integer
/// literal or (for the `MPTokenIssuanceCreateFlags` aliases) a bare
/// identifier naming another enum member. This tells the two apart.
pub fn is_bare_identifier(value: &str) -> bool {
    let v = value.trim();
    !v.is_empty()
        && v.chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && v.chars().all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Renders a `ls_flags.h`/`tx_flags.h` enum member value: an identifier
/// alias becomes a `path::to::ident` Rust expression, a literal is rendered
/// per [`render_literal`].
pub fn render_flag_value(value: &str, alias_path: &str) -> Result<String> {
    if is_bare_identifier(value) {
        Ok(format!("{alias_path}::{value}"))
    } else {
        render_literal(value)
    }
}

/// Fails loudly if `expr` doesn't parse as a plain non-negative decimal
/// integer literal — used for the handful of families (`error.h`, `tts.h`,
/// `KEYLET_*`/`COMPARE_*`, `tfCANONICAL`'s siblings) whose headers never use
/// hex, so an unexpected hex literal upstream should be a build failure, not
/// a silent reformat.
pub fn expect_decimal(name: &str, c_expr: &str) -> Result<String> {
    let (value, is_hex) = parse_c_int(c_expr)?;
    if is_hex {
        bail!("{name}: expected a decimal literal, found hex {c_expr:?}");
    }
    Ok(value.to_string())
}
