// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-protocol/ledger_entries.macro — DO NOT EDIT BY HAND.
//! Ledger entry type (`LedgerEntryType`) model.
//!
//! [`LedgerEntryType`] is a typed, exhaustive-by-construction mirror of the
//! raw `lt*` ledger-entry-type codes in `rshooks_core::lets` (plus
//! [`LedgerEntryType::Unknown`] for forward-compatibility with codes this
//! crate does not yet know about) — exactly what [`crate::tx_type::TxType`]
//! is for the `tt*` codes, applied to the `u16` type channel of a ledger
//! object's `sfLedgerEntryType`.

/// The type of a ledger object, decoded from the raw `u16` `lt*` code
/// its `sfLedgerEntryType` field carries.
///
/// # Examples
///
/// ```
/// use rshooks::ledger_entry_type::LedgerEntryType;
///
/// let ty = LedgerEntryType::from(0x0061);
/// assert_eq!(ty, LedgerEntryType::AccountRoot);
/// assert_eq!(ty.code(), 0x0061);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LedgerEntryType {
    /// `ltNFTOKEN_OFFER` (0x0037) — RPC name `nft_offer`.
    NFTokenOffer,
    /// `ltCRON` (0x0041) — RPC name `cron`.
    Cron,
    /// `ltCHECK` (0x0043) — RPC name `check`.
    Check,
    /// `ltHOOK_DEFINITION` (0x0044) — RPC name `hook_definition`.
    HookDefinition,
    /// `ltEMITTED_TXN` (0x0045) — RPC name `emitted_txn`.
    EmittedTxn,
    /// `ltHOOK` (0x0048) — RPC name `hook`.
    Hook,
    /// `ltIMPORT_VLSEQ` (0x0049) — RPC name `import_vlseq`.
    ImportVLSequence,
    /// `ltNEGATIVE_UNL` (0x004e) — RPC name `nunl`.
    NegativeUNL,
    /// `ltNFTOKEN_PAGE` (0x0050) — RPC name `nft_page`.
    NFTokenPage,
    /// `ltUNL_REPORT` (0x0052) — RPC name `unl_report`.
    UNLReport,
    /// `ltSIGNER_LIST` (0x0053) — RPC name `signer_list`.
    SignerList,
    /// `ltTICKET` (0x0054) — RPC name `ticket`.
    Ticket,
    /// `ltURI_TOKEN` (0x0055) — RPC name `uri_token`.
    URIToken,
    /// `ltACCOUNT_ROOT` (0x0061) — RPC name `account`.
    AccountRoot,
    /// `ltDIR_NODE` (0x0064) — RPC name `directory`.
    DirectoryNode,
    /// `ltAMENDMENTS` (0x0066) — RPC name `amendments`.
    Amendments,
    /// `ltLEDGER_HASHES` (0x0068) — RPC name `hashes`.
    LedgerHashes,
    /// `ltBRIDGE` (0x0069) — RPC name `bridge`.
    Bridge,
    /// `ltOFFER` (0x006f) — RPC name `offer`.
    Offer,
    /// `ltDEPOSIT_PREAUTH` (0x0070) — RPC name `deposit_preauth`.
    DepositPreauth,
    /// `ltXCHAIN_OWNED_CLAIM_ID` (0x0071) — RPC name `xchain_owned_claim_id`.
    XChainOwnedClaimID,
    /// `ltRIPPLE_STATE` (0x0072) — RPC name `state`.
    RippleState,
    /// `ltFEE_SETTINGS` (0x0073) — RPC name `fee`.
    FeeSettings,
    /// `ltXCHAIN_OWNED_CREATE_ACCOUNT_CLAIM_ID` (0x0074) — RPC name `xchain_owned_create_account_claim_id`.
    XChainOwnedCreateAccountClaimID,
    /// `ltESCROW` (0x0075) — RPC name `escrow`.
    Escrow,
    /// `ltHOOK_STATE` (0x0076) — RPC name `hook_state`.
    HookState,
    /// `ltPAYCHAN` (0x0078) — RPC name `payment_channel`.
    PayChannel,
    /// `ltAMM` (0x0079) — RPC name `amm`.
    AMM,
    /// `ltORACLE` (0x0080) — RPC name `oracle`.
    Oracle,
    /// `ltMPTOKEN_ISSUANCE` (0x007e) — RPC name `mpt_issuance`.
    MPTokenIssuance,
    /// `ltMPTOKEN` (0x007f) — RPC name `mptoken`.
    MPToken,
    /// `ltCREDENTIAL` (0x0081) — RPC name `credential`.
    Credential,
    /// `ltPERMISSIONED_DOMAIN` (0x0082) — RPC name `permissioned_domain`.
    PermissionedDomain,
    /// `ltDID` (0x008d) — RPC name `did`.
    DID,

    /// A code this version of rshooks does not recognize yet. Carries
    /// the raw code for forward-compatibility.
    Unknown(u16),
}

impl From<u16> for LedgerEntryType {
    fn from(code: u16) -> Self {
        match code {
            rshooks_core::ltNFTOKEN_OFFER => LedgerEntryType::NFTokenOffer,
            rshooks_core::ltCRON => LedgerEntryType::Cron,
            rshooks_core::ltCHECK => LedgerEntryType::Check,
            rshooks_core::ltHOOK_DEFINITION => LedgerEntryType::HookDefinition,
            rshooks_core::ltEMITTED_TXN => LedgerEntryType::EmittedTxn,
            rshooks_core::ltHOOK => LedgerEntryType::Hook,
            rshooks_core::ltIMPORT_VLSEQ => LedgerEntryType::ImportVLSequence,
            rshooks_core::ltNEGATIVE_UNL => LedgerEntryType::NegativeUNL,
            rshooks_core::ltNFTOKEN_PAGE => LedgerEntryType::NFTokenPage,
            rshooks_core::ltUNL_REPORT => LedgerEntryType::UNLReport,
            rshooks_core::ltSIGNER_LIST => LedgerEntryType::SignerList,
            rshooks_core::ltTICKET => LedgerEntryType::Ticket,
            rshooks_core::ltURI_TOKEN => LedgerEntryType::URIToken,
            rshooks_core::ltACCOUNT_ROOT => LedgerEntryType::AccountRoot,
            rshooks_core::ltDIR_NODE => LedgerEntryType::DirectoryNode,
            rshooks_core::ltAMENDMENTS => LedgerEntryType::Amendments,
            rshooks_core::ltLEDGER_HASHES => LedgerEntryType::LedgerHashes,
            rshooks_core::ltBRIDGE => LedgerEntryType::Bridge,
            rshooks_core::ltOFFER => LedgerEntryType::Offer,
            rshooks_core::ltDEPOSIT_PREAUTH => LedgerEntryType::DepositPreauth,
            rshooks_core::ltXCHAIN_OWNED_CLAIM_ID => LedgerEntryType::XChainOwnedClaimID,
            rshooks_core::ltRIPPLE_STATE => LedgerEntryType::RippleState,
            rshooks_core::ltFEE_SETTINGS => LedgerEntryType::FeeSettings,
            rshooks_core::ltXCHAIN_OWNED_CREATE_ACCOUNT_CLAIM_ID => {
                LedgerEntryType::XChainOwnedCreateAccountClaimID
            }
            rshooks_core::ltESCROW => LedgerEntryType::Escrow,
            rshooks_core::ltHOOK_STATE => LedgerEntryType::HookState,
            rshooks_core::ltPAYCHAN => LedgerEntryType::PayChannel,
            rshooks_core::ltAMM => LedgerEntryType::AMM,
            rshooks_core::ltORACLE => LedgerEntryType::Oracle,
            rshooks_core::ltMPTOKEN_ISSUANCE => LedgerEntryType::MPTokenIssuance,
            rshooks_core::ltMPTOKEN => LedgerEntryType::MPToken,
            rshooks_core::ltCREDENTIAL => LedgerEntryType::Credential,
            rshooks_core::ltPERMISSIONED_DOMAIN => LedgerEntryType::PermissionedDomain,
            rshooks_core::ltDID => LedgerEntryType::DID,
            other => LedgerEntryType::Unknown(other),
        }
    }
}

impl LedgerEntryType {
    /// The raw `u16` code this variant corresponds to. Exact inverse of
    /// [`LedgerEntryType::from`]:
    /// `LedgerEntryType::from(c).code() == c` for every code, known or
    /// unknown.
    #[inline(always)]
    #[must_use]
    pub const fn code(&self) -> u16 {
        match *self {
            LedgerEntryType::NFTokenOffer => rshooks_core::ltNFTOKEN_OFFER,
            LedgerEntryType::Cron => rshooks_core::ltCRON,
            LedgerEntryType::Check => rshooks_core::ltCHECK,
            LedgerEntryType::HookDefinition => rshooks_core::ltHOOK_DEFINITION,
            LedgerEntryType::EmittedTxn => rshooks_core::ltEMITTED_TXN,
            LedgerEntryType::Hook => rshooks_core::ltHOOK,
            LedgerEntryType::ImportVLSequence => rshooks_core::ltIMPORT_VLSEQ,
            LedgerEntryType::NegativeUNL => rshooks_core::ltNEGATIVE_UNL,
            LedgerEntryType::NFTokenPage => rshooks_core::ltNFTOKEN_PAGE,
            LedgerEntryType::UNLReport => rshooks_core::ltUNL_REPORT,
            LedgerEntryType::SignerList => rshooks_core::ltSIGNER_LIST,
            LedgerEntryType::Ticket => rshooks_core::ltTICKET,
            LedgerEntryType::URIToken => rshooks_core::ltURI_TOKEN,
            LedgerEntryType::AccountRoot => rshooks_core::ltACCOUNT_ROOT,
            LedgerEntryType::DirectoryNode => rshooks_core::ltDIR_NODE,
            LedgerEntryType::Amendments => rshooks_core::ltAMENDMENTS,
            LedgerEntryType::LedgerHashes => rshooks_core::ltLEDGER_HASHES,
            LedgerEntryType::Bridge => rshooks_core::ltBRIDGE,
            LedgerEntryType::Offer => rshooks_core::ltOFFER,
            LedgerEntryType::DepositPreauth => rshooks_core::ltDEPOSIT_PREAUTH,
            LedgerEntryType::XChainOwnedClaimID => rshooks_core::ltXCHAIN_OWNED_CLAIM_ID,
            LedgerEntryType::RippleState => rshooks_core::ltRIPPLE_STATE,
            LedgerEntryType::FeeSettings => rshooks_core::ltFEE_SETTINGS,
            LedgerEntryType::XChainOwnedCreateAccountClaimID => {
                rshooks_core::ltXCHAIN_OWNED_CREATE_ACCOUNT_CLAIM_ID
            }
            LedgerEntryType::Escrow => rshooks_core::ltESCROW,
            LedgerEntryType::HookState => rshooks_core::ltHOOK_STATE,
            LedgerEntryType::PayChannel => rshooks_core::ltPAYCHAN,
            LedgerEntryType::AMM => rshooks_core::ltAMM,
            LedgerEntryType::Oracle => rshooks_core::ltORACLE,
            LedgerEntryType::MPTokenIssuance => rshooks_core::ltMPTOKEN_ISSUANCE,
            LedgerEntryType::MPToken => rshooks_core::ltMPTOKEN,
            LedgerEntryType::Credential => rshooks_core::ltCREDENTIAL,
            LedgerEntryType::PermissionedDomain => rshooks_core::ltPERMISSIONED_DOMAIN,
            LedgerEntryType::DID => rshooks_core::ltDID,
            LedgerEntryType::Unknown(code) => code,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_known_codes() {
        const _: u16 = LedgerEntryType::Unknown(0).code();
        let known: &[u16] = &[
            0x0037, 0x0041, 0x0043, 0x0044, 0x0045, 0x0048, 0x0049, 0x004e, 0x0050, 0x0052, 0x0053,
            0x0054, 0x0055, 0x0061, 0x0064, 0x0066, 0x0068, 0x0069, 0x006f, 0x0070, 0x0071, 0x0072,
            0x0073, 0x0074, 0x0075, 0x0076, 0x0078, 0x0079, 0x0080, 0x007e, 0x007f, 0x0081, 0x0082,
            0x008d,
        ];
        for &code in known {
            assert_eq!(
                LedgerEntryType::from(code).code(),
                code,
                "round-trip failed for {code}"
            );
        }
        assert_eq!(known.len(), 34, "generated for 34 ledger entry types");
    }

    #[test]
    fn unknown_code_round_trips() {
        let ty = LedgerEntryType::from(9999);
        assert_eq!(ty, LedgerEntryType::Unknown(9999));
        assert_eq!(ty.code(), 9999);
    }
}
