// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/sfcodes.h — DO NOT EDIT BY HAND.
//! Typed serialized-field constants ([`SField<T>`](crate::types::SField)).
//!
//! One constant per **usable** `sfXxx` code, carrying the Rust type that
//! field's value reads back as. `sfSequence` is an
//! `SField<u32>`, `sfAccount` an `SField<AccountId>`, `sfBalance` an
//! `SField<Amount>` — so
//! [`SlotObject::get`](crate::slot_obj::SlotObject::get) can hand back an
//! already-typed handle and its `value()` needs no turbofish:
//!
//! ```
//! use rshooks::prelude::*;
//!
//! // The type comes from the constant, not from an annotation.
//! let _: SField<u32> = sfSequence;
//! let _: SField<AccountId> = sfAccount;
//!
//! // `.code()` is the const-context bridge back to the raw `u32`.
//! const SEQ: u32 = sfSequence.code();
//! assert_eq!(SEQ, rshooks::raw::sfcodes::sfSequence);
//! ```
//!
//! # Which fields are here
//!
//! Not all of them, deliberately. [`rshooks_core::sfcodes`] is the complete
//! 1:1 mirror of the wire protocol; this table is the *ergonomic* layer, and
//! it carries a constant only for a field some usable format references.
//! `crates/rshooks-core/format_availability.json` classifies every format:
//!
//! - a field referenced by at least one **active** format is here normally;
//! - a field whose best format is **pending** (supported by xahaud, not yet
//!   activated on Xahau) is here behind the `pending-amendments` cargo
//!   feature, alongside the views that read it;
//! - a field referenced only by **dormant** formats — gated by an amendment
//!   xahaud marks `Supported::no`, so it cannot activate on Xahau without a
//!   node upgrade — has **no typed constant**. `sfAsset` (AMM) and
//!   `sfXChainBridge` (XChainBridge) are the shape of that group.
//! - a field **no** format references is structural rather than
//!   amendment-borne — metadata, hash and index plumbing — and stays.
//!
//! Nothing is lost: the raw `u32` is always available as
//! `rshooks::raw::sfcodes::sfXxx`, and every API that takes a field code
//! takes `impl Into<u32>`. What the omission buys is that this table cannot
//! offer an autocomplete entry for a field no Xahau object can contain.
//!
//! [`crate::tx_type::TxType`] and [`crate::ledger_entry_type::LedgerEntryType`]
//! stay exhaustive for the opposite reason: they *decode* wire values rather
//! than offering capability, and a decoder that cannot name a code it might
//! receive is strictly worse than one that can.
//!
//! # How the value type is chosen
//!
//! Every `sfXxx` code packs a serialized type ID in its high bits
//! (`code >> 16`), and that ID alone decides the Rust type: 2 (`UInt32`) →
//! `u32`, 8 (`AccountID`) → [`AccountId`](crate::types::AccountId), 14
//! (`STObject`) → [`STObject`](crate::types::STObject), and so on.
//!
//! IDs this crate models no typed read for — `Blob`, `PathSet`,
//! `Vector256`, `Number`, `UInt192`, `XChainBridge`, and `Hash160` (whose
//! four fields carry genuinely different semantics: two currencies and two
//! issuers) — map to [`Opaque`](crate::types::Opaque), which supports
//! navigation and the raw byte escapes but no `value()`. Nothing is lost:
//! the bytes are still reachable, just not pre-interpreted.
//!
//! # Naming
//!
//! `#[allow(non_upper_case_globals)]`, because these mirror C constant names
//! verbatim — the same rule [`rshooks_core::sfcodes`] follows, and for the
//! same reason: a hook author reading xahaud's own sources should find the
//! identical spelling here.

#![allow(non_upper_case_globals)]

use crate::types::SField;

/// C: `sfCloseResolution` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfCloseResolution: SField<u8> = SField::new((16 << 16) + 1);
/// C: `sfMethod` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfMethod: SField<u8> = SField::new((16 << 16) + 2);
/// C: `sfTransactionResult` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfTransactionResult: SField<u8> = SField::new((16 << 16) + 3);
/// C: `sfScale` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfScale: SField<u8> = SField::new((16 << 16) + 4);
/// C: `sfTickSize` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfTickSize: SField<u8> = SField::new((16 << 16) + 16);
/// C: `sfUNLModifyDisabling` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfUNLModifyDisabling: SField<u8> = SField::new((16 << 16) + 17);
/// C: `sfHookResult` (sfcodes.h) — UInt8, read as [`u8`].
pub const sfHookResult: SField<u8> = SField::new((16 << 16) + 18);
/// C: `sfLedgerEntryType` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfLedgerEntryType: SField<u16> = SField::new((1 << 16) + 1);
/// C: `sfTransactionType` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfTransactionType: SField<u16> = SField::new((1 << 16) + 2);
/// C: `sfSignerWeight` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfSignerWeight: SField<u16> = SField::new((1 << 16) + 3);
/// C: `sfTransferFee` (sfcodes.h) — UInt16, read as [`u16`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfTransferFee: SField<u16> = SField::new((1 << 16) + 4);
/// C: `sfVersion` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfVersion: SField<u16> = SField::new((1 << 16) + 16);
/// C: `sfHookStateChangeCount` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfHookStateChangeCount: SField<u16> = SField::new((1 << 16) + 17);
/// C: `sfHookEmitCount` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfHookEmitCount: SField<u16> = SField::new((1 << 16) + 18);
/// C: `sfHookExecutionIndex` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfHookExecutionIndex: SField<u16> = SField::new((1 << 16) + 19);
/// C: `sfHookApiVersion` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfHookApiVersion: SField<u16> = SField::new((1 << 16) + 20);
/// C: `sfHookStateScale` (sfcodes.h) — UInt16, read as [`u16`].
pub const sfHookStateScale: SField<u16> = SField::new((1 << 16) + 21);
/// C: `sfLedgerFixType` (sfcodes.h) — UInt16, read as [`u16`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfLedgerFixType: SField<u16> = SField::new((1 << 16) + 22);
/// C: `sfNetworkID` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfNetworkID: SField<u32> = SField::new((2 << 16) + 1);
/// C: `sfFlags` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfFlags: SField<u32> = SField::new((2 << 16) + 2);
/// C: `sfSourceTag` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSourceTag: SField<u32> = SField::new((2 << 16) + 3);
/// C: `sfSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSequence: SField<u32> = SField::new((2 << 16) + 4);
/// C: `sfPreviousTxnLgrSeq` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfPreviousTxnLgrSeq: SField<u32> = SField::new((2 << 16) + 5);
/// C: `sfLedgerSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLedgerSequence: SField<u32> = SField::new((2 << 16) + 6);
/// C: `sfCloseTime` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfCloseTime: SField<u32> = SField::new((2 << 16) + 7);
/// C: `sfParentCloseTime` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfParentCloseTime: SField<u32> = SField::new((2 << 16) + 8);
/// C: `sfSigningTime` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSigningTime: SField<u32> = SField::new((2 << 16) + 9);
/// C: `sfExpiration` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfExpiration: SField<u32> = SField::new((2 << 16) + 10);
/// C: `sfTransferRate` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfTransferRate: SField<u32> = SField::new((2 << 16) + 11);
/// C: `sfWalletSize` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfWalletSize: SField<u32> = SField::new((2 << 16) + 12);
/// C: `sfOwnerCount` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfOwnerCount: SField<u32> = SField::new((2 << 16) + 13);
/// C: `sfDestinationTag` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfDestinationTag: SField<u32> = SField::new((2 << 16) + 14);
/// C: `sfLastUpdateTime` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLastUpdateTime: SField<u32> = SField::new((2 << 16) + 15);
/// C: `sfHighQualityIn` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfHighQualityIn: SField<u32> = SField::new((2 << 16) + 16);
/// C: `sfHighQualityOut` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfHighQualityOut: SField<u32> = SField::new((2 << 16) + 17);
/// C: `sfLowQualityIn` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLowQualityIn: SField<u32> = SField::new((2 << 16) + 18);
/// C: `sfLowQualityOut` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLowQualityOut: SField<u32> = SField::new((2 << 16) + 19);
/// C: `sfQualityIn` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfQualityIn: SField<u32> = SField::new((2 << 16) + 20);
/// C: `sfQualityOut` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfQualityOut: SField<u32> = SField::new((2 << 16) + 21);
/// C: `sfStampEscrow` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfStampEscrow: SField<u32> = SField::new((2 << 16) + 22);
/// C: `sfBondAmount` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfBondAmount: SField<u32> = SField::new((2 << 16) + 23);
/// C: `sfLoadFee` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLoadFee: SField<u32> = SField::new((2 << 16) + 24);
/// C: `sfOfferSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfOfferSequence: SField<u32> = SField::new((2 << 16) + 25);
/// C: `sfFirstLedgerSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfFirstLedgerSequence: SField<u32> = SField::new((2 << 16) + 26);
/// C: `sfLastLedgerSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLastLedgerSequence: SField<u32> = SField::new((2 << 16) + 27);
/// C: `sfTransactionIndex` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfTransactionIndex: SField<u32> = SField::new((2 << 16) + 28);
/// C: `sfOperationLimit` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfOperationLimit: SField<u32> = SField::new((2 << 16) + 29);
/// C: `sfReferenceFeeUnits` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfReferenceFeeUnits: SField<u32> = SField::new((2 << 16) + 30);
/// C: `sfReserveBase` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfReserveBase: SField<u32> = SField::new((2 << 16) + 31);
/// C: `sfReserveIncrement` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfReserveIncrement: SField<u32> = SField::new((2 << 16) + 32);
/// C: `sfSetFlag` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSetFlag: SField<u32> = SField::new((2 << 16) + 33);
/// C: `sfClearFlag` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfClearFlag: SField<u32> = SField::new((2 << 16) + 34);
/// C: `sfSignerQuorum` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSignerQuorum: SField<u32> = SField::new((2 << 16) + 35);
/// C: `sfCancelAfter` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfCancelAfter: SField<u32> = SField::new((2 << 16) + 36);
/// C: `sfFinishAfter` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfFinishAfter: SField<u32> = SField::new((2 << 16) + 37);
/// C: `sfSignerListID` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSignerListID: SField<u32> = SField::new((2 << 16) + 38);
/// C: `sfSettleDelay` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfSettleDelay: SField<u32> = SField::new((2 << 16) + 39);
/// C: `sfTicketCount` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfTicketCount: SField<u32> = SField::new((2 << 16) + 40);
/// C: `sfTicketSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfTicketSequence: SField<u32> = SField::new((2 << 16) + 41);
/// C: `sfNFTokenTaxon` (sfcodes.h) — UInt32, read as [`u32`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokenTaxon: SField<u32> = SField::new((2 << 16) + 42);
/// C: `sfMintedNFTokens` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfMintedNFTokens: SField<u32> = SField::new((2 << 16) + 43);
/// C: `sfBurnedNFTokens` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfBurnedNFTokens: SField<u32> = SField::new((2 << 16) + 44);
/// C: `sfHookStateCount` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfHookStateCount: SField<u32> = SField::new((2 << 16) + 45);
/// C: `sfEmitGeneration` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfEmitGeneration: SField<u32> = SField::new((2 << 16) + 46);
/// C: `sfLockCount` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfLockCount: SField<u32> = SField::new((2 << 16) + 49);
/// C: `sfFirstNFTokenSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfFirstNFTokenSequence: SField<u32> = SField::new((2 << 16) + 50);
/// C: `sfOracleDocumentID` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfOracleDocumentID: SField<u32> = SField::new((2 << 16) + 51);
/// C: `sfStartTime` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfStartTime: SField<u32> = SField::new((2 << 16) + 93);
/// C: `sfRepeatCount` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfRepeatCount: SField<u32> = SField::new((2 << 16) + 94);
/// C: `sfDelaySeconds` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfDelaySeconds: SField<u32> = SField::new((2 << 16) + 95);
/// C: `sfXahauActivationLgrSeq` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfXahauActivationLgrSeq: SField<u32> = SField::new((2 << 16) + 96);
/// C: `sfImportSequence` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfImportSequence: SField<u32> = SField::new((2 << 16) + 97);
/// C: `sfRewardTime` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfRewardTime: SField<u32> = SField::new((2 << 16) + 98);
/// C: `sfRewardLgrFirst` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfRewardLgrFirst: SField<u32> = SField::new((2 << 16) + 99);
/// C: `sfRewardLgrLast` (sfcodes.h) — UInt32, read as [`u32`].
pub const sfRewardLgrLast: SField<u32> = SField::new((2 << 16) + 100);
/// C: `sfIndexNext` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfIndexNext: SField<u64> = SField::new((3 << 16) + 1);
/// C: `sfIndexPrevious` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfIndexPrevious: SField<u64> = SField::new((3 << 16) + 2);
/// C: `sfBookNode` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfBookNode: SField<u64> = SField::new((3 << 16) + 3);
/// C: `sfOwnerNode` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfOwnerNode: SField<u64> = SField::new((3 << 16) + 4);
/// C: `sfBaseFee` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfBaseFee: SField<u64> = SField::new((3 << 16) + 5);
/// C: `sfExchangeRate` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfExchangeRate: SField<u64> = SField::new((3 << 16) + 6);
/// C: `sfLowNode` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfLowNode: SField<u64> = SField::new((3 << 16) + 7);
/// C: `sfHighNode` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfHighNode: SField<u64> = SField::new((3 << 16) + 8);
/// C: `sfDestinationNode` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfDestinationNode: SField<u64> = SField::new((3 << 16) + 9);
/// C: `sfCookie` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfCookie: SField<u64> = SField::new((3 << 16) + 10);
/// C: `sfServerVersion` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfServerVersion: SField<u64> = SField::new((3 << 16) + 11);
/// C: `sfNFTokenOfferNode` (sfcodes.h) — UInt64, read as [`u64`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokenOfferNode: SField<u64> = SField::new((3 << 16) + 12);
/// C: `sfEmitBurden` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfEmitBurden: SField<u64> = SField::new((3 << 16) + 13);
/// C: `sfHookInstructionCount` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfHookInstructionCount: SField<u64> = SField::new((3 << 16) + 17);
/// C: `sfHookReturnCode` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfHookReturnCode: SField<u64> = SField::new((3 << 16) + 18);
/// C: `sfReferenceCount` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfReferenceCount: SField<u64> = SField::new((3 << 16) + 19);
/// C: `sfAssetPrice` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfAssetPrice: SField<u64> = SField::new((3 << 16) + 23);
/// C: `sfTouchCount` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfTouchCount: SField<u64> = SField::new((3 << 16) + 97);
/// C: `sfAccountIndex` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfAccountIndex: SField<u64> = SField::new((3 << 16) + 98);
/// C: `sfAccountCount` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfAccountCount: SField<u64> = SField::new((3 << 16) + 99);
/// C: `sfRewardAccumulator` (sfcodes.h) — UInt64, read as [`u64`].
pub const sfRewardAccumulator: SField<u64> = SField::new((3 << 16) + 100);
/// C: `sfEmailHash` (sfcodes.h) — Hash128, read as [`crate::types::Opaque`].
pub const sfEmailHash: SField<crate::types::Opaque> = SField::new((4 << 16) + 1);
/// C: `sfTakerPaysCurrency` (sfcodes.h) — Hash160, read as [`crate::types::Opaque`].
pub const sfTakerPaysCurrency: SField<crate::types::Opaque> = SField::new((17 << 16) + 1);
/// C: `sfTakerPaysIssuer` (sfcodes.h) — Hash160, read as [`crate::types::Opaque`].
pub const sfTakerPaysIssuer: SField<crate::types::Opaque> = SField::new((17 << 16) + 2);
/// C: `sfTakerGetsCurrency` (sfcodes.h) — Hash160, read as [`crate::types::Opaque`].
pub const sfTakerGetsCurrency: SField<crate::types::Opaque> = SField::new((17 << 16) + 3);
/// C: `sfTakerGetsIssuer` (sfcodes.h) — Hash160, read as [`crate::types::Opaque`].
pub const sfTakerGetsIssuer: SField<crate::types::Opaque> = SField::new((17 << 16) + 4);
/// C: `sfLedgerHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfLedgerHash: SField<crate::types::Hash> = SField::new((5 << 16) + 1);
/// C: `sfParentHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfParentHash: SField<crate::types::Hash> = SField::new((5 << 16) + 2);
/// C: `sfTransactionHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfTransactionHash: SField<crate::types::Hash> = SField::new((5 << 16) + 3);
/// C: `sfAccountHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfAccountHash: SField<crate::types::Hash> = SField::new((5 << 16) + 4);
/// C: `sfPreviousTxnID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfPreviousTxnID: SField<crate::types::Hash> = SField::new((5 << 16) + 5);
/// C: `sfLedgerIndex` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfLedgerIndex: SField<crate::types::Hash> = SField::new((5 << 16) + 6);
/// C: `sfWalletLocator` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfWalletLocator: SField<crate::types::Hash> = SField::new((5 << 16) + 7);
/// C: `sfRootIndex` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfRootIndex: SField<crate::types::Hash> = SField::new((5 << 16) + 8);
/// C: `sfAccountTxnID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfAccountTxnID: SField<crate::types::Hash> = SField::new((5 << 16) + 9);
/// C: `sfNFTokenID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfNFTokenID: SField<crate::types::Hash> = SField::new((5 << 16) + 10);
/// C: `sfEmitParentTxnID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfEmitParentTxnID: SField<crate::types::Hash> = SField::new((5 << 16) + 11);
/// C: `sfEmitNonce` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfEmitNonce: SField<crate::types::Hash> = SField::new((5 << 16) + 12);
/// C: `sfEmitHookHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfEmitHookHash: SField<crate::types::Hash> = SField::new((5 << 16) + 13);
/// C: `sfObjectID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfObjectID: SField<crate::types::Hash> = SField::new((5 << 16) + 14);
/// C: `sfAMMID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfAMMID: SField<crate::types::Hash> = SField::new((5 << 16) + 15);
/// C: `sfBookDirectory` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfBookDirectory: SField<crate::types::Hash> = SField::new((5 << 16) + 16);
/// C: `sfInvoiceID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfInvoiceID: SField<crate::types::Hash> = SField::new((5 << 16) + 17);
/// C: `sfNickname` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfNickname: SField<crate::types::Hash> = SField::new((5 << 16) + 18);
/// C: `sfAmendment` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfAmendment: SField<crate::types::Hash> = SField::new((5 << 16) + 19);
/// C: `sfHookOn` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookOn: SField<crate::types::Hash> = SField::new((5 << 16) + 20);
/// C: `sfDigest` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfDigest: SField<crate::types::Hash> = SField::new((5 << 16) + 21);
/// C: `sfChannel` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfChannel: SField<crate::types::Hash> = SField::new((5 << 16) + 22);
/// C: `sfConsensusHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfConsensusHash: SField<crate::types::Hash> = SField::new((5 << 16) + 23);
/// C: `sfCheckID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfCheckID: SField<crate::types::Hash> = SField::new((5 << 16) + 24);
/// C: `sfValidatedHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfValidatedHash: SField<crate::types::Hash> = SField::new((5 << 16) + 25);
/// C: `sfPreviousPageMin` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfPreviousPageMin: SField<crate::types::Hash> = SField::new((5 << 16) + 26);
/// C: `sfNextPageMin` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNextPageMin: SField<crate::types::Hash> = SField::new((5 << 16) + 27);
/// C: `sfNFTokenBuyOffer` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokenBuyOffer: SField<crate::types::Hash> = SField::new((5 << 16) + 28);
/// C: `sfNFTokenSellOffer` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokenSellOffer: SField<crate::types::Hash> = SField::new((5 << 16) + 29);
/// C: `sfHookStateKey` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookStateKey: SField<crate::types::Hash> = SField::new((5 << 16) + 30);
/// C: `sfHookHash` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookHash: SField<crate::types::Hash> = SField::new((5 << 16) + 31);
/// C: `sfHookNamespace` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookNamespace: SField<crate::types::Hash> = SField::new((5 << 16) + 32);
/// C: `sfHookSetTxnID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookSetTxnID: SField<crate::types::Hash> = SField::new((5 << 16) + 33);
/// C: `sfOfferID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfOfferID: SField<crate::types::Hash> = SField::new((5 << 16) + 34);
/// C: `sfEscrowID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfEscrowID: SField<crate::types::Hash> = SField::new((5 << 16) + 35);
/// C: `sfURITokenID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfURITokenID: SField<crate::types::Hash> = SField::new((5 << 16) + 36);
/// C: `sfHookOnOutgoing` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookOnOutgoing: SField<crate::types::Hash> = SField::new((5 << 16) + 93);
/// C: `sfHookOnIncoming` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookOnIncoming: SField<crate::types::Hash> = SField::new((5 << 16) + 94);
/// C: `sfCron` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfCron: SField<crate::types::Hash> = SField::new((5 << 16) + 95);
/// C: `sfHookCanEmit` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfHookCanEmit: SField<crate::types::Hash> = SField::new((5 << 16) + 96);
/// C: `sfEmittedTxnID` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfEmittedTxnID: SField<crate::types::Hash> = SField::new((5 << 16) + 97);
/// C: `sfGovernanceMarks` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfGovernanceMarks: SField<crate::types::Hash> = SField::new((5 << 16) + 98);
/// C: `sfGovernanceFlags` (sfcodes.h) — Hash256, read as [`crate::types::Hash`].
pub const sfGovernanceFlags: SField<crate::types::Hash> = SField::new((5 << 16) + 99);
/// C: `sfNumber` (sfcodes.h) — Number, read as [`crate::types::Opaque`].
pub const sfNumber: SField<crate::types::Opaque> = SField::new((9 << 16) + 1);
/// C: `sfAmount` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfAmount: SField<crate::types::Amount> = SField::new((6 << 16) + 1);
/// C: `sfBalance` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfBalance: SField<crate::types::Amount> = SField::new((6 << 16) + 2);
/// C: `sfLimitAmount` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfLimitAmount: SField<crate::types::Amount> = SField::new((6 << 16) + 3);
/// C: `sfTakerPays` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfTakerPays: SField<crate::types::Amount> = SField::new((6 << 16) + 4);
/// C: `sfTakerGets` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfTakerGets: SField<crate::types::Amount> = SField::new((6 << 16) + 5);
/// C: `sfLowLimit` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfLowLimit: SField<crate::types::Amount> = SField::new((6 << 16) + 6);
/// C: `sfHighLimit` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfHighLimit: SField<crate::types::Amount> = SField::new((6 << 16) + 7);
/// C: `sfFee` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfFee: SField<crate::types::Amount> = SField::new((6 << 16) + 8);
/// C: `sfSendMax` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfSendMax: SField<crate::types::Amount> = SField::new((6 << 16) + 9);
/// C: `sfDeliverMin` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfDeliverMin: SField<crate::types::Amount> = SField::new((6 << 16) + 10);
/// C: `sfMinimumOffer` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfMinimumOffer: SField<crate::types::Amount> = SField::new((6 << 16) + 16);
/// C: `sfRippleEscrow` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfRippleEscrow: SField<crate::types::Amount> = SField::new((6 << 16) + 17);
/// C: `sfDeliveredAmount` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfDeliveredAmount: SField<crate::types::Amount> = SField::new((6 << 16) + 18);
/// C: `sfNFTokenBrokerFee` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokenBrokerFee: SField<crate::types::Amount> = SField::new((6 << 16) + 19);
/// C: `sfHookCallbackFee` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfHookCallbackFee: SField<crate::types::Amount> = SField::new((6 << 16) + 20);
/// C: `sfLockedBalance` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfLockedBalance: SField<crate::types::Amount> = SField::new((6 << 16) + 21);
/// C: `sfBaseFeeDrops` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfBaseFeeDrops: SField<crate::types::Amount> = SField::new((6 << 16) + 22);
/// C: `sfReserveBaseDrops` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfReserveBaseDrops: SField<crate::types::Amount> = SField::new((6 << 16) + 23);
/// C: `sfReserveIncrementDrops` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfReserveIncrementDrops: SField<crate::types::Amount> = SField::new((6 << 16) + 24);
/// C: `sfTrustLineRewardAccumulator` (sfcodes.h) — Amount, read as [`crate::types::Amount`].
pub const sfTrustLineRewardAccumulator: SField<crate::types::Amount> = SField::new((6 << 16) + 99);
/// C: `sfPublicKey` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfPublicKey: SField<crate::types::Opaque> = SField::new((7 << 16) + 1);
/// C: `sfMessageKey` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfMessageKey: SField<crate::types::Opaque> = SField::new((7 << 16) + 2);
/// C: `sfSigningPubKey` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfSigningPubKey: SField<crate::types::Opaque> = SField::new((7 << 16) + 3);
/// C: `sfTxnSignature` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfTxnSignature: SField<crate::types::Opaque> = SField::new((7 << 16) + 4);
/// C: `sfURI` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfURI: SField<crate::types::Opaque> = SField::new((7 << 16) + 5);
/// C: `sfSignature` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfSignature: SField<crate::types::Opaque> = SField::new((7 << 16) + 6);
/// C: `sfDomain` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfDomain: SField<crate::types::Opaque> = SField::new((7 << 16) + 7);
/// C: `sfFundCode` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfFundCode: SField<crate::types::Opaque> = SField::new((7 << 16) + 8);
/// C: `sfRemoveCode` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfRemoveCode: SField<crate::types::Opaque> = SField::new((7 << 16) + 9);
/// C: `sfExpireCode` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfExpireCode: SField<crate::types::Opaque> = SField::new((7 << 16) + 10);
/// C: `sfCreateCode` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfCreateCode: SField<crate::types::Opaque> = SField::new((7 << 16) + 11);
/// C: `sfMemoType` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfMemoType: SField<crate::types::Opaque> = SField::new((7 << 16) + 12);
/// C: `sfMemoData` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfMemoData: SField<crate::types::Opaque> = SField::new((7 << 16) + 13);
/// C: `sfMemoFormat` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfMemoFormat: SField<crate::types::Opaque> = SField::new((7 << 16) + 14);
/// C: `sfFulfillment` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfFulfillment: SField<crate::types::Opaque> = SField::new((7 << 16) + 16);
/// C: `sfCondition` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfCondition: SField<crate::types::Opaque> = SField::new((7 << 16) + 17);
/// C: `sfMasterSignature` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfMasterSignature: SField<crate::types::Opaque> = SField::new((7 << 16) + 18);
/// C: `sfUNLModifyValidator` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfUNLModifyValidator: SField<crate::types::Opaque> = SField::new((7 << 16) + 19);
/// C: `sfValidatorToDisable` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfValidatorToDisable: SField<crate::types::Opaque> = SField::new((7 << 16) + 20);
/// C: `sfValidatorToReEnable` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfValidatorToReEnable: SField<crate::types::Opaque> = SField::new((7 << 16) + 21);
/// C: `sfHookStateData` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfHookStateData: SField<crate::types::Opaque> = SField::new((7 << 16) + 22);
/// C: `sfHookReturnString` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfHookReturnString: SField<crate::types::Opaque> = SField::new((7 << 16) + 23);
/// C: `sfHookParameterName` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfHookParameterName: SField<crate::types::Opaque> = SField::new((7 << 16) + 24);
/// C: `sfHookParameterValue` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfHookParameterValue: SField<crate::types::Opaque> = SField::new((7 << 16) + 25);
/// C: `sfBlob` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfBlob: SField<crate::types::Opaque> = SField::new((7 << 16) + 26);
/// C: `sfAssetClass` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfAssetClass: SField<crate::types::Opaque> = SField::new((7 << 16) + 29);
/// C: `sfProvider` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfProvider: SField<crate::types::Opaque> = SField::new((7 << 16) + 30);
/// C: `sfHookName` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfHookName: SField<crate::types::Opaque> = SField::new((7 << 16) + 97);
/// C: `sfRemarkValue` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfRemarkValue: SField<crate::types::Opaque> = SField::new((7 << 16) + 98);
/// C: `sfRemarkName` (sfcodes.h) — Blob, read as [`crate::types::Opaque`].
pub const sfRemarkName: SField<crate::types::Opaque> = SField::new((7 << 16) + 99);
/// C: `sfAccount` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfAccount: SField<crate::types::AccountId> = SField::new((8 << 16) + 1);
/// C: `sfOwner` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfOwner: SField<crate::types::AccountId> = SField::new((8 << 16) + 2);
/// C: `sfDestination` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfDestination: SField<crate::types::AccountId> = SField::new((8 << 16) + 3);
/// C: `sfIssuer` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfIssuer: SField<crate::types::AccountId> = SField::new((8 << 16) + 4);
/// C: `sfAuthorize` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfAuthorize: SField<crate::types::AccountId> = SField::new((8 << 16) + 5);
/// C: `sfUnauthorize` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfUnauthorize: SField<crate::types::AccountId> = SField::new((8 << 16) + 6);
/// C: `sfRegularKey` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfRegularKey: SField<crate::types::AccountId> = SField::new((8 << 16) + 8);
/// C: `sfNFTokenMinter` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfNFTokenMinter: SField<crate::types::AccountId> = SField::new((8 << 16) + 9);
/// C: `sfEmitCallback` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfEmitCallback: SField<crate::types::AccountId> = SField::new((8 << 16) + 10);
/// C: `sfHolder` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfHolder: SField<crate::types::AccountId> = SField::new((8 << 16) + 11);
/// C: `sfHookAccount` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfHookAccount: SField<crate::types::AccountId> = SField::new((8 << 16) + 16);
/// C: `sfLockingChainDoor` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfLockingChainDoor: SField<crate::types::AccountId> = SField::new((8 << 16) + 22);
/// C: `sfIssuingChainDoor` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfIssuingChainDoor: SField<crate::types::AccountId> = SField::new((8 << 16) + 23);
/// C: `sfInform` (sfcodes.h) — AccountID, read as [`crate::types::AccountId`].
pub const sfInform: SField<crate::types::AccountId> = SField::new((8 << 16) + 99);
/// C: `sfIndexes` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
pub const sfIndexes: SField<crate::types::Opaque> = SField::new((19 << 16) + 1);
/// C: `sfHashes` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
pub const sfHashes: SField<crate::types::Opaque> = SField::new((19 << 16) + 2);
/// C: `sfAmendments` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
pub const sfAmendments: SField<crate::types::Opaque> = SField::new((19 << 16) + 3);
/// C: `sfNFTokenOffers` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokenOffers: SField<crate::types::Opaque> = SField::new((19 << 16) + 4);
/// C: `sfHookNamespaces` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
pub const sfHookNamespaces: SField<crate::types::Opaque> = SField::new((19 << 16) + 5);
/// C: `sfCredentialIDs` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
pub const sfCredentialIDs: SField<crate::types::Opaque> = SField::new((19 << 16) + 6);
/// C: `sfURITokenIDs` (sfcodes.h) — Vector256, read as [`crate::types::Opaque`].
pub const sfURITokenIDs: SField<crate::types::Opaque> = SField::new((19 << 16) + 99);
/// C: `sfPaths` (sfcodes.h) — PathSet, read as [`crate::types::Opaque`].
pub const sfPaths: SField<crate::types::Opaque> = SField::new((18 << 16) + 1);
/// C: `sfBaseAsset` (sfcodes.h) — Currency, read as [`crate::types::CurrencyCode`].
pub const sfBaseAsset: SField<crate::types::CurrencyCode> = SField::new((26 << 16) + 1);
/// C: `sfQuoteAsset` (sfcodes.h) — Currency, read as [`crate::types::CurrencyCode`].
pub const sfQuoteAsset: SField<crate::types::CurrencyCode> = SField::new((26 << 16) + 2);
/// C: `sfLockingChainIssue` (sfcodes.h) — Issue, read as [`crate::types::Issue`].
pub const sfLockingChainIssue: SField<crate::types::Issue> = SField::new((24 << 16) + 1);
/// C: `sfIssuingChainIssue` (sfcodes.h) — Issue, read as [`crate::types::Issue`].
pub const sfIssuingChainIssue: SField<crate::types::Issue> = SField::new((24 << 16) + 2);
/// C: `sfClaimCurrency` (sfcodes.h) — Issue, read as [`crate::types::Issue`].
pub const sfClaimCurrency: SField<crate::types::Issue> = SField::new((24 << 16) + 5);
/// C: `sfTransactionMetaData` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfTransactionMetaData: SField<crate::types::STObject> = SField::new((14 << 16) + 2);
/// C: `sfCreatedNode` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfCreatedNode: SField<crate::types::STObject> = SField::new((14 << 16) + 3);
/// C: `sfDeletedNode` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfDeletedNode: SField<crate::types::STObject> = SField::new((14 << 16) + 4);
/// C: `sfModifiedNode` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfModifiedNode: SField<crate::types::STObject> = SField::new((14 << 16) + 5);
/// C: `sfPreviousFields` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfPreviousFields: SField<crate::types::STObject> = SField::new((14 << 16) + 6);
/// C: `sfFinalFields` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfFinalFields: SField<crate::types::STObject> = SField::new((14 << 16) + 7);
/// C: `sfNewFields` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfNewFields: SField<crate::types::STObject> = SField::new((14 << 16) + 8);
/// C: `sfTemplateEntry` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfTemplateEntry: SField<crate::types::STObject> = SField::new((14 << 16) + 9);
/// C: `sfMemo` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfMemo: SField<crate::types::STObject> = SField::new((14 << 16) + 10);
/// C: `sfSignerEntry` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfSignerEntry: SField<crate::types::STObject> = SField::new((14 << 16) + 11);
/// C: `sfNFToken` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFToken: SField<crate::types::STObject> = SField::new((14 << 16) + 12);
/// C: `sfEmitDetails` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfEmitDetails: SField<crate::types::STObject> = SField::new((14 << 16) + 13);
/// C: `sfHook` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfHook: SField<crate::types::STObject> = SField::new((14 << 16) + 14);
/// C: `sfSigner` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfSigner: SField<crate::types::STObject> = SField::new((14 << 16) + 16);
/// C: `sfMajority` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfMajority: SField<crate::types::STObject> = SField::new((14 << 16) + 18);
/// C: `sfDisabledValidator` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfDisabledValidator: SField<crate::types::STObject> = SField::new((14 << 16) + 19);
/// C: `sfEmittedTxn` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfEmittedTxn: SField<crate::types::STObject> = SField::new((14 << 16) + 20);
/// C: `sfHookExecution` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfHookExecution: SField<crate::types::STObject> = SField::new((14 << 16) + 21);
/// C: `sfHookParameter` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfHookParameter: SField<crate::types::STObject> = SField::new((14 << 16) + 23);
/// C: `sfHookGrant` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfHookGrant: SField<crate::types::STObject> = SField::new((14 << 16) + 24);
/// C: `sfPriceData` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfPriceData: SField<crate::types::STObject> = SField::new((14 << 16) + 32);
/// C: `sfAmountEntry` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfAmountEntry: SField<crate::types::STObject> = SField::new((14 << 16) + 91);
/// C: `sfMintURIToken` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfMintURIToken: SField<crate::types::STObject> = SField::new((14 << 16) + 92);
/// C: `sfHookEmission` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfHookEmission: SField<crate::types::STObject> = SField::new((14 << 16) + 93);
/// C: `sfImportVLKey` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfImportVLKey: SField<crate::types::STObject> = SField::new((14 << 16) + 94);
/// C: `sfActiveValidator` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfActiveValidator: SField<crate::types::STObject> = SField::new((14 << 16) + 95);
/// C: `sfGenesisMint` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfGenesisMint: SField<crate::types::STObject> = SField::new((14 << 16) + 96);
/// C: `sfRemark` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfRemark: SField<crate::types::STObject> = SField::new((14 << 16) + 97);
/// C: `sfHighReward` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfHighReward: SField<crate::types::STObject> = SField::new((14 << 16) + 98);
/// C: `sfLowReward` (sfcodes.h) — STObject, read as [`crate::types::STObject`].
pub const sfLowReward: SField<crate::types::STObject> = SField::new((14 << 16) + 99);
/// C: `sfSigners` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfSigners: SField<crate::types::STArray> = SField::new((15 << 16) + 3);
/// C: `sfSignerEntries` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfSignerEntries: SField<crate::types::STArray> = SField::new((15 << 16) + 4);
/// C: `sfTemplate` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfTemplate: SField<crate::types::STArray> = SField::new((15 << 16) + 5);
/// C: `sfNecessary` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfNecessary: SField<crate::types::STArray> = SField::new((15 << 16) + 6);
/// C: `sfSufficient` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfSufficient: SField<crate::types::STArray> = SField::new((15 << 16) + 7);
/// C: `sfAffectedNodes` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfAffectedNodes: SField<crate::types::STArray> = SField::new((15 << 16) + 8);
/// C: `sfMemos` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfMemos: SField<crate::types::STArray> = SField::new((15 << 16) + 9);
/// C: `sfNFTokens` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
///
/// **Amendment not yet active** as of the vendored snapshot: every format
/// declaring this field is `pending`, so the constant is generated behind
/// the `pending-amendments` cargo feature alongside those views.
#[cfg(feature = "pending-amendments")]
pub const sfNFTokens: SField<crate::types::STArray> = SField::new((15 << 16) + 10);
/// C: `sfHooks` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfHooks: SField<crate::types::STArray> = SField::new((15 << 16) + 11);
/// C: `sfMajorities` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfMajorities: SField<crate::types::STArray> = SField::new((15 << 16) + 16);
/// C: `sfDisabledValidators` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfDisabledValidators: SField<crate::types::STArray> = SField::new((15 << 16) + 17);
/// C: `sfHookExecutions` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfHookExecutions: SField<crate::types::STArray> = SField::new((15 << 16) + 18);
/// C: `sfHookParameters` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfHookParameters: SField<crate::types::STArray> = SField::new((15 << 16) + 19);
/// C: `sfHookGrants` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfHookGrants: SField<crate::types::STArray> = SField::new((15 << 16) + 20);
/// C: `sfPriceDataSeries` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfPriceDataSeries: SField<crate::types::STArray> = SField::new((15 << 16) + 24);
/// C: `sfAuthorizeCredentials` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfAuthorizeCredentials: SField<crate::types::STArray> = SField::new((15 << 16) + 26);
/// C: `sfUnauthorizeCredentials` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfUnauthorizeCredentials: SField<crate::types::STArray> = SField::new((15 << 16) + 27);
/// C: `sfAmounts` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfAmounts: SField<crate::types::STArray> = SField::new((15 << 16) + 92);
/// C: `sfHookEmissions` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfHookEmissions: SField<crate::types::STArray> = SField::new((15 << 16) + 93);
/// C: `sfImportVLKeys` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfImportVLKeys: SField<crate::types::STArray> = SField::new((15 << 16) + 94);
/// C: `sfActiveValidators` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfActiveValidators: SField<crate::types::STArray> = SField::new((15 << 16) + 95);
/// C: `sfGenesisMints` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfGenesisMints: SField<crate::types::STArray> = SField::new((15 << 16) + 96);
/// C: `sfRemarks` (sfcodes.h) — STArray, read as [`crate::types::STArray`].
pub const sfRemarks: SField<crate::types::STArray> = SField::new((15 << 16) + 97);

#[cfg(test)]
mod parity {
    //! Every typed constant equals the raw `sfcodes` constant of the
    //! same name. Holds by construction — both tables are rendered
    //! from one parse by `cargo xtask gen-core` — which is exactly why
    //! it is worth asserting: "by construction" stops being true the
    //! moment either generator changes shape.

    #[test]
    fn typed_field_codes_match_raw() {
        assert_eq!(
            super::sfCloseResolution.code(),
            ::rshooks_core::sfcodes::sfCloseResolution,
            "sfCloseResolution"
        );
        assert_eq!(
            super::sfMethod.code(),
            ::rshooks_core::sfcodes::sfMethod,
            "sfMethod"
        );
        assert_eq!(
            super::sfTransactionResult.code(),
            ::rshooks_core::sfcodes::sfTransactionResult,
            "sfTransactionResult"
        );
        assert_eq!(
            super::sfScale.code(),
            ::rshooks_core::sfcodes::sfScale,
            "sfScale"
        );
        assert_eq!(
            super::sfTickSize.code(),
            ::rshooks_core::sfcodes::sfTickSize,
            "sfTickSize"
        );
        assert_eq!(
            super::sfUNLModifyDisabling.code(),
            ::rshooks_core::sfcodes::sfUNLModifyDisabling,
            "sfUNLModifyDisabling"
        );
        assert_eq!(
            super::sfHookResult.code(),
            ::rshooks_core::sfcodes::sfHookResult,
            "sfHookResult"
        );
        assert_eq!(
            super::sfLedgerEntryType.code(),
            ::rshooks_core::sfcodes::sfLedgerEntryType,
            "sfLedgerEntryType"
        );
        assert_eq!(
            super::sfTransactionType.code(),
            ::rshooks_core::sfcodes::sfTransactionType,
            "sfTransactionType"
        );
        assert_eq!(
            super::sfSignerWeight.code(),
            ::rshooks_core::sfcodes::sfSignerWeight,
            "sfSignerWeight"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfTransferFee.code(),
            ::rshooks_core::sfcodes::sfTransferFee,
            "sfTransferFee"
        );
        assert_eq!(
            super::sfVersion.code(),
            ::rshooks_core::sfcodes::sfVersion,
            "sfVersion"
        );
        assert_eq!(
            super::sfHookStateChangeCount.code(),
            ::rshooks_core::sfcodes::sfHookStateChangeCount,
            "sfHookStateChangeCount"
        );
        assert_eq!(
            super::sfHookEmitCount.code(),
            ::rshooks_core::sfcodes::sfHookEmitCount,
            "sfHookEmitCount"
        );
        assert_eq!(
            super::sfHookExecutionIndex.code(),
            ::rshooks_core::sfcodes::sfHookExecutionIndex,
            "sfHookExecutionIndex"
        );
        assert_eq!(
            super::sfHookApiVersion.code(),
            ::rshooks_core::sfcodes::sfHookApiVersion,
            "sfHookApiVersion"
        );
        assert_eq!(
            super::sfHookStateScale.code(),
            ::rshooks_core::sfcodes::sfHookStateScale,
            "sfHookStateScale"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfLedgerFixType.code(),
            ::rshooks_core::sfcodes::sfLedgerFixType,
            "sfLedgerFixType"
        );
        assert_eq!(
            super::sfNetworkID.code(),
            ::rshooks_core::sfcodes::sfNetworkID,
            "sfNetworkID"
        );
        assert_eq!(
            super::sfFlags.code(),
            ::rshooks_core::sfcodes::sfFlags,
            "sfFlags"
        );
        assert_eq!(
            super::sfSourceTag.code(),
            ::rshooks_core::sfcodes::sfSourceTag,
            "sfSourceTag"
        );
        assert_eq!(
            super::sfSequence.code(),
            ::rshooks_core::sfcodes::sfSequence,
            "sfSequence"
        );
        assert_eq!(
            super::sfPreviousTxnLgrSeq.code(),
            ::rshooks_core::sfcodes::sfPreviousTxnLgrSeq,
            "sfPreviousTxnLgrSeq"
        );
        assert_eq!(
            super::sfLedgerSequence.code(),
            ::rshooks_core::sfcodes::sfLedgerSequence,
            "sfLedgerSequence"
        );
        assert_eq!(
            super::sfCloseTime.code(),
            ::rshooks_core::sfcodes::sfCloseTime,
            "sfCloseTime"
        );
        assert_eq!(
            super::sfParentCloseTime.code(),
            ::rshooks_core::sfcodes::sfParentCloseTime,
            "sfParentCloseTime"
        );
        assert_eq!(
            super::sfSigningTime.code(),
            ::rshooks_core::sfcodes::sfSigningTime,
            "sfSigningTime"
        );
        assert_eq!(
            super::sfExpiration.code(),
            ::rshooks_core::sfcodes::sfExpiration,
            "sfExpiration"
        );
        assert_eq!(
            super::sfTransferRate.code(),
            ::rshooks_core::sfcodes::sfTransferRate,
            "sfTransferRate"
        );
        assert_eq!(
            super::sfWalletSize.code(),
            ::rshooks_core::sfcodes::sfWalletSize,
            "sfWalletSize"
        );
        assert_eq!(
            super::sfOwnerCount.code(),
            ::rshooks_core::sfcodes::sfOwnerCount,
            "sfOwnerCount"
        );
        assert_eq!(
            super::sfDestinationTag.code(),
            ::rshooks_core::sfcodes::sfDestinationTag,
            "sfDestinationTag"
        );
        assert_eq!(
            super::sfLastUpdateTime.code(),
            ::rshooks_core::sfcodes::sfLastUpdateTime,
            "sfLastUpdateTime"
        );
        assert_eq!(
            super::sfHighQualityIn.code(),
            ::rshooks_core::sfcodes::sfHighQualityIn,
            "sfHighQualityIn"
        );
        assert_eq!(
            super::sfHighQualityOut.code(),
            ::rshooks_core::sfcodes::sfHighQualityOut,
            "sfHighQualityOut"
        );
        assert_eq!(
            super::sfLowQualityIn.code(),
            ::rshooks_core::sfcodes::sfLowQualityIn,
            "sfLowQualityIn"
        );
        assert_eq!(
            super::sfLowQualityOut.code(),
            ::rshooks_core::sfcodes::sfLowQualityOut,
            "sfLowQualityOut"
        );
        assert_eq!(
            super::sfQualityIn.code(),
            ::rshooks_core::sfcodes::sfQualityIn,
            "sfQualityIn"
        );
        assert_eq!(
            super::sfQualityOut.code(),
            ::rshooks_core::sfcodes::sfQualityOut,
            "sfQualityOut"
        );
        assert_eq!(
            super::sfStampEscrow.code(),
            ::rshooks_core::sfcodes::sfStampEscrow,
            "sfStampEscrow"
        );
        assert_eq!(
            super::sfBondAmount.code(),
            ::rshooks_core::sfcodes::sfBondAmount,
            "sfBondAmount"
        );
        assert_eq!(
            super::sfLoadFee.code(),
            ::rshooks_core::sfcodes::sfLoadFee,
            "sfLoadFee"
        );
        assert_eq!(
            super::sfOfferSequence.code(),
            ::rshooks_core::sfcodes::sfOfferSequence,
            "sfOfferSequence"
        );
        assert_eq!(
            super::sfFirstLedgerSequence.code(),
            ::rshooks_core::sfcodes::sfFirstLedgerSequence,
            "sfFirstLedgerSequence"
        );
        assert_eq!(
            super::sfLastLedgerSequence.code(),
            ::rshooks_core::sfcodes::sfLastLedgerSequence,
            "sfLastLedgerSequence"
        );
        assert_eq!(
            super::sfTransactionIndex.code(),
            ::rshooks_core::sfcodes::sfTransactionIndex,
            "sfTransactionIndex"
        );
        assert_eq!(
            super::sfOperationLimit.code(),
            ::rshooks_core::sfcodes::sfOperationLimit,
            "sfOperationLimit"
        );
        assert_eq!(
            super::sfReferenceFeeUnits.code(),
            ::rshooks_core::sfcodes::sfReferenceFeeUnits,
            "sfReferenceFeeUnits"
        );
        assert_eq!(
            super::sfReserveBase.code(),
            ::rshooks_core::sfcodes::sfReserveBase,
            "sfReserveBase"
        );
        assert_eq!(
            super::sfReserveIncrement.code(),
            ::rshooks_core::sfcodes::sfReserveIncrement,
            "sfReserveIncrement"
        );
        assert_eq!(
            super::sfSetFlag.code(),
            ::rshooks_core::sfcodes::sfSetFlag,
            "sfSetFlag"
        );
        assert_eq!(
            super::sfClearFlag.code(),
            ::rshooks_core::sfcodes::sfClearFlag,
            "sfClearFlag"
        );
        assert_eq!(
            super::sfSignerQuorum.code(),
            ::rshooks_core::sfcodes::sfSignerQuorum,
            "sfSignerQuorum"
        );
        assert_eq!(
            super::sfCancelAfter.code(),
            ::rshooks_core::sfcodes::sfCancelAfter,
            "sfCancelAfter"
        );
        assert_eq!(
            super::sfFinishAfter.code(),
            ::rshooks_core::sfcodes::sfFinishAfter,
            "sfFinishAfter"
        );
        assert_eq!(
            super::sfSignerListID.code(),
            ::rshooks_core::sfcodes::sfSignerListID,
            "sfSignerListID"
        );
        assert_eq!(
            super::sfSettleDelay.code(),
            ::rshooks_core::sfcodes::sfSettleDelay,
            "sfSettleDelay"
        );
        assert_eq!(
            super::sfTicketCount.code(),
            ::rshooks_core::sfcodes::sfTicketCount,
            "sfTicketCount"
        );
        assert_eq!(
            super::sfTicketSequence.code(),
            ::rshooks_core::sfcodes::sfTicketSequence,
            "sfTicketSequence"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokenTaxon.code(),
            ::rshooks_core::sfcodes::sfNFTokenTaxon,
            "sfNFTokenTaxon"
        );
        assert_eq!(
            super::sfMintedNFTokens.code(),
            ::rshooks_core::sfcodes::sfMintedNFTokens,
            "sfMintedNFTokens"
        );
        assert_eq!(
            super::sfBurnedNFTokens.code(),
            ::rshooks_core::sfcodes::sfBurnedNFTokens,
            "sfBurnedNFTokens"
        );
        assert_eq!(
            super::sfHookStateCount.code(),
            ::rshooks_core::sfcodes::sfHookStateCount,
            "sfHookStateCount"
        );
        assert_eq!(
            super::sfEmitGeneration.code(),
            ::rshooks_core::sfcodes::sfEmitGeneration,
            "sfEmitGeneration"
        );
        assert_eq!(
            super::sfLockCount.code(),
            ::rshooks_core::sfcodes::sfLockCount,
            "sfLockCount"
        );
        assert_eq!(
            super::sfFirstNFTokenSequence.code(),
            ::rshooks_core::sfcodes::sfFirstNFTokenSequence,
            "sfFirstNFTokenSequence"
        );
        assert_eq!(
            super::sfOracleDocumentID.code(),
            ::rshooks_core::sfcodes::sfOracleDocumentID,
            "sfOracleDocumentID"
        );
        assert_eq!(
            super::sfStartTime.code(),
            ::rshooks_core::sfcodes::sfStartTime,
            "sfStartTime"
        );
        assert_eq!(
            super::sfRepeatCount.code(),
            ::rshooks_core::sfcodes::sfRepeatCount,
            "sfRepeatCount"
        );
        assert_eq!(
            super::sfDelaySeconds.code(),
            ::rshooks_core::sfcodes::sfDelaySeconds,
            "sfDelaySeconds"
        );
        assert_eq!(
            super::sfXahauActivationLgrSeq.code(),
            ::rshooks_core::sfcodes::sfXahauActivationLgrSeq,
            "sfXahauActivationLgrSeq"
        );
        assert_eq!(
            super::sfImportSequence.code(),
            ::rshooks_core::sfcodes::sfImportSequence,
            "sfImportSequence"
        );
        assert_eq!(
            super::sfRewardTime.code(),
            ::rshooks_core::sfcodes::sfRewardTime,
            "sfRewardTime"
        );
        assert_eq!(
            super::sfRewardLgrFirst.code(),
            ::rshooks_core::sfcodes::sfRewardLgrFirst,
            "sfRewardLgrFirst"
        );
        assert_eq!(
            super::sfRewardLgrLast.code(),
            ::rshooks_core::sfcodes::sfRewardLgrLast,
            "sfRewardLgrLast"
        );
        assert_eq!(
            super::sfIndexNext.code(),
            ::rshooks_core::sfcodes::sfIndexNext,
            "sfIndexNext"
        );
        assert_eq!(
            super::sfIndexPrevious.code(),
            ::rshooks_core::sfcodes::sfIndexPrevious,
            "sfIndexPrevious"
        );
        assert_eq!(
            super::sfBookNode.code(),
            ::rshooks_core::sfcodes::sfBookNode,
            "sfBookNode"
        );
        assert_eq!(
            super::sfOwnerNode.code(),
            ::rshooks_core::sfcodes::sfOwnerNode,
            "sfOwnerNode"
        );
        assert_eq!(
            super::sfBaseFee.code(),
            ::rshooks_core::sfcodes::sfBaseFee,
            "sfBaseFee"
        );
        assert_eq!(
            super::sfExchangeRate.code(),
            ::rshooks_core::sfcodes::sfExchangeRate,
            "sfExchangeRate"
        );
        assert_eq!(
            super::sfLowNode.code(),
            ::rshooks_core::sfcodes::sfLowNode,
            "sfLowNode"
        );
        assert_eq!(
            super::sfHighNode.code(),
            ::rshooks_core::sfcodes::sfHighNode,
            "sfHighNode"
        );
        assert_eq!(
            super::sfDestinationNode.code(),
            ::rshooks_core::sfcodes::sfDestinationNode,
            "sfDestinationNode"
        );
        assert_eq!(
            super::sfCookie.code(),
            ::rshooks_core::sfcodes::sfCookie,
            "sfCookie"
        );
        assert_eq!(
            super::sfServerVersion.code(),
            ::rshooks_core::sfcodes::sfServerVersion,
            "sfServerVersion"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokenOfferNode.code(),
            ::rshooks_core::sfcodes::sfNFTokenOfferNode,
            "sfNFTokenOfferNode"
        );
        assert_eq!(
            super::sfEmitBurden.code(),
            ::rshooks_core::sfcodes::sfEmitBurden,
            "sfEmitBurden"
        );
        assert_eq!(
            super::sfHookInstructionCount.code(),
            ::rshooks_core::sfcodes::sfHookInstructionCount,
            "sfHookInstructionCount"
        );
        assert_eq!(
            super::sfHookReturnCode.code(),
            ::rshooks_core::sfcodes::sfHookReturnCode,
            "sfHookReturnCode"
        );
        assert_eq!(
            super::sfReferenceCount.code(),
            ::rshooks_core::sfcodes::sfReferenceCount,
            "sfReferenceCount"
        );
        assert_eq!(
            super::sfAssetPrice.code(),
            ::rshooks_core::sfcodes::sfAssetPrice,
            "sfAssetPrice"
        );
        assert_eq!(
            super::sfTouchCount.code(),
            ::rshooks_core::sfcodes::sfTouchCount,
            "sfTouchCount"
        );
        assert_eq!(
            super::sfAccountIndex.code(),
            ::rshooks_core::sfcodes::sfAccountIndex,
            "sfAccountIndex"
        );
        assert_eq!(
            super::sfAccountCount.code(),
            ::rshooks_core::sfcodes::sfAccountCount,
            "sfAccountCount"
        );
        assert_eq!(
            super::sfRewardAccumulator.code(),
            ::rshooks_core::sfcodes::sfRewardAccumulator,
            "sfRewardAccumulator"
        );
        assert_eq!(
            super::sfEmailHash.code(),
            ::rshooks_core::sfcodes::sfEmailHash,
            "sfEmailHash"
        );
        assert_eq!(
            super::sfTakerPaysCurrency.code(),
            ::rshooks_core::sfcodes::sfTakerPaysCurrency,
            "sfTakerPaysCurrency"
        );
        assert_eq!(
            super::sfTakerPaysIssuer.code(),
            ::rshooks_core::sfcodes::sfTakerPaysIssuer,
            "sfTakerPaysIssuer"
        );
        assert_eq!(
            super::sfTakerGetsCurrency.code(),
            ::rshooks_core::sfcodes::sfTakerGetsCurrency,
            "sfTakerGetsCurrency"
        );
        assert_eq!(
            super::sfTakerGetsIssuer.code(),
            ::rshooks_core::sfcodes::sfTakerGetsIssuer,
            "sfTakerGetsIssuer"
        );
        assert_eq!(
            super::sfLedgerHash.code(),
            ::rshooks_core::sfcodes::sfLedgerHash,
            "sfLedgerHash"
        );
        assert_eq!(
            super::sfParentHash.code(),
            ::rshooks_core::sfcodes::sfParentHash,
            "sfParentHash"
        );
        assert_eq!(
            super::sfTransactionHash.code(),
            ::rshooks_core::sfcodes::sfTransactionHash,
            "sfTransactionHash"
        );
        assert_eq!(
            super::sfAccountHash.code(),
            ::rshooks_core::sfcodes::sfAccountHash,
            "sfAccountHash"
        );
        assert_eq!(
            super::sfPreviousTxnID.code(),
            ::rshooks_core::sfcodes::sfPreviousTxnID,
            "sfPreviousTxnID"
        );
        assert_eq!(
            super::sfLedgerIndex.code(),
            ::rshooks_core::sfcodes::sfLedgerIndex,
            "sfLedgerIndex"
        );
        assert_eq!(
            super::sfWalletLocator.code(),
            ::rshooks_core::sfcodes::sfWalletLocator,
            "sfWalletLocator"
        );
        assert_eq!(
            super::sfRootIndex.code(),
            ::rshooks_core::sfcodes::sfRootIndex,
            "sfRootIndex"
        );
        assert_eq!(
            super::sfAccountTxnID.code(),
            ::rshooks_core::sfcodes::sfAccountTxnID,
            "sfAccountTxnID"
        );
        assert_eq!(
            super::sfNFTokenID.code(),
            ::rshooks_core::sfcodes::sfNFTokenID,
            "sfNFTokenID"
        );
        assert_eq!(
            super::sfEmitParentTxnID.code(),
            ::rshooks_core::sfcodes::sfEmitParentTxnID,
            "sfEmitParentTxnID"
        );
        assert_eq!(
            super::sfEmitNonce.code(),
            ::rshooks_core::sfcodes::sfEmitNonce,
            "sfEmitNonce"
        );
        assert_eq!(
            super::sfEmitHookHash.code(),
            ::rshooks_core::sfcodes::sfEmitHookHash,
            "sfEmitHookHash"
        );
        assert_eq!(
            super::sfObjectID.code(),
            ::rshooks_core::sfcodes::sfObjectID,
            "sfObjectID"
        );
        assert_eq!(
            super::sfAMMID.code(),
            ::rshooks_core::sfcodes::sfAMMID,
            "sfAMMID"
        );
        assert_eq!(
            super::sfBookDirectory.code(),
            ::rshooks_core::sfcodes::sfBookDirectory,
            "sfBookDirectory"
        );
        assert_eq!(
            super::sfInvoiceID.code(),
            ::rshooks_core::sfcodes::sfInvoiceID,
            "sfInvoiceID"
        );
        assert_eq!(
            super::sfNickname.code(),
            ::rshooks_core::sfcodes::sfNickname,
            "sfNickname"
        );
        assert_eq!(
            super::sfAmendment.code(),
            ::rshooks_core::sfcodes::sfAmendment,
            "sfAmendment"
        );
        assert_eq!(
            super::sfHookOn.code(),
            ::rshooks_core::sfcodes::sfHookOn,
            "sfHookOn"
        );
        assert_eq!(
            super::sfDigest.code(),
            ::rshooks_core::sfcodes::sfDigest,
            "sfDigest"
        );
        assert_eq!(
            super::sfChannel.code(),
            ::rshooks_core::sfcodes::sfChannel,
            "sfChannel"
        );
        assert_eq!(
            super::sfConsensusHash.code(),
            ::rshooks_core::sfcodes::sfConsensusHash,
            "sfConsensusHash"
        );
        assert_eq!(
            super::sfCheckID.code(),
            ::rshooks_core::sfcodes::sfCheckID,
            "sfCheckID"
        );
        assert_eq!(
            super::sfValidatedHash.code(),
            ::rshooks_core::sfcodes::sfValidatedHash,
            "sfValidatedHash"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfPreviousPageMin.code(),
            ::rshooks_core::sfcodes::sfPreviousPageMin,
            "sfPreviousPageMin"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNextPageMin.code(),
            ::rshooks_core::sfcodes::sfNextPageMin,
            "sfNextPageMin"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokenBuyOffer.code(),
            ::rshooks_core::sfcodes::sfNFTokenBuyOffer,
            "sfNFTokenBuyOffer"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokenSellOffer.code(),
            ::rshooks_core::sfcodes::sfNFTokenSellOffer,
            "sfNFTokenSellOffer"
        );
        assert_eq!(
            super::sfHookStateKey.code(),
            ::rshooks_core::sfcodes::sfHookStateKey,
            "sfHookStateKey"
        );
        assert_eq!(
            super::sfHookHash.code(),
            ::rshooks_core::sfcodes::sfHookHash,
            "sfHookHash"
        );
        assert_eq!(
            super::sfHookNamespace.code(),
            ::rshooks_core::sfcodes::sfHookNamespace,
            "sfHookNamespace"
        );
        assert_eq!(
            super::sfHookSetTxnID.code(),
            ::rshooks_core::sfcodes::sfHookSetTxnID,
            "sfHookSetTxnID"
        );
        assert_eq!(
            super::sfOfferID.code(),
            ::rshooks_core::sfcodes::sfOfferID,
            "sfOfferID"
        );
        assert_eq!(
            super::sfEscrowID.code(),
            ::rshooks_core::sfcodes::sfEscrowID,
            "sfEscrowID"
        );
        assert_eq!(
            super::sfURITokenID.code(),
            ::rshooks_core::sfcodes::sfURITokenID,
            "sfURITokenID"
        );
        assert_eq!(
            super::sfHookOnOutgoing.code(),
            ::rshooks_core::sfcodes::sfHookOnOutgoing,
            "sfHookOnOutgoing"
        );
        assert_eq!(
            super::sfHookOnIncoming.code(),
            ::rshooks_core::sfcodes::sfHookOnIncoming,
            "sfHookOnIncoming"
        );
        assert_eq!(
            super::sfCron.code(),
            ::rshooks_core::sfcodes::sfCron,
            "sfCron"
        );
        assert_eq!(
            super::sfHookCanEmit.code(),
            ::rshooks_core::sfcodes::sfHookCanEmit,
            "sfHookCanEmit"
        );
        assert_eq!(
            super::sfEmittedTxnID.code(),
            ::rshooks_core::sfcodes::sfEmittedTxnID,
            "sfEmittedTxnID"
        );
        assert_eq!(
            super::sfGovernanceMarks.code(),
            ::rshooks_core::sfcodes::sfGovernanceMarks,
            "sfGovernanceMarks"
        );
        assert_eq!(
            super::sfGovernanceFlags.code(),
            ::rshooks_core::sfcodes::sfGovernanceFlags,
            "sfGovernanceFlags"
        );
        assert_eq!(
            super::sfNumber.code(),
            ::rshooks_core::sfcodes::sfNumber,
            "sfNumber"
        );
        assert_eq!(
            super::sfAmount.code(),
            ::rshooks_core::sfcodes::sfAmount,
            "sfAmount"
        );
        assert_eq!(
            super::sfBalance.code(),
            ::rshooks_core::sfcodes::sfBalance,
            "sfBalance"
        );
        assert_eq!(
            super::sfLimitAmount.code(),
            ::rshooks_core::sfcodes::sfLimitAmount,
            "sfLimitAmount"
        );
        assert_eq!(
            super::sfTakerPays.code(),
            ::rshooks_core::sfcodes::sfTakerPays,
            "sfTakerPays"
        );
        assert_eq!(
            super::sfTakerGets.code(),
            ::rshooks_core::sfcodes::sfTakerGets,
            "sfTakerGets"
        );
        assert_eq!(
            super::sfLowLimit.code(),
            ::rshooks_core::sfcodes::sfLowLimit,
            "sfLowLimit"
        );
        assert_eq!(
            super::sfHighLimit.code(),
            ::rshooks_core::sfcodes::sfHighLimit,
            "sfHighLimit"
        );
        assert_eq!(super::sfFee.code(), ::rshooks_core::sfcodes::sfFee, "sfFee");
        assert_eq!(
            super::sfSendMax.code(),
            ::rshooks_core::sfcodes::sfSendMax,
            "sfSendMax"
        );
        assert_eq!(
            super::sfDeliverMin.code(),
            ::rshooks_core::sfcodes::sfDeliverMin,
            "sfDeliverMin"
        );
        assert_eq!(
            super::sfMinimumOffer.code(),
            ::rshooks_core::sfcodes::sfMinimumOffer,
            "sfMinimumOffer"
        );
        assert_eq!(
            super::sfRippleEscrow.code(),
            ::rshooks_core::sfcodes::sfRippleEscrow,
            "sfRippleEscrow"
        );
        assert_eq!(
            super::sfDeliveredAmount.code(),
            ::rshooks_core::sfcodes::sfDeliveredAmount,
            "sfDeliveredAmount"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokenBrokerFee.code(),
            ::rshooks_core::sfcodes::sfNFTokenBrokerFee,
            "sfNFTokenBrokerFee"
        );
        assert_eq!(
            super::sfHookCallbackFee.code(),
            ::rshooks_core::sfcodes::sfHookCallbackFee,
            "sfHookCallbackFee"
        );
        assert_eq!(
            super::sfLockedBalance.code(),
            ::rshooks_core::sfcodes::sfLockedBalance,
            "sfLockedBalance"
        );
        assert_eq!(
            super::sfBaseFeeDrops.code(),
            ::rshooks_core::sfcodes::sfBaseFeeDrops,
            "sfBaseFeeDrops"
        );
        assert_eq!(
            super::sfReserveBaseDrops.code(),
            ::rshooks_core::sfcodes::sfReserveBaseDrops,
            "sfReserveBaseDrops"
        );
        assert_eq!(
            super::sfReserveIncrementDrops.code(),
            ::rshooks_core::sfcodes::sfReserveIncrementDrops,
            "sfReserveIncrementDrops"
        );
        assert_eq!(
            super::sfTrustLineRewardAccumulator.code(),
            ::rshooks_core::sfcodes::sfTrustLineRewardAccumulator,
            "sfTrustLineRewardAccumulator"
        );
        assert_eq!(
            super::sfPublicKey.code(),
            ::rshooks_core::sfcodes::sfPublicKey,
            "sfPublicKey"
        );
        assert_eq!(
            super::sfMessageKey.code(),
            ::rshooks_core::sfcodes::sfMessageKey,
            "sfMessageKey"
        );
        assert_eq!(
            super::sfSigningPubKey.code(),
            ::rshooks_core::sfcodes::sfSigningPubKey,
            "sfSigningPubKey"
        );
        assert_eq!(
            super::sfTxnSignature.code(),
            ::rshooks_core::sfcodes::sfTxnSignature,
            "sfTxnSignature"
        );
        assert_eq!(super::sfURI.code(), ::rshooks_core::sfcodes::sfURI, "sfURI");
        assert_eq!(
            super::sfSignature.code(),
            ::rshooks_core::sfcodes::sfSignature,
            "sfSignature"
        );
        assert_eq!(
            super::sfDomain.code(),
            ::rshooks_core::sfcodes::sfDomain,
            "sfDomain"
        );
        assert_eq!(
            super::sfFundCode.code(),
            ::rshooks_core::sfcodes::sfFundCode,
            "sfFundCode"
        );
        assert_eq!(
            super::sfRemoveCode.code(),
            ::rshooks_core::sfcodes::sfRemoveCode,
            "sfRemoveCode"
        );
        assert_eq!(
            super::sfExpireCode.code(),
            ::rshooks_core::sfcodes::sfExpireCode,
            "sfExpireCode"
        );
        assert_eq!(
            super::sfCreateCode.code(),
            ::rshooks_core::sfcodes::sfCreateCode,
            "sfCreateCode"
        );
        assert_eq!(
            super::sfMemoType.code(),
            ::rshooks_core::sfcodes::sfMemoType,
            "sfMemoType"
        );
        assert_eq!(
            super::sfMemoData.code(),
            ::rshooks_core::sfcodes::sfMemoData,
            "sfMemoData"
        );
        assert_eq!(
            super::sfMemoFormat.code(),
            ::rshooks_core::sfcodes::sfMemoFormat,
            "sfMemoFormat"
        );
        assert_eq!(
            super::sfFulfillment.code(),
            ::rshooks_core::sfcodes::sfFulfillment,
            "sfFulfillment"
        );
        assert_eq!(
            super::sfCondition.code(),
            ::rshooks_core::sfcodes::sfCondition,
            "sfCondition"
        );
        assert_eq!(
            super::sfMasterSignature.code(),
            ::rshooks_core::sfcodes::sfMasterSignature,
            "sfMasterSignature"
        );
        assert_eq!(
            super::sfUNLModifyValidator.code(),
            ::rshooks_core::sfcodes::sfUNLModifyValidator,
            "sfUNLModifyValidator"
        );
        assert_eq!(
            super::sfValidatorToDisable.code(),
            ::rshooks_core::sfcodes::sfValidatorToDisable,
            "sfValidatorToDisable"
        );
        assert_eq!(
            super::sfValidatorToReEnable.code(),
            ::rshooks_core::sfcodes::sfValidatorToReEnable,
            "sfValidatorToReEnable"
        );
        assert_eq!(
            super::sfHookStateData.code(),
            ::rshooks_core::sfcodes::sfHookStateData,
            "sfHookStateData"
        );
        assert_eq!(
            super::sfHookReturnString.code(),
            ::rshooks_core::sfcodes::sfHookReturnString,
            "sfHookReturnString"
        );
        assert_eq!(
            super::sfHookParameterName.code(),
            ::rshooks_core::sfcodes::sfHookParameterName,
            "sfHookParameterName"
        );
        assert_eq!(
            super::sfHookParameterValue.code(),
            ::rshooks_core::sfcodes::sfHookParameterValue,
            "sfHookParameterValue"
        );
        assert_eq!(
            super::sfBlob.code(),
            ::rshooks_core::sfcodes::sfBlob,
            "sfBlob"
        );
        assert_eq!(
            super::sfAssetClass.code(),
            ::rshooks_core::sfcodes::sfAssetClass,
            "sfAssetClass"
        );
        assert_eq!(
            super::sfProvider.code(),
            ::rshooks_core::sfcodes::sfProvider,
            "sfProvider"
        );
        assert_eq!(
            super::sfHookName.code(),
            ::rshooks_core::sfcodes::sfHookName,
            "sfHookName"
        );
        assert_eq!(
            super::sfRemarkValue.code(),
            ::rshooks_core::sfcodes::sfRemarkValue,
            "sfRemarkValue"
        );
        assert_eq!(
            super::sfRemarkName.code(),
            ::rshooks_core::sfcodes::sfRemarkName,
            "sfRemarkName"
        );
        assert_eq!(
            super::sfAccount.code(),
            ::rshooks_core::sfcodes::sfAccount,
            "sfAccount"
        );
        assert_eq!(
            super::sfOwner.code(),
            ::rshooks_core::sfcodes::sfOwner,
            "sfOwner"
        );
        assert_eq!(
            super::sfDestination.code(),
            ::rshooks_core::sfcodes::sfDestination,
            "sfDestination"
        );
        assert_eq!(
            super::sfIssuer.code(),
            ::rshooks_core::sfcodes::sfIssuer,
            "sfIssuer"
        );
        assert_eq!(
            super::sfAuthorize.code(),
            ::rshooks_core::sfcodes::sfAuthorize,
            "sfAuthorize"
        );
        assert_eq!(
            super::sfUnauthorize.code(),
            ::rshooks_core::sfcodes::sfUnauthorize,
            "sfUnauthorize"
        );
        assert_eq!(
            super::sfRegularKey.code(),
            ::rshooks_core::sfcodes::sfRegularKey,
            "sfRegularKey"
        );
        assert_eq!(
            super::sfNFTokenMinter.code(),
            ::rshooks_core::sfcodes::sfNFTokenMinter,
            "sfNFTokenMinter"
        );
        assert_eq!(
            super::sfEmitCallback.code(),
            ::rshooks_core::sfcodes::sfEmitCallback,
            "sfEmitCallback"
        );
        assert_eq!(
            super::sfHolder.code(),
            ::rshooks_core::sfcodes::sfHolder,
            "sfHolder"
        );
        assert_eq!(
            super::sfHookAccount.code(),
            ::rshooks_core::sfcodes::sfHookAccount,
            "sfHookAccount"
        );
        assert_eq!(
            super::sfLockingChainDoor.code(),
            ::rshooks_core::sfcodes::sfLockingChainDoor,
            "sfLockingChainDoor"
        );
        assert_eq!(
            super::sfIssuingChainDoor.code(),
            ::rshooks_core::sfcodes::sfIssuingChainDoor,
            "sfIssuingChainDoor"
        );
        assert_eq!(
            super::sfInform.code(),
            ::rshooks_core::sfcodes::sfInform,
            "sfInform"
        );
        assert_eq!(
            super::sfIndexes.code(),
            ::rshooks_core::sfcodes::sfIndexes,
            "sfIndexes"
        );
        assert_eq!(
            super::sfHashes.code(),
            ::rshooks_core::sfcodes::sfHashes,
            "sfHashes"
        );
        assert_eq!(
            super::sfAmendments.code(),
            ::rshooks_core::sfcodes::sfAmendments,
            "sfAmendments"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokenOffers.code(),
            ::rshooks_core::sfcodes::sfNFTokenOffers,
            "sfNFTokenOffers"
        );
        assert_eq!(
            super::sfHookNamespaces.code(),
            ::rshooks_core::sfcodes::sfHookNamespaces,
            "sfHookNamespaces"
        );
        assert_eq!(
            super::sfCredentialIDs.code(),
            ::rshooks_core::sfcodes::sfCredentialIDs,
            "sfCredentialIDs"
        );
        assert_eq!(
            super::sfURITokenIDs.code(),
            ::rshooks_core::sfcodes::sfURITokenIDs,
            "sfURITokenIDs"
        );
        assert_eq!(
            super::sfPaths.code(),
            ::rshooks_core::sfcodes::sfPaths,
            "sfPaths"
        );
        assert_eq!(
            super::sfBaseAsset.code(),
            ::rshooks_core::sfcodes::sfBaseAsset,
            "sfBaseAsset"
        );
        assert_eq!(
            super::sfQuoteAsset.code(),
            ::rshooks_core::sfcodes::sfQuoteAsset,
            "sfQuoteAsset"
        );
        assert_eq!(
            super::sfLockingChainIssue.code(),
            ::rshooks_core::sfcodes::sfLockingChainIssue,
            "sfLockingChainIssue"
        );
        assert_eq!(
            super::sfIssuingChainIssue.code(),
            ::rshooks_core::sfcodes::sfIssuingChainIssue,
            "sfIssuingChainIssue"
        );
        assert_eq!(
            super::sfClaimCurrency.code(),
            ::rshooks_core::sfcodes::sfClaimCurrency,
            "sfClaimCurrency"
        );
        assert_eq!(
            super::sfTransactionMetaData.code(),
            ::rshooks_core::sfcodes::sfTransactionMetaData,
            "sfTransactionMetaData"
        );
        assert_eq!(
            super::sfCreatedNode.code(),
            ::rshooks_core::sfcodes::sfCreatedNode,
            "sfCreatedNode"
        );
        assert_eq!(
            super::sfDeletedNode.code(),
            ::rshooks_core::sfcodes::sfDeletedNode,
            "sfDeletedNode"
        );
        assert_eq!(
            super::sfModifiedNode.code(),
            ::rshooks_core::sfcodes::sfModifiedNode,
            "sfModifiedNode"
        );
        assert_eq!(
            super::sfPreviousFields.code(),
            ::rshooks_core::sfcodes::sfPreviousFields,
            "sfPreviousFields"
        );
        assert_eq!(
            super::sfFinalFields.code(),
            ::rshooks_core::sfcodes::sfFinalFields,
            "sfFinalFields"
        );
        assert_eq!(
            super::sfNewFields.code(),
            ::rshooks_core::sfcodes::sfNewFields,
            "sfNewFields"
        );
        assert_eq!(
            super::sfTemplateEntry.code(),
            ::rshooks_core::sfcodes::sfTemplateEntry,
            "sfTemplateEntry"
        );
        assert_eq!(
            super::sfMemo.code(),
            ::rshooks_core::sfcodes::sfMemo,
            "sfMemo"
        );
        assert_eq!(
            super::sfSignerEntry.code(),
            ::rshooks_core::sfcodes::sfSignerEntry,
            "sfSignerEntry"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFToken.code(),
            ::rshooks_core::sfcodes::sfNFToken,
            "sfNFToken"
        );
        assert_eq!(
            super::sfEmitDetails.code(),
            ::rshooks_core::sfcodes::sfEmitDetails,
            "sfEmitDetails"
        );
        assert_eq!(
            super::sfHook.code(),
            ::rshooks_core::sfcodes::sfHook,
            "sfHook"
        );
        assert_eq!(
            super::sfSigner.code(),
            ::rshooks_core::sfcodes::sfSigner,
            "sfSigner"
        );
        assert_eq!(
            super::sfMajority.code(),
            ::rshooks_core::sfcodes::sfMajority,
            "sfMajority"
        );
        assert_eq!(
            super::sfDisabledValidator.code(),
            ::rshooks_core::sfcodes::sfDisabledValidator,
            "sfDisabledValidator"
        );
        assert_eq!(
            super::sfEmittedTxn.code(),
            ::rshooks_core::sfcodes::sfEmittedTxn,
            "sfEmittedTxn"
        );
        assert_eq!(
            super::sfHookExecution.code(),
            ::rshooks_core::sfcodes::sfHookExecution,
            "sfHookExecution"
        );
        assert_eq!(
            super::sfHookParameter.code(),
            ::rshooks_core::sfcodes::sfHookParameter,
            "sfHookParameter"
        );
        assert_eq!(
            super::sfHookGrant.code(),
            ::rshooks_core::sfcodes::sfHookGrant,
            "sfHookGrant"
        );
        assert_eq!(
            super::sfPriceData.code(),
            ::rshooks_core::sfcodes::sfPriceData,
            "sfPriceData"
        );
        assert_eq!(
            super::sfAmountEntry.code(),
            ::rshooks_core::sfcodes::sfAmountEntry,
            "sfAmountEntry"
        );
        assert_eq!(
            super::sfMintURIToken.code(),
            ::rshooks_core::sfcodes::sfMintURIToken,
            "sfMintURIToken"
        );
        assert_eq!(
            super::sfHookEmission.code(),
            ::rshooks_core::sfcodes::sfHookEmission,
            "sfHookEmission"
        );
        assert_eq!(
            super::sfImportVLKey.code(),
            ::rshooks_core::sfcodes::sfImportVLKey,
            "sfImportVLKey"
        );
        assert_eq!(
            super::sfActiveValidator.code(),
            ::rshooks_core::sfcodes::sfActiveValidator,
            "sfActiveValidator"
        );
        assert_eq!(
            super::sfGenesisMint.code(),
            ::rshooks_core::sfcodes::sfGenesisMint,
            "sfGenesisMint"
        );
        assert_eq!(
            super::sfRemark.code(),
            ::rshooks_core::sfcodes::sfRemark,
            "sfRemark"
        );
        assert_eq!(
            super::sfHighReward.code(),
            ::rshooks_core::sfcodes::sfHighReward,
            "sfHighReward"
        );
        assert_eq!(
            super::sfLowReward.code(),
            ::rshooks_core::sfcodes::sfLowReward,
            "sfLowReward"
        );
        assert_eq!(
            super::sfSigners.code(),
            ::rshooks_core::sfcodes::sfSigners,
            "sfSigners"
        );
        assert_eq!(
            super::sfSignerEntries.code(),
            ::rshooks_core::sfcodes::sfSignerEntries,
            "sfSignerEntries"
        );
        assert_eq!(
            super::sfTemplate.code(),
            ::rshooks_core::sfcodes::sfTemplate,
            "sfTemplate"
        );
        assert_eq!(
            super::sfNecessary.code(),
            ::rshooks_core::sfcodes::sfNecessary,
            "sfNecessary"
        );
        assert_eq!(
            super::sfSufficient.code(),
            ::rshooks_core::sfcodes::sfSufficient,
            "sfSufficient"
        );
        assert_eq!(
            super::sfAffectedNodes.code(),
            ::rshooks_core::sfcodes::sfAffectedNodes,
            "sfAffectedNodes"
        );
        assert_eq!(
            super::sfMemos.code(),
            ::rshooks_core::sfcodes::sfMemos,
            "sfMemos"
        );
        #[cfg(feature = "pending-amendments")]
        assert_eq!(
            super::sfNFTokens.code(),
            ::rshooks_core::sfcodes::sfNFTokens,
            "sfNFTokens"
        );
        assert_eq!(
            super::sfHooks.code(),
            ::rshooks_core::sfcodes::sfHooks,
            "sfHooks"
        );
        assert_eq!(
            super::sfMajorities.code(),
            ::rshooks_core::sfcodes::sfMajorities,
            "sfMajorities"
        );
        assert_eq!(
            super::sfDisabledValidators.code(),
            ::rshooks_core::sfcodes::sfDisabledValidators,
            "sfDisabledValidators"
        );
        assert_eq!(
            super::sfHookExecutions.code(),
            ::rshooks_core::sfcodes::sfHookExecutions,
            "sfHookExecutions"
        );
        assert_eq!(
            super::sfHookParameters.code(),
            ::rshooks_core::sfcodes::sfHookParameters,
            "sfHookParameters"
        );
        assert_eq!(
            super::sfHookGrants.code(),
            ::rshooks_core::sfcodes::sfHookGrants,
            "sfHookGrants"
        );
        assert_eq!(
            super::sfPriceDataSeries.code(),
            ::rshooks_core::sfcodes::sfPriceDataSeries,
            "sfPriceDataSeries"
        );
        assert_eq!(
            super::sfAuthorizeCredentials.code(),
            ::rshooks_core::sfcodes::sfAuthorizeCredentials,
            "sfAuthorizeCredentials"
        );
        assert_eq!(
            super::sfUnauthorizeCredentials.code(),
            ::rshooks_core::sfcodes::sfUnauthorizeCredentials,
            "sfUnauthorizeCredentials"
        );
        assert_eq!(
            super::sfAmounts.code(),
            ::rshooks_core::sfcodes::sfAmounts,
            "sfAmounts"
        );
        assert_eq!(
            super::sfHookEmissions.code(),
            ::rshooks_core::sfcodes::sfHookEmissions,
            "sfHookEmissions"
        );
        assert_eq!(
            super::sfImportVLKeys.code(),
            ::rshooks_core::sfcodes::sfImportVLKeys,
            "sfImportVLKeys"
        );
        assert_eq!(
            super::sfActiveValidators.code(),
            ::rshooks_core::sfcodes::sfActiveValidators,
            "sfActiveValidators"
        );
        assert_eq!(
            super::sfGenesisMints.code(),
            ::rshooks_core::sfcodes::sfGenesisMints,
            "sfGenesisMints"
        );
        assert_eq!(
            super::sfRemarks.code(),
            ::rshooks_core::sfcodes::sfRemarks,
            "sfRemarks"
        );
        assert_eq!(275, 275, "generated for 275 constants");
    }
}
