//! The guard pass: `docs/DESIGN.md` §6.3.
//!
//! Scans every function body for `loop` opcodes and checks that each one
//! begins with the guard prologue `i32.const a; i32.const b; call $_g`
//! (optionally followed by `drop`). This is the pure scanner used by the
//! validator's hard-error check and by `check`.

use anyhow::{Context, Result};

use crate::ir;

/// One `loop` site found while scanning a function body.
#[derive(Debug, Clone, Copy)]
pub(crate) struct LoopSite {
    /// Byte offset of the `loop` opcode within the function body (from the
    /// start of the body, locals included — i.e. as returned by
    /// `OperatorsReader::read_with_offset`).
    pub offset: usize,
    /// Whether this loop already begins with a valid guard prologue.
    pub guarded: bool,
    /// A conservative, best-effort guess at what this loop's body is doing
    /// (see [`LoopBodyGuess`]), used only to add an actionable hint to
    /// diagnostics for unguarded loops — it never affects pass/fail.
    pub guess: LoopBodyGuess,
}

/// A conservative, best-effort guess at what an *unguarded* loop's body is
/// doing, based purely on which instruction shapes appear in it. This exists
/// only to make the guard pass's hard-error diagnostic actionable — it never
/// affects whether the loop is accepted or rejected, and a wrong guess never
/// turns a real problem into a false pass or vice versa (see
/// [`guard_hint`]).
///
/// The heuristic is deliberately narrow and biased toward `Unknown` (no
/// hint) whenever it isn't confident: any loop containing a
/// `call`/`call_indirect` is classified `Unknown`, because real Hook
/// API-driven business logic loops (the case a developer should just add
/// `guard!` to) almost always call something, while the
/// `compiler_builtins`-generated loops this heuristic targets
/// (`bcmp`/`memcpy`/`memset`) are leaf loops that only load/store memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LoopBodyGuess {
    /// Loads memory but never stores or calls: the shape LLVM emits for a
    /// `bcmp`-style byte-compare loop, typically from `[u8; N] == [u8; N]`.
    CompareLike,
    /// Both loads and stores memory, never calls: the shape LLVM emits for a
    /// `memcpy`-style copy loop.
    CopyLike,
    /// Stores memory but never loads or calls: the shape LLVM emits for a
    /// `memset`-style zero-init loop.
    ZeroInitLike,
    /// Contains a `call` to the `_g` guard import somewhere in its body, but
    /// not at its head (a guarded loop's head is already excluded before
    /// this heuristic runs — see [`scan_function_loops`]), and not the head
    /// of a nested loop either (see [`guess_loop_body`]'s own doc comment).
    /// Distinct compiler behaviors can produce this shape:
    ///
    /// - The block-wrap case: Binaryen `wasm-opt -Oz` (run early in
    ///   `rshooks build`'s pipeline, before cleaning) restructures a loop
    ///   whose body contains an internal early-exit branch (a `continue`,
    ///   or an `if`/`?` check) into `loop { block { <guard>; .. } }`,
    ///   wrapping the guard in a `block` the checker's exact prologue match
    ///   doesn't see through.
    /// - The rotation case: LLVM's loop-rotation pass turns
    ///   `loop { guard!(maxiter); if !cond { break } body }` into a
    ///   do-while: the condition/guard block moves to the loop's latch and
    ///   is duplicated into the preheader, so the compiled `loop` opcode is
    ///   followed by `body`, not by the guard, even though the source
    ///   guard is present.
    ///
    /// [`crate::guard_hoist::hoist`] runs before this check inside
    /// `run_pipeline` (i.e. from `rshooks build`) and undoes exactly the
    /// block-wrap case, so a `RotatedGuard` guess reaching a diagnostic from
    /// `rshooks build` means the rotation case. `rshooks check` on an
    /// already-built file calls [`verify`](crate::verify) directly, with no
    /// hoist pass, so either cause is still possible there (see
    /// [`guard_hint`]'s message). Takes priority over
    /// `CompareLike`/`CopyLike`/`ZeroInitLike` in [`guess_loop_body`]: a
    /// real guard call anywhere in the body is a more specific signal than
    /// the generic load/store shape.
    RotatedGuard,
    /// Didn't conservatively match any of the above (most commonly: the
    /// loop calls something, or neither loads nor stores memory at all) —
    /// no hint should be printed for this case.
    Unknown,
}

/// Actionable hint text for an unguarded loop matching `guess`, or `None` for
/// [`LoopBodyGuess::Unknown`] (the heuristic found nothing to say — the
/// caller falls back to the plain diagnostic). Never claims certainty
/// ("looks like"), since the heuristic is a guess, not a proof.
pub(crate) fn guard_hint(guess: LoopBodyGuess) -> Option<&'static str> {
    match guess {
        LoopBodyGuess::CompareLike => Some(
            "this looks like a compiler-generated byte-compare loop (the shape LLVM emits for \
             `[u8; N] == [u8; N]` on wasm32v1-none at opt-level \"z\") — consider \
             rshooks::buf_eq_<N> instead of `==` (see crates/rshooks/src/buf_eq.rs), or, if \
             the comparison is intentionally dynamic-length, write the loop by hand with \
             `guard!` so its `maxiter` is explicit",
        ),
        LoopBodyGuess::CopyLike => Some(
            "this looks like a compiler-generated memcpy-style copy loop — either (a) a \
             stack-built source buffer: consider moving it into a `static` (data segment) \
             instead of building it on the stack, per examples/README.md's \"Statics for \
             templates and large buffers\" section, or (b) a constant-length copy over 64 \
             bytes (`copy_from_slice`, a struct/array move): past LLVM's 8-word inline-memcpy \
             limit on this target, this lowers to a `memcpy` libcall — chunk it with \
             rshooks::txn::codec::copy_fixed (or the buf_copy_<N> table in \
             crates/rshooks/src/buf_eq.rs for a fixed, already-covered length)",
        ),
        LoopBodyGuess::ZeroInitLike => Some(
            "this looks like a compiler-generated memset-style zero-init loop — either (a) a \
             large stack-local buffer: consider a zero-initialized `static` \
             (rshooks::static_cell::HookStatic) instead, per examples/README.md's \"Statics \
             for templates and large buffers\" section, or (b) a constant-length fill over 64 \
             bytes (`[x; N]`, a NOP/zero fill): past LLVM's 8-word inline-memset limit on this \
             target, this lowers to a `memset` libcall — chunk it with \
             rshooks::txn::codec::fill_fixed",
        ),
        LoopBodyGuess::RotatedGuard => Some(
            "this loop contains a `_g` guard call that is not at its head — either (a) \
             `wasm-opt -Oz` wrapped the loop body in a `block` (the guard itself is still \
             unconditional and present, just not immediately after `loop`), or (b) LLVM's \
             loop rotation moved the guard to the loop's latch and duplicated a copy into the \
             preheader (the same guard id then also appears right before this `loop`). \
             `rshooks build`'s pipeline already hoists case (a) back out automatically before \
             this check runs, so seeing this from `rshooks build` means (b) — write the loop \
             as `rshooks::guarded_while!(maxiter, cond, { .. })` instead, which stays guarded \
             either way. `rshooks check` on an already-built file runs no hoist pass, so \
             either cause is possible there; `rshooks build --no-optimize` and `wasm-tools \
             print` on the raw per-entry wasm distinguish them (see \
             book/src/concepts/guards.md, \"wasm-opt block-wrapping and LLVM loop \
             rotation\")",
        ),
        LoopBodyGuess::Unknown => None,
    }
}

/// Scans a loop's body for the load/store/call shape [`LoopBodyGuess`] is
/// based on. `reader` must be positioned immediately after the `Loop`
/// operator; this reads a clone, so `reader` itself is left untouched. Stops
/// at the loop's own matching `end` (nested blocks/loops/ifs are skipped
/// over via a depth counter, not descended into specially — their
/// loads/stores/calls still count towards the outer loop's shape, which is
/// intentional: a `bcmp`/`memcpy`/`memset` loop's body sometimes contains a
/// nested `if` for an early exit). `g_index` is the current function index
/// of the `_g` import, if the module imports one (see [`find_g_index`]).
///
/// A `call` to `_g` still counts towards [`LoopBodyGuess::RotatedGuard`]
/// wherever it appears in the body — *except* the three operator slots
/// right after a nested `loop`'s own opener, which are excluded: a call
/// there is that inner loop's own (possibly perfectly valid) guard
/// prologue, not evidence that the loop being inspected here is missing its
/// own guard. Without this exclusion, an outer loop that simply forgot its
/// `guard!` — with a correctly guarded inner loop somewhere in its body —
/// would wrongly get the rotation hint instead of the plain "add a guard!"
/// diagnostic.
fn guess_loop_body(
    reader: &wasmparser::OperatorsReader,
    g_index: Option<u32>,
) -> Result<LoopBodyGuess> {
    let mut r = reader.clone();
    let mut depth: u32 = 0;
    let mut has_load = false;
    let mut has_store = false;
    let mut has_call = false;
    let mut has_g_call = false;
    // Counts down the three operator slots right after a nested `loop`
    // opener, where that inner loop's own guard prologue would sit — see
    // this function's doc comment.
    let mut nested_prologue_guard: u32 = 0;
    while !r.eof() {
        let op = r.read()?;
        match &op {
            wasmparser::Operator::Block { .. }
            | wasmparser::Operator::Loop { .. }
            | wasmparser::Operator::If { .. } => depth += 1,
            wasmparser::Operator::End => {
                if depth == 0 {
                    break;
                }
                depth -= 1;
            }
            wasmparser::Operator::Call { function_index } => {
                has_call = true;
                if g_index == Some(*function_index) && nested_prologue_guard == 0 {
                    has_g_call = true;
                }
            }
            wasmparser::Operator::CallIndirect { .. } => {
                has_call = true;
            }
            op => {
                // wasmparser names every load/store variant (`I32Load`,
                // `I64Load8U`, `F32Store`, `I32Store8`, ...) with a `Load`
                // or `Store` substring; matching on the debug name keeps
                // this in sync with wasmparser's operator set without
                // hand-listing every width/signedness variant (the crate's
                // own float-opcode check in `validator.rs` uses the same
                // debug-name-matching idiom).
                let dbg = format!("{op:?}");
                if dbg.contains("Load") {
                    has_load = true;
                } else if dbg.contains("Store") {
                    has_store = true;
                }
            }
        }
        if matches!(op, wasmparser::Operator::Loop { .. }) {
            nested_prologue_guard = 3;
        } else {
            nested_prologue_guard = nested_prologue_guard.saturating_sub(1);
        }
    }
    if has_g_call {
        return Ok(LoopBodyGuess::RotatedGuard);
    }
    Ok(match (has_call, has_load, has_store) {
        (false, true, false) => LoopBodyGuess::CompareLike,
        (false, true, true) => LoopBodyGuess::CopyLike,
        (false, false, true) => LoopBodyGuess::ZeroInitLike,
        _ => LoopBodyGuess::Unknown,
    })
}

/// Scans a function body for `loop` sites, classifying each as guarded or
/// not. `g_index` is the current function index of the `_g` import in this
/// module, if one exists (a guard can only be recognized if its `call`
/// target actually resolves to `_g`).
pub(crate) fn scan_function_loops(
    body: &wasmparser::FunctionBody,
    g_index: Option<u32>,
) -> Result<Vec<LoopSite>> {
    let mut sites = Vec::new();
    let mut reader = body.get_operators_reader().context("function body")?;
    while !reader.eof() {
        let (op, offset) = reader
            .read_with_offset()
            .context("function body operator")?;
        if let wasmparser::Operator::Loop { .. } = op {
            let guarded = is_guard_prologue(&reader, g_index)?;
            let guess = guess_loop_body(&reader, g_index)?;
            sites.push(LoopSite {
                offset,
                guarded,
                guess,
            });
        }
    }
    Ok(sites)
}

/// Peeks (without consuming `reader`) at the next few operators to check for
/// the guard prologue `i32.const; i32.const; call $_g`. The second constant
/// (`maxiter`) must be non-zero: the upstream checker rejects a zero
/// `maxiter` outright (`Guard.h` "Guard call cannot specify 0 maxiter"), so
/// a zero-`maxiter` prologue counts as unguarded here too.
fn is_guard_prologue(reader: &wasmparser::OperatorsReader, g_index: Option<u32>) -> Result<bool> {
    let Some(g_index) = g_index else {
        return Ok(false);
    };
    let mut r = reader.clone();
    if r.eof() {
        return Ok(false);
    }
    if !matches!(r.read()?, wasmparser::Operator::I32Const { .. }) {
        return Ok(false);
    }
    if r.eof() {
        return Ok(false);
    }
    if !matches!(r.read()?, wasmparser::Operator::I32Const { value } if value != 0) {
        return Ok(false);
    }
    if r.eof() {
        return Ok(false);
    }
    match r.read()? {
        wasmparser::Operator::Call { function_index } => Ok(function_index == g_index),
        _ => Ok(false),
    }
}

/// Finds the current function index of the `env`/`_g` import, if imported.
pub(crate) fn find_g_index(m: &ir::ParsedModule) -> Option<u32> {
    m.find_func_import("env", "_g")
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::panic
)]
mod tests {
    use super::*;

    fn body_bytes(ops: &[wasm_encoder::Instruction]) -> Vec<u8> {
        let mut f = wasm_encoder::Function::new(std::iter::empty::<(u32, wasm_encoder::ValType)>());
        for op in ops {
            f.instruction(op);
        }
        f.instruction(&wasm_encoder::Instruction::End);
        f.into_raw_body()
    }

    fn parse_body(bytes: &[u8]) -> wasmparser::FunctionBody<'_> {
        wasmparser::FunctionBody::new(wasmparser::BinaryReader::new(bytes, 0))
    }

    fn reader_after_loop<'a>(
        body: &'a wasmparser::FunctionBody<'a>,
    ) -> wasmparser::OperatorsReader<'a> {
        let mut r = body.get_operators_reader().expect("operators");
        loop {
            match r.read().expect("op") {
                wasmparser::Operator::Loop { .. } => return r,
                _ => continue,
            }
        }
    }

    // -- is_guard_prologue --------------------------------------------------

    #[test]
    fn is_guard_prologue_valid_sequence_is_true() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(10),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_call_to_different_import_is_false() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(10),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(99)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_only_one_i32_const_is_false() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_loop_at_end_of_body_is_false() {
        let bytes = body_bytes(&[wasm_encoder::Instruction::Loop(
            wasm_encoder::BlockType::Empty,
        )]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_zero_maxiter_is_false() {
        // `Guard.h` rejects a zero `maxiter` outright ("Guard call cannot
        // specify 0 maxiter"), so a zero-maxiter prologue must count as
        // unguarded here too.
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_no_g_index_is_false() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(10),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, None).expect("valid"));
    }

    // -- guess_loop_body / guard_hint --------------------------------------------

    fn guess_of_with_g(
        loop_body: &[wasm_encoder::Instruction],
        g_index: Option<u32>,
    ) -> LoopBodyGuess {
        let mut ops = vec![wasm_encoder::Instruction::Loop(
            wasm_encoder::BlockType::Empty,
        )];
        ops.extend_from_slice(loop_body);
        ops.push(wasm_encoder::Instruction::End); // closes loop
        // `body_bytes` appends its own trailing `End` for the function.
        let bytes = body_bytes(&ops);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        guess_loop_body(&r, g_index).expect("valid")
    }

    fn guess_of(loop_body: &[wasm_encoder::Instruction]) -> LoopBodyGuess {
        guess_of_with_g(loop_body, None)
    }

    #[test]
    fn guess_load_only_loop_is_compare_like() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::Drop,
        ]);
        assert_eq!(guess, LoopBodyGuess::CompareLike);
        assert!(guard_hint(guess).expect("hint").contains("buf_eq"));
    }

    #[test]
    fn guess_load_and_store_loop_is_copy_like() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
        ]);
        assert_eq!(guess, LoopBodyGuess::CopyLike);
        assert!(guard_hint(guess).is_some());
    }

    #[test]
    fn guess_store_only_loop_is_zero_init_like() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
        ]);
        assert_eq!(guess, LoopBodyGuess::ZeroInitLike);
        assert!(guard_hint(guess).is_some());
    }

    #[test]
    fn guess_loop_with_any_call_is_unknown() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::Drop,
            wasm_encoder::Instruction::Call(0),
            wasm_encoder::Instruction::Drop,
        ]);
        assert_eq!(guess, LoopBodyGuess::Unknown);
        assert!(guard_hint(guess).is_none());
    }

    #[test]
    fn guess_call_to_g_in_body_is_rotated_guard() {
        // The rotated-loop shape: the guard call sits at the loop's latch,
        // not its head, with unrelated body instructions ahead of it.
        let guess = guess_of_with_g(
            &[
                wasm_encoder::Instruction::I32Const(0),
                wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                    offset: 0,
                    align: 0,
                    memory_index: 0,
                }),
                wasm_encoder::Instruction::Drop,
                wasm_encoder::Instruction::I32Const(1),
                wasm_encoder::Instruction::I32Const(10),
                wasm_encoder::Instruction::Call(3),
                wasm_encoder::Instruction::Drop,
            ],
            Some(3),
        );
        assert_eq!(guess, LoopBodyGuess::RotatedGuard);
        assert!(guard_hint(guess).expect("hint").contains("guarded_while"));
    }

    #[test]
    fn guess_call_to_other_import_is_not_rotated_guard() {
        // A call in the body that does not resolve to `_g` must not be
        // mistaken for a rotated guard.
        let guess = guess_of_with_g(
            &[
                wasm_encoder::Instruction::I32Const(1),
                wasm_encoder::Instruction::I32Const(10),
                wasm_encoder::Instruction::Call(7),
                wasm_encoder::Instruction::Drop,
            ],
            Some(3),
        );
        assert_eq!(guess, LoopBodyGuess::Unknown);
    }

    #[test]
    fn guess_nested_loops_own_guard_is_not_mistaken_for_rotated_guard() {
        // The outer loop is genuinely unguarded (a plain missing-`guard!`
        // bug); its body contains a nested loop with its own, correctly
        // placed guard prologue at its head. That inner guard must not
        // make the outer loop's guess `RotatedGuard` — it's unrelated to
        // rotation, and hinting at `guarded_while!` here would be wrong.
        let guess = guess_of_with_g(
            &[
                wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
                wasm_encoder::Instruction::I32Const(1),
                wasm_encoder::Instruction::I32Const(10),
                wasm_encoder::Instruction::Call(3),
                wasm_encoder::Instruction::Drop,
                wasm_encoder::Instruction::End, // closes the nested loop
            ],
            Some(3),
        );
        assert_eq!(guess, LoopBodyGuess::Unknown);
        assert!(guard_hint(guess).is_none());
    }

    #[test]
    fn guess_nested_if_inside_loop_still_classified() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::If(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::Drop,
            wasm_encoder::Instruction::End,
        ]);
        assert_eq!(guess, LoopBodyGuess::CompareLike);
    }
}
