//! The guard pass: `docs/DESIGN.md` §6.3.
//!
//! Scans every function body for `loop` opcodes and checks that each one
//! begins with the guard prologue `i32.const a; i32.const b; call $_g`
//! (optionally followed by `drop`). This module provides both the pure
//! scanner (used by the validator's hard-error check, and by `check`) and
//! the deprecated opt-in auto-insertion transform (used by `build
//! --auto-guard` / `clean --auto-guard`).

use anyhow::{Context, Result};

use crate::Options;
use crate::encode;
use crate::ir::{self, IndexRemapper};

/// One `loop` site found while scanning a function body.
#[derive(Debug, Clone, Copy)]
pub(crate) struct LoopSite {
    /// Byte offset of the `loop` opcode within the function body (from the
    /// start of the body, locals included — i.e. as returned by
    /// `OperatorsReader::read_with_offset`).
    pub offset: usize,
    /// Whether this loop already begins with a valid guard prologue.
    pub guarded: bool,
    /// A conservative, best-effort guess at what this loop's body is doing
    /// (see [`LoopBodyGuess`]), used only to add an actionable hint to
    /// diagnostics for unguarded loops — it never affects pass/fail.
    pub guess: LoopBodyGuess,
}

/// A conservative, best-effort guess at what an *unguarded* loop's body is
/// doing, based purely on which instruction shapes appear in it. This exists
/// only to make the guard pass's hard-error diagnostic actionable — it never
/// affects whether the loop is accepted or rejected, and a wrong guess never
/// turns a real problem into a false pass or vice versa (see
/// [`guard_hint`]).
///
/// The heuristic is deliberately narrow and biased toward `Unknown` (no
/// hint) whenever it isn't confident: any loop containing a
/// `call`/`call_indirect` is classified `Unknown`, because real Hook
/// API-driven business logic loops (the case a developer should just add
/// `guard!` to) almost always call something, while the
/// `compiler_builtins`-generated loops this heuristic targets
/// (`bcmp`/`memcpy`/`memset`) are leaf loops that only load/store memory.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum LoopBodyGuess {
    /// Loads memory but never stores or calls: the shape LLVM emits for a
    /// `bcmp`-style byte-compare loop, typically from `[u8; N] == [u8; N]`.
    CompareLike,
    /// Both loads and stores memory, never calls: the shape LLVM emits for a
    /// `memcpy`-style copy loop.
    CopyLike,
    /// Stores memory but never loads or calls: the shape LLVM emits for a
    /// `memset`-style zero-init loop.
    ZeroInitLike,
    /// Didn't conservatively match any of the above (most commonly: the
    /// loop calls something, or neither loads nor stores memory at all) —
    /// no hint should be printed for this case.
    Unknown,
}

/// Actionable hint text for an unguarded loop matching `guess`, or `None` for
/// [`LoopBodyGuess::Unknown`] (the heuristic found nothing to say — the
/// caller falls back to the plain diagnostic). Never claims certainty
/// ("looks like"), since the heuristic is a guess, not a proof.
pub(crate) fn guard_hint(guess: LoopBodyGuess) -> Option<&'static str> {
    match guess {
        LoopBodyGuess::CompareLike => Some(
            "this looks like a compiler-generated byte-compare loop (the shape LLVM emits for \
             `[u8; N] == [u8; N]` on wasm32v1-none at opt-level \"z\") — consider \
             rshooks::buf_eq_<N> instead of `==` (see crates/rshooks/src/buf_eq.rs), or, if \
             the comparison is intentionally dynamic-length, write the loop by hand with \
             `guard!` so its `maxiter` is explicit",
        ),
        LoopBodyGuess::CopyLike => Some(
            "this looks like a compiler-generated memcpy-style copy loop — consider moving the \
             source data into a `static` (data segment) instead of building it on the stack, \
             per examples/README.md's \"Statics for templates and large buffers\" section",
        ),
        LoopBodyGuess::ZeroInitLike => Some(
            "this looks like a compiler-generated memset-style zero-init loop — consider a \
             zero-initialized `static` (rshooks::static_cell::HookStatic) instead of a large \
             stack-local buffer, per examples/README.md's \"Statics for templates and large \
             buffers\" section",
        ),
        LoopBodyGuess::Unknown => None,
    }
}

/// Scans a loop's body for the load/store/call shape [`LoopBodyGuess`] is
/// based on. `reader` must be positioned immediately after the `Loop`
/// operator; this reads a clone, so `reader` itself is left untouched. Stops
/// at the loop's own matching `end` (nested blocks/loops/ifs are skipped
/// over via a depth counter, not descended into specially — their
/// loads/stores/calls still count towards the outer loop's shape, which is
/// intentional: a `bcmp`/`memcpy`/`memset` loop's body sometimes contains a
/// nested `if` for an early exit).
fn guess_loop_body(reader: &wasmparser::OperatorsReader) -> Result<LoopBodyGuess> {
    let mut r = reader.clone();
    let mut depth: u32 = 0;
    let mut has_load = false;
    let mut has_store = false;
    let mut has_call = false;
    while !r.eof() {
        match r.read()? {
            wasmparser::Operator::Block { .. }
            | wasmparser::Operator::Loop { .. }
            | wasmparser::Operator::If { .. } => depth += 1,
            wasmparser::Operator::End => {
                if depth == 0 {
                    break;
                }
                depth -= 1;
            }
            wasmparser::Operator::Call { .. } | wasmparser::Operator::CallIndirect { .. } => {
                has_call = true;
            }
            op => {
                // wasmparser names every load/store variant (`I32Load`,
                // `I64Load8U`, `F32Store`, `I32Store8`, ...) with a `Load`
                // or `Store` substring; matching on the debug name keeps
                // this in sync with wasmparser's operator set without
                // hand-listing every width/signedness variant (the crate's
                // own float-opcode check in `validator.rs` uses the same
                // debug-name-matching idiom).
                let dbg = format!("{op:?}");
                if dbg.contains("Load") {
                    has_load = true;
                } else if dbg.contains("Store") {
                    has_store = true;
                }
            }
        }
    }
    Ok(match (has_call, has_load, has_store) {
        (false, true, false) => LoopBodyGuess::CompareLike,
        (false, true, true) => LoopBodyGuess::CopyLike,
        (false, false, true) => LoopBodyGuess::ZeroInitLike,
        _ => LoopBodyGuess::Unknown,
    })
}

/// Scans a function body for `loop` sites, classifying each as guarded or
/// not. `g_index` is the current function index of the `_g` import in this
/// module, if one exists (a guard can only be recognized if its `call`
/// target actually resolves to `_g`).
pub(crate) fn scan_function_loops(
    body: &wasmparser::FunctionBody,
    g_index: Option<u32>,
) -> Result<Vec<LoopSite>> {
    let mut sites = Vec::new();
    let mut reader = body.get_operators_reader().context("function body")?;
    while !reader.eof() {
        let (op, offset) = reader
            .read_with_offset()
            .context("function body operator")?;
        if let wasmparser::Operator::Loop { .. } = op {
            let guarded = is_guard_prologue(&reader, g_index)?;
            let guess = guess_loop_body(&reader)?;
            sites.push(LoopSite {
                offset,
                guarded,
                guess,
            });
        }
    }
    Ok(sites)
}

/// Peeks (without consuming `reader`) at the next few operators to check for
/// the guard prologue `i32.const; i32.const; call $_g`. The second constant
/// (`maxiter`) must be non-zero: the upstream checker rejects a zero
/// `maxiter` outright (`Guard.h` "Guard call cannot specify 0 maxiter"), so
/// a zero-`maxiter` prologue counts as unguarded here too.
fn is_guard_prologue(reader: &wasmparser::OperatorsReader, g_index: Option<u32>) -> Result<bool> {
    let Some(g_index) = g_index else {
        return Ok(false);
    };
    let mut r = reader.clone();
    if r.eof() {
        return Ok(false);
    }
    if !matches!(r.read()?, wasmparser::Operator::I32Const { .. }) {
        return Ok(false);
    }
    if r.eof() {
        return Ok(false);
    }
    if !matches!(r.read()?, wasmparser::Operator::I32Const { value } if value != 0) {
        return Ok(false);
    }
    if r.eof() {
        return Ok(false);
    }
    match r.read()? {
        wasmparser::Operator::Call { function_index } => Ok(function_index == g_index),
        _ => Ok(false),
    }
}

/// Finds the current function index of the `env`/`_g` import, if imported.
pub(crate) fn find_g_index(m: &ir::ParsedModule) -> Option<u32> {
    m.find_func_import("env", "_g")
}

/// Runs the auto-guard transform: for every function, any `loop` missing a
/// guard prologue gets one inserted immediately after the loop's blocktype:
/// `i32.const id; i32.const maxiter; call $_g; drop`, where
/// `id = (1 << 30) + n` (`n` sequential across the whole module, disjoint
/// from the `guard!`/`guard_m!` id space which starts at `1 << 31`) and
/// `maxiter = opts.default_maxiter`.
///
/// If `_g` is not already imported, it is added (as the last import), which
/// uniformly shifts every defined function index by one; every `call` and
/// export index in the module is updated accordingly.
///
/// If every loop already carries a guard, `wasm` is returned unchanged
/// (byte-for-byte) — this keeps the pass idempotent and avoids
/// re-encoding a module that needed no changes.
#[deprecated(
    note = "the auto-guard transform is scheduled for removal; remove the compiler-generated \
            loop at the source level (`rshooks::buf_eq_*`, `HookStatic`) or write the loop by \
            hand with `guard!`"
)]
#[allow(deprecated)]
pub fn auto_guard(wasm: &[u8], opts: &Options) -> Result<Vec<u8>> {
    let m = ir::parse(wasm)?;

    // Cleaned input never contains a table or an element segment (the
    // cleaner drops both — `call_indirect` is banned). The re-encode below
    // emits neither section, so accepting one here would silently drop it;
    // reject instead.
    if !m.tables.is_empty() || !m.elements.is_empty() {
        anyhow::bail!(
            "module has a table or element segment; the guard pass requires cleaned input \
             (run the cleaner first)"
        );
    }

    let existing_g_index = find_g_index(&m);

    // First pass: does anything actually need inserting? If not, return the
    // input unchanged.
    let mut any_unguarded = false;
    for body in &m.code {
        let sites = scan_function_loops(body, existing_g_index)?;
        if sites.iter().any(|s| !s.guarded) {
            any_unguarded = true;
            break;
        }
    }
    if !any_unguarded {
        return Ok(wasm.to_vec());
    }

    /// Whether `_g` is already imported, or needs to be added (and if so,
    /// at which new function index and with which type index).
    #[derive(Clone, Copy)]
    enum GImport {
        Existing(u32),
        New { g_index: u32, type_idx: u32 },
    }

    let n_imp_funcs = m.num_imported_funcs();
    let mut types = m.types.clone();
    let g_import = match existing_g_index {
        Some(idx) => GImport::Existing(idx),
        None => {
            let type_idx = ir::find_or_insert_type(
                &mut types,
                &[wasmparser::ValType::I32, wasmparser::ValType::I32],
                &[wasmparser::ValType::I32],
            );
            GImport::New {
                g_index: n_imp_funcs,
                type_idx,
            }
        }
    };
    let (g_index, need_new_import, shift_at) = match g_import {
        GImport::Existing(idx) => (idx, false, None),
        GImport::New { g_index, .. } => (g_index, true, Some(g_index)),
    };
    let func_map = move |old: u32| -> u32 {
        match shift_at {
            Some(threshold) if old >= threshold => old + 1,
            _ => old,
        }
    };
    let global_map = |old: u32| old;

    let mut counter: u32 = 0;

    let mut module = wasm_encoder::Module::new();

    module.section(&encode::encode_type_section(&types)?);

    let mut imports_sec = encode::encode_import_section(&m.imports, |_ordinal, type_idx| {
        Ok(Some(wasm_encoder::EntityType::Function(type_idx)))
    })?;
    if let GImport::New { type_idx, .. } = g_import {
        imports_sec.import("env", "_g", wasm_encoder::EntityType::Function(type_idx));
    }
    module.section(&imports_sec);

    let mut funcs_sec = wasm_encoder::FunctionSection::new();
    for &type_idx in &m.defined_func_types {
        funcs_sec.function(type_idx);
    }
    module.section(&funcs_sec);

    module.section(&encode::encode_memory_section(&m.memories));

    let mut remapper = IndexRemapper::new(func_map, global_map);
    module.section(&encode::encode_global_section(&m.globals, &mut remapper)?);

    let mut exports_sec = wasm_encoder::ExportSection::new();
    for e in &m.exports {
        let kind = encode::conv_export_kind(e.kind)?;
        let index = if matches!(e.kind, wasmparser::ExternalKind::Func) {
            func_map(e.index)
        } else {
            e.index
        };
        exports_sec.export(e.name, kind, index);
    }
    module.section(&exports_sec);

    // Section order is fixed by the wasm spec: code precedes data.
    let mut code_sec = wasm_encoder::CodeSection::new();
    {
        let mut remapper = IndexRemapper::new(func_map, global_map);
        for body in &m.code {
            let sites = scan_function_loops(body, existing_g_index)?;
            let unguarded_offsets: std::collections::BTreeSet<usize> = sites
                .iter()
                .filter(|s| !s.guarded)
                .map(|s| s.offset)
                .collect();

            if unguarded_offsets.is_empty() && !need_new_import {
                // Nothing in this body changes at all.
                if !ir::body_needs_remap(body, &func_map, &global_map)? {
                    code_sec.raw(body.as_bytes());
                    continue;
                }
            }

            let built = ir::rebuild_function_body(body, &mut remapper, |op, offset, func| {
                if matches!(op, wasmparser::Operator::Loop { .. })
                    && unguarded_offsets.contains(&offset)
                {
                    let id = (1u32 << 30) + counter;
                    counter += 1;
                    func.instruction(&wasm_encoder::Instruction::I32Const(id as i32));
                    func.instruction(&wasm_encoder::Instruction::I32Const(
                        opts.default_maxiter as i32,
                    ));
                    func.instruction(&wasm_encoder::Instruction::Call(g_index));
                    func.instruction(&wasm_encoder::Instruction::Drop);
                }
                Ok(())
            })?;
            code_sec.function(&built);
        }
    }
    module.section(&code_sec);

    let mut remapper = IndexRemapper::new(func_map, global_map);
    module.section(&encode::encode_data_section(&m.datas, &mut remapper)?);

    Ok(module.finish())
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::unwrap_used,
    clippy::indexing_slicing,
    clippy::panic,
    deprecated
)]
mod tests {
    use super::*;

    fn body_bytes(ops: &[wasm_encoder::Instruction]) -> Vec<u8> {
        let mut f = wasm_encoder::Function::new(std::iter::empty::<(u32, wasm_encoder::ValType)>());
        for op in ops {
            f.instruction(op);
        }
        f.instruction(&wasm_encoder::Instruction::End);
        f.into_raw_body()
    }

    fn parse_body(bytes: &[u8]) -> wasmparser::FunctionBody<'_> {
        wasmparser::FunctionBody::new(wasmparser::BinaryReader::new(bytes, 0))
    }

    fn reader_after_loop<'a>(
        body: &'a wasmparser::FunctionBody<'a>,
    ) -> wasmparser::OperatorsReader<'a> {
        let mut r = body.get_operators_reader().expect("operators");
        loop {
            match r.read().expect("op") {
                wasmparser::Operator::Loop { .. } => return r,
                _ => continue,
            }
        }
    }

    // -- is_guard_prologue --------------------------------------------------

    #[test]
    fn is_guard_prologue_valid_sequence_is_true() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(10),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_call_to_different_import_is_false() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(10),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(99)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_only_one_i32_const_is_false() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_loop_at_end_of_body_is_false() {
        let bytes = body_bytes(&[wasm_encoder::Instruction::Loop(
            wasm_encoder::BlockType::Empty,
        )]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_zero_maxiter_is_false() {
        // `Guard.h` rejects a zero `maxiter` outright ("Guard call cannot
        // specify 0 maxiter"), so a zero-maxiter prologue must count as
        // unguarded here too.
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, Some(3)).expect("valid"));
    }

    #[test]
    fn is_guard_prologue_no_g_index_is_false() {
        let bytes = body_bytes(&[
            wasm_encoder::Instruction::Loop(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::I32Const(10),
            wasm_encoder::Instruction::Call(3),
            wasm_encoder::Instruction::End,
        ]);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        assert!(!is_guard_prologue(&r, None).expect("valid"));
    }

    // -- guess_loop_body / guard_hint --------------------------------------------

    fn guess_of(loop_body: &[wasm_encoder::Instruction]) -> LoopBodyGuess {
        let mut ops = vec![wasm_encoder::Instruction::Loop(
            wasm_encoder::BlockType::Empty,
        )];
        ops.extend_from_slice(loop_body);
        ops.push(wasm_encoder::Instruction::End); // closes loop
        // `body_bytes` appends its own trailing `End` for the function.
        let bytes = body_bytes(&ops);
        let body = parse_body(&bytes);
        let r = reader_after_loop(&body);
        guess_loop_body(&r).expect("valid")
    }

    #[test]
    fn guess_load_only_loop_is_compare_like() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::Drop,
        ]);
        assert_eq!(guess, LoopBodyGuess::CompareLike);
        assert!(guard_hint(guess).expect("hint").contains("buf_eq"));
    }

    #[test]
    fn guess_load_and_store_loop_is_copy_like() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
        ]);
        assert_eq!(guess, LoopBodyGuess::CopyLike);
        assert!(guard_hint(guess).is_some());
    }

    #[test]
    fn guess_store_only_loop_is_zero_init_like() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Store(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
        ]);
        assert_eq!(guess, LoopBodyGuess::ZeroInitLike);
        assert!(guard_hint(guess).is_some());
    }

    #[test]
    fn guess_loop_with_any_call_is_unknown() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::Drop,
            wasm_encoder::Instruction::Call(0),
            wasm_encoder::Instruction::Drop,
        ]);
        assert_eq!(guess, LoopBodyGuess::Unknown);
        assert!(guard_hint(guess).is_none());
    }

    #[test]
    fn guess_nested_if_inside_loop_still_classified() {
        let guess = guess_of(&[
            wasm_encoder::Instruction::I32Const(1),
            wasm_encoder::Instruction::If(wasm_encoder::BlockType::Empty),
            wasm_encoder::Instruction::I32Const(0),
            wasm_encoder::Instruction::I32Load(wasm_encoder::MemArg {
                offset: 0,
                align: 0,
                memory_index: 0,
            }),
            wasm_encoder::Instruction::Drop,
            wasm_encoder::Instruction::End,
        ]);
        assert_eq!(guess, LoopBodyGuess::CompareLike);
    }

    // -- auto_guard pass-level -------------------------------------------------

    fn wasm(src: &str) -> Vec<u8> {
        wat::parse_str(src).expect("fixture is valid wat")
    }

    fn opts() -> Options {
        Options::default()
    }

    const TWO_UNGUARDED_LOOPS: &str = r#"
    (module
      (func $hook (param i32) (result i64)
        (local $i i32)
        (loop $a
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (br_if $a (i32.lt_u (local.get $i) (i32.const 10))))
        (loop $b
          (local.set $i (i32.sub (local.get $i) (i32.const 1)))
          (br_if $b (i32.gt_u (local.get $i) (i32.const 0))))
        (i64.const 0))
      (export "hook" (func $hook)))
    "#;

    #[test]
    fn table_or_element_input_errors() {
        let src = r#"
        (module
          (table 1 funcref)
          (func $hook (param i32) (result i64) (i64.const 0))
          (export "hook" (func $hook)))
        "#;
        let err = auto_guard(&wasm(src), &opts()).unwrap_err();
        assert!(err.to_string().contains("table or element"), "{err}");
    }

    #[test]
    fn two_unguarded_loops_get_sequential_ids() {
        let out = auto_guard(&wasm(TWO_UNGUARDED_LOOPS), &opts()).expect("auto_guard succeeds");
        let m = ir::parse(&out).expect("re-parse");
        let g_index = find_g_index(&m).expect("_g present");
        let body = &m.code[0];
        let sites = scan_function_loops(body, Some(g_index)).expect("scan");
        assert_eq!(sites.len(), 2);

        // Collect the two inserted `id` constants (first i32.const after
        // each loop) by re-reading operators directly.
        let mut ids = Vec::new();
        let mut r = body.get_operators_reader().expect("operators");
        while !r.eof() {
            if let wasmparser::Operator::Loop { .. } = r.read().expect("op") {
                let id_op = r.read().expect("id const");
                if let wasmparser::Operator::I32Const { value } = id_op {
                    ids.push(value as u32);
                }
                let maxiter_op = r.read().expect("maxiter const");
                assert_eq!(
                    maxiter_op,
                    wasmparser::Operator::I32Const {
                        value: opts().default_maxiter as i32
                    }
                );
            }
        }
        assert_eq!(ids, vec![1u32 << 30, (1u32 << 30) + 1]);
    }

    #[test]
    fn missing_g_is_appended_and_shifts_every_index() {
        let out = auto_guard(&wasm(TWO_UNGUARDED_LOOPS), &opts()).expect("auto_guard succeeds");
        let m = ir::parse(&out).expect("re-parse");
        let g_index = find_g_index(&m).expect("_g present");
        assert_eq!(g_index, 0, "_g appended as the only (thus first) import");
        // `hook`'s function index must have shifted from 0 to 1.
        let hook_export = m
            .exports
            .iter()
            .find(|e| e.name == "hook")
            .expect("hook export");
        assert_eq!(hook_export.index, 1);
    }

    #[test]
    fn fully_guarded_module_is_returned_unchanged() {
        let src = r#"
        (module
          (import "env" "_g" (func $g (param i32 i32) (result i32)))
          (func $hook (param i32) (result i64)
            (local $i i32)
            (loop $l
              (call $g (i32.const 1) (i32.const 10))
              drop
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br_if $l (i32.lt_u (local.get $i) (i32.const 10))))
            (i64.const 0))
          (export "hook" (func $hook)))
        "#;
        let input = wasm(src);
        let out = auto_guard(&input, &opts()).expect("auto_guard succeeds");
        assert_eq!(out, input, "already-guarded module must be byte-identical");
    }

    #[test]
    fn existing_g_import_is_reused_not_duplicated() {
        let src = r#"
        (module
          (import "env" "_g" (func $g (param i32 i32) (result i32)))
          (func $hook (param i32) (result i64)
            (local $i i32)
            (loop $l
              (local.set $i (i32.add (local.get $i) (i32.const 1)))
              (br_if $l (i32.lt_u (local.get $i) (i32.const 10))))
            (i64.const 0))
          (export "hook" (func $hook)))
        "#;
        let out = auto_guard(&wasm(src), &opts()).expect("auto_guard succeeds");
        let m = ir::parse(&out).expect("re-parse");
        assert_eq!(m.num_imported_funcs(), 1, "no new import should be added");
    }
}
