// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/tts.h — DO NOT EDIT BY HAND.
//! Build-side transaction-type name/code table.
//!
//! Consumed by `rshooks_build::metadata` to validate `#[hooks]` entries'
//! `on`/`can_emit` transaction-type lists and to encode the HookOn /
//! HookCanEmit bitmasks — the build-side counterpart of
//! `rshooks::tx_type::TxType`, generated from the same `tts.h` constants so
//! the two can never drift apart.

/// Canonical Xahau JSON spellings for every known `TxType` variant
/// (excluding the data-carrying `Unknown`), used to validate
/// `#[hooks]` entries' `on`/`can_emit` transaction-type lists.
/// Position-for-position with [`TRANSACTION_TYPE_CODES`], and using
/// the exact same spellings as `rshooks::tx_type::TxType`.
pub(crate) const TRANSACTION_TYPES: &[&str] = &[
    "Payment",
    "EscrowCreate",
    "EscrowFinish",
    "AccountSet",
    "EscrowCancel",
    "SetRegularKey",
    "OfferCreate",
    "OfferCancel",
    "TicketCreate",
    "SignerListSet",
    "PaymentChannelCreate",
    "PaymentChannelFund",
    "PaymentChannelClaim",
    "CheckCreate",
    "CheckCash",
    "CheckCancel",
    "DepositPreauth",
    "TrustSet",
    "AccountDelete",
    "SetHook",
    "NFTokenMint",
    "NFTokenBurn",
    "NFTokenCreateOffer",
    "NFTokenCancelOffer",
    "NFTokenAcceptOffer",
    "Clawback",
    "AMMClawback",
    "AMMCreate",
    "AMMDeposit",
    "AMMWithdraw",
    "AMMVote",
    "AMMBid",
    "AMMDelete",
    "URITokenMint",
    "URITokenBurn",
    "URITokenBuy",
    "URITokenCreateSellOffer",
    "URITokenCancelSellOffer",
    "XChainCreateClaimID",
    "XChainCommit",
    "XChainClaim",
    "XChainAccountCreateCommit",
    "XChainAddClaimAttestation",
    "XChainAddAccountCreateAttestation",
    "XChainModifyBridge",
    "XChainCreateBridge",
    "DIDSet",
    "DIDDelete",
    "OracleSet",
    "OracleDelete",
    "LedgerStateFix",
    "MPTokenIssuanceCreate",
    "MPTokenIssuanceDestroy",
    "MPTokenIssuanceSet",
    "MPTokenAuthorize",
    "CredentialCreate",
    "CredentialAccept",
    "CredentialDelete",
    "NFTokenModify",
    "PermissionedDomainSet",
    "PermissionedDomainDelete",
    "Cron",
    "CronSet",
    "SetRemarks",
    "Remit",
    "GenesisMint",
    "Import",
    "ClaimReward",
    "Invoke",
    "EnableAmendment",
    "SetFee",
    "UNLModify",
    "EmitFailure",
    "UNLReport",
];

/// `tt*` codes corresponding position-for-position to
/// [`TRANSACTION_TYPES`].
pub(crate) const TRANSACTION_TYPE_CODES: &[u8] = &[
    0, 1, 2, 3, 4, 5, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 25, 26, 27, 28, 29, 30,
    31, 35, 36, 37, 38, 39, 40, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
    62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103,
    104,
];
