// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/extern.h — DO NOT EDIT BY HAND.
//! The Hook API import whitelist.
//!
//! The single source of truth for which functions a Hook is allowed to
//! import from module `env`, and with which signature — generated from the
//! same `extern.h` parse as `rshooks-core`'s `src/api.rs`, so the two can
//! never drift apart.

use wasm_encoder::ValType;

/// One entry in the Hook API whitelist: an import name, its parameter types,
/// and its single result type.
#[derive(Debug, Clone, Copy)]
pub struct ApiFn {
    /// The import name (as it appears after `wasm_import_module = "env"`).
    pub name: &'static str,
    /// Parameter types, in order.
    pub params: &'static [ValType],
    /// The single result type (every Hook API function, including `_g`,
    /// returns exactly one value).
    pub result: ValType,
}

const I32: ValType = ValType::I32;
const I64: ValType = ValType::I64;

/// Every function a Hook may import from module `env`: `_g` plus every
/// other Hook API function from `extern.h`, in header order.
pub static WHITELIST: &[ApiFn] = &[
    ApiFn {
        name: "_g",
        params: &[I32, I32],
        result: I32,
    },
    ApiFn {
        name: "accept",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "rollback",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "util_raddr",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_accid",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_verify",
        params: &[I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_sha512h",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_keylet",
        params: &[I32, I32, I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_validate",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_subfield",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_subarray",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_emplace",
        params: &[I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_erase",
        params: &[I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_burden",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "etxn_details",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_fee_base",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_reserve",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_generation",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "etxn_nonce",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "emit",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_set",
        params: &[I32, I64],
        result: I64,
    },
    ApiFn {
        name: "float_multiply",
        params: &[I64, I64],
        result: I64,
    },
    ApiFn {
        name: "float_mulratio",
        params: &[I64, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_negate",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_compare",
        params: &[I64, I64, I32],
        result: I64,
    },
    ApiFn {
        name: "float_sum",
        params: &[I64, I64],
        result: I64,
    },
    ApiFn {
        name: "float_sto",
        params: &[I32, I32, I32, I32, I32, I32, I64, I32],
        result: I64,
    },
    ApiFn {
        name: "float_sto_set",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_invert",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_divide",
        params: &[I64, I64],
        result: I64,
    },
    ApiFn {
        name: "float_one",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "float_mantissa",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_sign",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_int",
        params: &[I64, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_log",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_root",
        params: &[I64, I32],
        result: I64,
    },
    ApiFn {
        name: "fee_base",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "ledger_seq",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "ledger_last_time",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "ledger_last_hash",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "ledger_nonce",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "ledger_keylet",
        params: &[I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_account",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_hash",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_param_set",
        params: &[I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_param",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_again",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "hook_skip",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_pos",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "slot",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_clear",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "slot_count",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "slot_set",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_size",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "slot_subarray",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_subfield",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_type",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_float",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "state_set",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "state_foreign_set",
        params: &[I32, I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "state",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "state_foreign",
        params: &[I32, I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "trace",
        params: &[I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "trace_num",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "trace_float",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "otxn_burden",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "otxn_field",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "otxn_generation",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "otxn_id",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "otxn_type",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "otxn_slot",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "otxn_param",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "meta_slot",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "xpop_slot",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "prepare",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
];

/// Looks up a whitelist entry by name.
#[must_use]
pub fn lookup(name: &str) -> Option<&'static ApiFn> {
    WHITELIST.iter().find(|f| f.name == name)
}
