//! The Hook API import whitelist.
//!
//! This is the single source of truth for which functions a Hook is allowed
//! to import from module `env`, and with which signature. It is generated by
//! hand from `hook/extern.h` (upstream `Xahau/xahaud`, branch `release`) and
//! must stay in sync with `rshooks-core`'s `src/api.rs`, which mirrors the same
//! header. A unit test below cross-checks the two so they can never drift.

use wasm_encoder::ValType;

/// One entry in the Hook API whitelist: an import name, its parameter types,
/// and its single result type.
#[derive(Debug, Clone, Copy)]
pub struct ApiFn {
    /// The import name (as it appears after `wasm_import_module = "env"`).
    pub name: &'static str,
    /// Parameter types, in order.
    pub params: &'static [ValType],
    /// The single result type (every Hook API function, including `_g`,
    /// returns exactly one value).
    pub result: ValType,
}

const I32: ValType = ValType::I32;
const I64: ValType = ValType::I64;

/// All 75 functions a Hook may import from module `env`: `_g` plus the 74
/// Hook API functions from `extern.h`, in header order.
pub static WHITELIST: &[ApiFn] = &[
    ApiFn {
        name: "_g",
        params: &[I32, I32],
        result: I32,
    },
    ApiFn {
        name: "accept",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "rollback",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "util_raddr",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_accid",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_verify",
        params: &[I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_sha512h",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "util_keylet",
        params: &[I32, I32, I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_validate",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_subfield",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_subarray",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_emplace",
        params: &[I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "sto_erase",
        params: &[I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_burden",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "etxn_details",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_fee_base",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_reserve",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "etxn_generation",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "etxn_nonce",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "emit",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_set",
        params: &[I32, I64],
        result: I64,
    },
    ApiFn {
        name: "float_multiply",
        params: &[I64, I64],
        result: I64,
    },
    ApiFn {
        name: "float_mulratio",
        params: &[I64, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_negate",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_compare",
        params: &[I64, I64, I32],
        result: I64,
    },
    ApiFn {
        name: "float_sum",
        params: &[I64, I64],
        result: I64,
    },
    ApiFn {
        name: "float_sto",
        params: &[I32, I32, I32, I32, I32, I32, I64, I32],
        result: I64,
    },
    ApiFn {
        name: "float_sto_set",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_invert",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_divide",
        params: &[I64, I64],
        result: I64,
    },
    ApiFn {
        name: "float_one",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "float_mantissa",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_sign",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_int",
        params: &[I64, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "float_log",
        params: &[I64],
        result: I64,
    },
    ApiFn {
        name: "float_root",
        params: &[I64, I32],
        result: I64,
    },
    ApiFn {
        name: "fee_base",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "ledger_seq",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "ledger_last_time",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "ledger_last_hash",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "ledger_nonce",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "ledger_keylet",
        params: &[I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_account",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_hash",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_param_set",
        params: &[I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_param",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_again",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "hook_skip",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "hook_pos",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "slot",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_clear",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "slot_count",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "slot_set",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_size",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "slot_subarray",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_subfield",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_type",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "slot_float",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "state_set",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "state_foreign_set",
        params: &[I32, I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "state",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "state_foreign",
        params: &[I32, I32, I32, I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "trace",
        params: &[I32, I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "trace_num",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "trace_float",
        params: &[I32, I32, I64],
        result: I64,
    },
    ApiFn {
        name: "otxn_burden",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "otxn_field",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "otxn_generation",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "otxn_id",
        params: &[I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "otxn_type",
        params: &[],
        result: I64,
    },
    ApiFn {
        name: "otxn_slot",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "otxn_param",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
    ApiFn {
        name: "meta_slot",
        params: &[I32],
        result: I64,
    },
    ApiFn {
        name: "xpop_slot",
        params: &[I32, I32],
        result: I64,
    },
    ApiFn {
        name: "prepare",
        params: &[I32, I32, I32, I32],
        result: I64,
    },
];

/// Looks up a whitelist entry by name.
#[must_use]
pub fn lookup(name: &str) -> Option<&'static ApiFn> {
    WHITELIST.iter().find(|f| f.name == name)
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]
mod tests {
    use super::*;

    /// `rshooks-core`'s `src/api.rs` is the mechanical translation of the same
    /// `extern.h` header this whitelist is generated from. Parses the
    /// `pub fn NAME(params) -> ret;` declarations out of that file (a naive
    /// text parse, as they appear verbatim inside the
    /// `#[cfg(target_arch = "wasm32")] unsafe extern "C" { ... }` block) and
    /// checks every whitelist entry matches rshooks-core exactly, with no
    /// rshooks-core declaration missing — this is what keeps the two crates
    /// from silently drifting apart.
    #[test]
    fn whitelist_matches_rshooks_core_api() {
        let src = include_str!("../../rshooks-core/src/api.rs");
        let parsed = parse_extern_fns(src);

        assert_eq!(
            parsed.len(),
            WHITELIST.len(),
            "rshooks-core/src/api.rs declares {} extern fns but the whitelist has {}",
            parsed.len(),
            WHITELIST.len()
        );

        for (name, params, result) in &parsed {
            let entry = lookup(name).unwrap_or_else(|| {
                panic!("rshooks-core declares `{name}` but it is not whitelisted")
            });
            assert_eq!(
                entry.params,
                params.as_slice(),
                "param mismatch for `{name}`"
            );
            assert_eq!(entry.result, *result, "result mismatch for `{name}`");
        }
    }

    /// Naively parses `pub fn NAME(arg: TYPE, ...) -> RET;` declarations
    /// (only those without an `unsafe` prefix, i.e. only the ones inside the
    /// wasm-import extern block, not the host-stub module) out of the given
    /// Rust source text.
    fn parse_extern_fns(src: &str) -> Vec<(String, Vec<ValType>, ValType)> {
        // A declaration may span multiple lines when rustfmt wraps long
        // argument lists; normalize by stripping newlines between a `pub fn`
        // and its terminating `;`.
        let mut joined = String::new();
        let mut depth: i32 = 0;
        let mut in_decl = false;
        for line in src.lines() {
            let trimmed = line.trim();
            if !in_decl {
                if trimmed.starts_with("pub fn ") {
                    in_decl = true;
                } else {
                    continue;
                }
            }
            joined.push_str(trimmed);
            joined.push(' ');
            depth += trimmed.matches('(').count() as i32;
            depth -= trimmed.matches(')').count() as i32;
            if in_decl && depth <= 0 && trimmed.ends_with(';') {
                joined.push('\n');
                in_decl = false;
                depth = 0;
            }
        }

        let mut out = Vec::new();
        for decl in joined.lines() {
            let decl = decl.trim();
            if decl.is_empty() {
                continue;
            }
            let rest = decl
                .strip_prefix("pub fn ")
                .expect("filtered to `pub fn ` lines");
            let name_end = rest.find('(').expect("declaration has `(`");
            let name = rest[..name_end].trim().to_string();
            let after_name = &rest[name_end + 1..];
            let args_end = after_name.find(')').expect("declaration has `)`");
            let args_str = &after_name[..args_end];
            let mut params = Vec::new();
            if !args_str.trim().is_empty() {
                for arg in args_str.split(',') {
                    let arg = arg.trim();
                    if arg.is_empty() {
                        continue;
                    }
                    let ty_str = arg.split(':').nth(1).expect("arg has a type").trim();
                    params.push(parse_valtype(ty_str));
                }
            }
            let after_args = &after_name[args_end + 1..];
            let result = if let Some(arrow) = after_args.find("->") {
                let ty_str = after_args[arrow + 2..].trim().trim_end_matches(';').trim();
                parse_valtype(ty_str)
            } else {
                panic!("declaration for `{name}` has no return type");
            };
            out.push((name, params, result));
        }
        out
    }

    fn parse_valtype(s: &str) -> ValType {
        match s {
            "u32" | "i32" => ValType::I32,
            "u64" | "i64" => ValType::I64,
            other => panic!("unexpected C-mirrored type `{other}` in rshooks-core api.rs"),
        }
    }
}
