//! Per-file generators: each submodule turns one or two parsed vendored
//! headers into the exact `crates/rshooks-core/src/*.rs` file content
//! described by `docs/DESIGN.md` §4.

/// Generates `crates/rshooks-core/src/api.rs` from `extern.h`.
pub mod api;
/// Generates `crates/rshooks-core/src/consts.rs` from `hookapi.h`/`macro.h`.
pub mod consts;
/// Generates `crates/rshooks-core/src/error.rs` from `error.h`.
pub mod error;
/// Generates `crates/rshooks-core/src/host.rs`: the `HookHost` trait + `Guest`.
pub mod host;
/// Generates `crates/rshooks-core/src/lets.rs` from the ledger entry
/// formats in `protocol_formats.json`.
pub mod lets;
/// Generates `crates/rshooks-core/src/ls_flags.rs` from `ls_flags.h`.
pub mod ls_flags;
/// Generates `crates/rshooks-core/src/sfcodes.rs` from `sfcodes.h`.
pub mod sfcodes;
/// Generates `crates/rshooks/src/sfield.rs` (typed `SField<T>` field
/// constants) from `sfcodes.h` — the typed mirror of [`sfcodes`]'s raw
/// table, in `rshooks` for the same reason [`tx_type`] is.
pub mod sfield;
/// Generates `crates/rshooks-core/src/tts.rs` from `tts.h`.
pub mod tts;
/// Generates `crates/rshooks-core/src/tx_flags.rs` from `tx_flags.h`.
pub mod tx_flags;

/// Generates `crates/rshooks/src/ledger_entry_type.rs` (a typed
/// `LedgerEntryType` enum) from `protocol_formats.json` — the ledger-entry
/// counterpart of [`tx_type`], and in `rshooks` for the same reason.
pub mod ledger_entry_type;
/// Generates `crates/rshooks/src/tx_type.rs` (a typed `TxType` enum) from
/// `tts.h` — one of the generators in this module whose output lands
/// outside `rshooks-core`; see its own module doc comment for why.
pub mod tx_type;
/// Generates `crates/rshooks-build/src/tx_type_table.rs` (the build-side
/// transaction-type name/code table) from `tts.h`, sharing [`tx_type`]'s
/// name spellings so the typed enum and the build-side validator can never
/// drift apart; see its own module doc comment for why.
pub mod tx_type_table;
/// Generates `crates/rshooks/src/views/{tx,ledger,inner}.rs` (typed read
/// views over every declared format) from `protocol_formats.json`.
pub mod views;

/// Prepends the required `// @generated ...` marker to a module's `//!`
/// doc-comment body, per `docs/DESIGN.md` §4 / the xtask spec: every
/// generated file starts with this marker, followed immediately by its
/// module-level docs. `inputs` names a file in the `xahaud-hook` vendor
/// group; see [`with_generated_marker_in`] for the other group.
pub fn with_generated_marker(inputs: &str, module_doc: &str) -> String {
    with_generated_marker_in("xahaud-hook", inputs, module_doc)
}

/// [`with_generated_marker`] for a generator whose input lives in a vendor
/// group other than `xahaud-hook` — the protocol format definitions in
/// `xahaud-protocol`.
pub fn with_generated_marker_in(vendor_group: &str, inputs: &str, module_doc: &str) -> String {
    format!(
        "// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/{vendor_group}/{inputs} — DO NOT EDIT BY HAND.\n{module_doc}"
    )
}

/// Appends one `/// <line>` doc comment followed by `pub const NAME: TY =
/// VALUE;` to `buf`. `doc_lines` may be more than one line (used for the
/// one hand-annotated irregular value in `error.rs`).
pub fn push_const(buf: &mut String, doc_lines: &[String], name: &str, ty: &str, value: &str) {
    for line in doc_lines {
        buf.push_str("/// ");
        buf.push_str(line);
        buf.push('\n');
    }
    buf.push_str("pub const ");
    buf.push_str(name);
    buf.push_str(": ");
    buf.push_str(ty);
    buf.push_str(" = ");
    buf.push_str(value);
    buf.push_str(";\n");
}
