[package]
name = "xfl-math"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
test = false

[dependencies]
rshooks = { workspace = true, features = ["host-panic-handler"] }

[dev-dependencies]
rshooks = { workspace = true, features = ["testenv"] }
rshooks-testenv.workspace = true

[lints]
workspace = true
