// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/extern.h (via hook_api.json) — DO NOT EDIT BY HAND.
//! `HookHost`: the raw Hook API as a trait, plus `Guest`, the trait's one
//! real implementor.
//!
//! Generated from `crates/rshooks-core/hook_api.json` (`crates/xtask/src/ir.rs`),
//! itself generated from `extern.h` (`docs/DESIGN.md` §4). Every method here
//! is a 1:1 forward to the same-named function in [`crate::api`] — same
//! name, same signature (raw `u32`/`i64` Hook API types), same safety
//! contract — so this trait adds an indirection point without adding any
//! logic: swap `Guest` for another `HookHost` implementor (e.g. a native
//! test host) and every Hook API call routes through it instead.
//!
//! `rshooks` and the examples do not use this trait today — the flat
//! free-function API in [`crate::api`] remains the public surface they call
//! (`docs/DESIGN.md` §4/§5).
//!
//! **Deprecated.** `HookHost`'s methods take raw `u32` pointers, so an
//! implementor cannot soundly read a caller's buffer on a 64-bit host; it
//! cannot serve as a native test seam. That role belongs to
//! `rshooks_core::backend::HostBackend` (present only on native builds with
//! the `testenv` feature), which uses semantic Rust types instead of FFI
//! signatures. `HookHost`/`Guest` are kept for this release as published
//! API with no known consumers, and will be removed in the next breaking
//! release.

/// Every Hook API host function (`_g` plus the 74 `extern.h` functions), as
/// trait methods with the exact same names, parameter names/types, and return
/// types as `crate::api`'s free functions and `extern.h` itself.
#[deprecated(
    note = "implement rshooks_core::backend::HostBackend instead; HookHost will be removed in the next breaking release"
)]
#[allow(clippy::missing_safety_doc)]
pub trait HookHost {
    /// C: `int32_t _g(uint32_t guard_id, uint32_t maxiter)` (extern.h)
    unsafe fn _g(&self, guard_id: u32, maxiter: u32) -> i32;

    /// C: `int64_t accept(uint32_t read_ptr, uint32_t read_len, int64_t error_code)` (extern.h)
    unsafe fn accept(&self, read_ptr: u32, read_len: u32, error_code: i64) -> i64;

    /// C: `int64_t rollback(uint32_t read_ptr, uint32_t read_len, int64_t error_code)` (extern.h)
    unsafe fn rollback(&self, read_ptr: u32, read_len: u32, error_code: i64) -> i64;

    /// C: `int64_t util_raddr(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn util_raddr(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64;

    /// C: `int64_t util_accid(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn util_accid(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64;

    /// C: `int64_t util_verify(uint32_t dread_ptr, uint32_t dread_len, uint32_t sread_ptr, uint32_t sread_len, uint32_t kread_ptr, uint32_t kread_len)` (extern.h)
    unsafe fn util_verify(
        &self,
        dread_ptr: u32,
        dread_len: u32,
        sread_ptr: u32,
        sread_len: u32,
        kread_ptr: u32,
        kread_len: u32,
    ) -> i64;

    /// C: `int64_t util_sha512h(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn util_sha512h(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64;

    /// C: `int64_t util_keylet(uint32_t write_ptr, uint32_t write_len, uint32_t keylet_type, uint32_t a, uint32_t b, uint32_t c, uint32_t d, uint32_t e, uint32_t f)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn util_keylet(
        &self,
        write_ptr: u32,
        write_len: u32,
        keylet_type: u32,
        a: u32,
        b: u32,
        c: u32,
        d: u32,
        e: u32,
        f: u32,
    ) -> i64;

    /// C: `int64_t sto_validate(uint32_t tread_ptr, uint32_t tread_len)` (extern.h)
    unsafe fn sto_validate(&self, tread_ptr: u32, tread_len: u32) -> i64;

    /// C: `int64_t sto_subfield(uint32_t read_ptr, uint32_t read_len, uint32_t field_id)` (extern.h)
    unsafe fn sto_subfield(&self, read_ptr: u32, read_len: u32, field_id: u32) -> i64;

    /// C: `int64_t sto_subarray(uint32_t read_ptr, uint32_t read_len, uint32_t array_id)` (extern.h)
    unsafe fn sto_subarray(&self, read_ptr: u32, read_len: u32, array_id: u32) -> i64;

    /// C: `int64_t sto_emplace(uint32_t write_ptr, uint32_t write_len, uint32_t sread_ptr, uint32_t sread_len, uint32_t fread_ptr, uint32_t fread_len, uint32_t field_id)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn sto_emplace(
        &self,
        write_ptr: u32,
        write_len: u32,
        sread_ptr: u32,
        sread_len: u32,
        fread_ptr: u32,
        fread_len: u32,
        field_id: u32,
    ) -> i64;

    /// C: `int64_t sto_erase(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len, uint32_t field_id)` (extern.h)
    unsafe fn sto_erase(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
        field_id: u32,
    ) -> i64;

    /// C: `int64_t etxn_burden()` (extern.h)
    unsafe fn etxn_burden(&self) -> i64;

    /// C: `int64_t etxn_details(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn etxn_details(&self, write_ptr: u32, write_len: u32) -> i64;

    /// C: `int64_t etxn_fee_base(uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn etxn_fee_base(&self, read_ptr: u32, read_len: u32) -> i64;

    /// C: `int64_t etxn_reserve(uint32_t count)` (extern.h)
    unsafe fn etxn_reserve(&self, count: u32) -> i64;

    /// C: `int64_t etxn_generation()` (extern.h)
    unsafe fn etxn_generation(&self) -> i64;

    /// C: `int64_t etxn_nonce(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn etxn_nonce(&self, write_ptr: u32, write_len: u32) -> i64;

    /// C: `int64_t emit(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn emit(&self, write_ptr: u32, write_len: u32, read_ptr: u32, read_len: u32) -> i64;

    /// C: `int64_t float_set(int32_t exponent, int64_t mantissa)` (extern.h)
    unsafe fn float_set(&self, exponent: i32, mantissa: i64) -> i64;

    /// C: `int64_t float_multiply(int64_t float1, int64_t float2)` (extern.h)
    unsafe fn float_multiply(&self, float1: i64, float2: i64) -> i64;

    /// C: `int64_t float_mulratio(int64_t float1, uint32_t round_up, uint32_t numerator, uint32_t denominator)` (extern.h)
    unsafe fn float_mulratio(
        &self,
        float1: i64,
        round_up: u32,
        numerator: u32,
        denominator: u32,
    ) -> i64;

    /// C: `int64_t float_negate(int64_t float1)` (extern.h)
    unsafe fn float_negate(&self, float1: i64) -> i64;

    /// C: `int64_t float_compare(int64_t float1, int64_t float2, uint32_t mode)` (extern.h)
    unsafe fn float_compare(&self, float1: i64, float2: i64, mode: u32) -> i64;

    /// C: `int64_t float_sum(int64_t float1, int64_t float2)` (extern.h)
    unsafe fn float_sum(&self, float1: i64, float2: i64) -> i64;

    /// C: `int64_t float_sto(uint32_t write_ptr, uint32_t write_len, uint32_t cread_ptr, uint32_t cread_len, uint32_t iread_ptr, uint32_t iread_len, int64_t float1, uint32_t field_code)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn float_sto(
        &self,
        write_ptr: u32,
        write_len: u32,
        cread_ptr: u32,
        cread_len: u32,
        iread_ptr: u32,
        iread_len: u32,
        float1: i64,
        field_code: u32,
    ) -> i64;

    /// C: `int64_t float_sto_set(uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn float_sto_set(&self, read_ptr: u32, read_len: u32) -> i64;

    /// C: `int64_t float_invert(int64_t float1)` (extern.h)
    unsafe fn float_invert(&self, float1: i64) -> i64;

    /// C: `int64_t float_divide(int64_t float1, int64_t float2)` (extern.h)
    unsafe fn float_divide(&self, float1: i64, float2: i64) -> i64;

    /// C: `int64_t float_one()` (extern.h)
    unsafe fn float_one(&self) -> i64;

    /// C: `int64_t float_mantissa(int64_t float1)` (extern.h)
    unsafe fn float_mantissa(&self, float1: i64) -> i64;

    /// C: `int64_t float_sign(int64_t float1)` (extern.h)
    unsafe fn float_sign(&self, float1: i64) -> i64;

    /// C: `int64_t float_int(int64_t float1, uint32_t decimal_places, uint32_t abs)` (extern.h)
    unsafe fn float_int(&self, float1: i64, decimal_places: u32, abs: u32) -> i64;

    /// C: `int64_t float_log(int64_t float1)` (extern.h)
    unsafe fn float_log(&self, float1: i64) -> i64;

    /// C: `int64_t float_root(int64_t float1, uint32_t n)` (extern.h)
    unsafe fn float_root(&self, float1: i64, n: u32) -> i64;

    /// C: `int64_t fee_base()` (extern.h)
    unsafe fn fee_base(&self) -> i64;

    /// C: `int64_t ledger_seq()` (extern.h)
    unsafe fn ledger_seq(&self) -> i64;

    /// C: `int64_t ledger_last_time()` (extern.h)
    unsafe fn ledger_last_time(&self) -> i64;

    /// C: `int64_t ledger_last_hash(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn ledger_last_hash(&self, write_ptr: u32, write_len: u32) -> i64;

    /// C: `int64_t ledger_nonce(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn ledger_nonce(&self, write_ptr: u32, write_len: u32) -> i64;

    /// C: `int64_t ledger_keylet(uint32_t write_ptr, uint32_t write_len, uint32_t lread_ptr, uint32_t lread_len, uint32_t hread_ptr, uint32_t hread_len)` (extern.h)
    unsafe fn ledger_keylet(
        &self,
        write_ptr: u32,
        write_len: u32,
        lread_ptr: u32,
        lread_len: u32,
        hread_ptr: u32,
        hread_len: u32,
    ) -> i64;

    /// C: `int64_t hook_account(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn hook_account(&self, write_ptr: u32, write_len: u32) -> i64;

    /// C: `int64_t hook_hash(uint32_t write_ptr, uint32_t write_len, int32_t hook_no)` (extern.h)
    unsafe fn hook_hash(&self, write_ptr: u32, write_len: u32, hook_no: i32) -> i64;

    /// C: `int64_t hook_param_set(uint32_t read_ptr, uint32_t read_len, uint32_t kread_ptr, uint32_t kread_len, uint32_t hread_ptr, uint32_t hread_len)` (extern.h)
    unsafe fn hook_param_set(
        &self,
        read_ptr: u32,
        read_len: u32,
        kread_ptr: u32,
        kread_len: u32,
        hread_ptr: u32,
        hread_len: u32,
    ) -> i64;

    /// C: `int64_t hook_param(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn hook_param(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64;

    /// C: `int64_t hook_again()` (extern.h)
    unsafe fn hook_again(&self) -> i64;

    /// C: `int64_t hook_skip(uint32_t read_ptr, uint32_t read_len, uint32_t flags)` (extern.h)
    unsafe fn hook_skip(&self, read_ptr: u32, read_len: u32, flags: u32) -> i64;

    /// C: `int64_t hook_pos()` (extern.h)
    unsafe fn hook_pos(&self) -> i64;

    /// C: `int64_t slot(uint32_t write_ptr, uint32_t write_len, uint32_t slot)` (extern.h)
    unsafe fn slot(&self, write_ptr: u32, write_len: u32, slot: u32) -> i64;

    /// C: `int64_t slot_clear(uint32_t slot)` (extern.h)
    unsafe fn slot_clear(&self, slot: u32) -> i64;

    /// C: `int64_t slot_count(uint32_t slot)` (extern.h)
    unsafe fn slot_count(&self, slot: u32) -> i64;

    /// C: `int64_t slot_set(uint32_t read_ptr, uint32_t read_len, uint32_t slot)` (extern.h)
    unsafe fn slot_set(&self, read_ptr: u32, read_len: u32, slot: u32) -> i64;

    /// C: `int64_t slot_size(uint32_t slot)` (extern.h)
    unsafe fn slot_size(&self, slot: u32) -> i64;

    /// C: `int64_t slot_subarray(uint32_t parent_slot, uint32_t array_id, uint32_t new_slot)` (extern.h)
    unsafe fn slot_subarray(&self, parent_slot: u32, array_id: u32, new_slot: u32) -> i64;

    /// C: `int64_t slot_subfield(uint32_t parent_slot, uint32_t field_id, uint32_t new_slot)` (extern.h)
    unsafe fn slot_subfield(&self, parent_slot: u32, field_id: u32, new_slot: u32) -> i64;

    /// C: `int64_t slot_type(uint32_t slot_no, uint32_t flags)` (extern.h)
    unsafe fn slot_type(&self, slot_no: u32, flags: u32) -> i64;

    /// C: `int64_t slot_float(uint32_t slot_no)` (extern.h)
    unsafe fn slot_float(&self, slot_no: u32) -> i64;

    /// C: `int64_t state_set(uint32_t read_ptr, uint32_t read_len, uint32_t kread_ptr, uint32_t kread_len)` (extern.h)
    unsafe fn state_set(&self, read_ptr: u32, read_len: u32, kread_ptr: u32, kread_len: u32)
    -> i64;

    /// C: `int64_t state_foreign_set(uint32_t read_ptr, uint32_t read_len, uint32_t kread_ptr, uint32_t kread_len, uint32_t nread_ptr, uint32_t nread_len, uint32_t aread_ptr, uint32_t aread_len)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn state_foreign_set(
        &self,
        read_ptr: u32,
        read_len: u32,
        kread_ptr: u32,
        kread_len: u32,
        nread_ptr: u32,
        nread_len: u32,
        aread_ptr: u32,
        aread_len: u32,
    ) -> i64;

    /// C: `int64_t state(uint32_t write_ptr, uint32_t write_len, uint32_t kread_ptr, uint32_t kread_len)` (extern.h)
    unsafe fn state(&self, write_ptr: u32, write_len: u32, kread_ptr: u32, kread_len: u32) -> i64;

    /// C: `int64_t state_foreign(uint32_t write_ptr, uint32_t write_len, uint32_t kread_ptr, uint32_t kread_len, uint32_t nread_ptr, uint32_t nread_len, uint32_t aread_ptr, uint32_t aread_len)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn state_foreign(
        &self,
        write_ptr: u32,
        write_len: u32,
        kread_ptr: u32,
        kread_len: u32,
        nread_ptr: u32,
        nread_len: u32,
        aread_ptr: u32,
        aread_len: u32,
    ) -> i64;

    /// C: `int64_t trace(uint32_t mread_ptr, uint32_t mread_len, uint32_t dread_ptr, uint32_t dread_len, uint32_t as_hex)` (extern.h)
    unsafe fn trace(
        &self,
        mread_ptr: u32,
        mread_len: u32,
        dread_ptr: u32,
        dread_len: u32,
        as_hex: u32,
    ) -> i64;

    /// C: `int64_t trace_num(uint32_t read_ptr, uint32_t read_len, int64_t number)` (extern.h)
    unsafe fn trace_num(&self, read_ptr: u32, read_len: u32, number: i64) -> i64;

    /// C: `int64_t trace_float(uint32_t read_ptr, uint32_t read_len, int64_t float1)` (extern.h)
    unsafe fn trace_float(&self, read_ptr: u32, read_len: u32, float1: i64) -> i64;

    /// C: `int64_t otxn_burden()` (extern.h)
    unsafe fn otxn_burden(&self) -> i64;

    /// C: `int64_t otxn_field(uint32_t write_ptr, uint32_t write_len, uint32_t field_id)` (extern.h)
    unsafe fn otxn_field(&self, write_ptr: u32, write_len: u32, field_id: u32) -> i64;

    /// C: `int64_t otxn_generation()` (extern.h)
    unsafe fn otxn_generation(&self) -> i64;

    /// C: `int64_t otxn_id(uint32_t write_ptr, uint32_t write_len, uint32_t flags)` (extern.h)
    unsafe fn otxn_id(&self, write_ptr: u32, write_len: u32, flags: u32) -> i64;

    /// C: `int64_t otxn_type()` (extern.h)
    unsafe fn otxn_type(&self) -> i64;

    /// C: `int64_t otxn_slot(uint32_t slot_no)` (extern.h)
    unsafe fn otxn_slot(&self, slot_no: u32) -> i64;

    /// C: `int64_t otxn_param(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn otxn_param(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64;

    /// C: `int64_t meta_slot(uint32_t slot_no)` (extern.h)
    unsafe fn meta_slot(&self, slot_no: u32) -> i64;

    /// C: `int64_t xpop_slot(uint32_t slot_no_tx, uint32_t slot_no_meta)` (extern.h)
    unsafe fn xpop_slot(&self, slot_no_tx: u32, slot_no_meta: u32) -> i64;

    /// C: `int64_t prepare(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn prepare(&self, write_ptr: u32, write_len: u32, read_ptr: u32, read_len: u32) -> i64;
}

/// The real `HookHost` implementor: on `target_arch = "wasm32"` this forwards
/// to the genuine `extern "C"` Hook API imports; on every other target it
/// forwards to the same deterministic, non-panicking `NOT_IMPLEMENTED` host
/// stubs `crate::api` provides there. Either way, `Guest` is a zero-sized unit
/// struct with no state of its own — it exists purely as `HookHost`'s
/// concrete implementor.
#[deprecated(
    note = "implement rshooks_core::backend::HostBackend instead; HookHost will be removed in the next breaking release"
)]
pub struct Guest;

#[allow(clippy::missing_safety_doc)]
#[allow(deprecated)]
impl HookHost for Guest {
    /// C: `int32_t _g(uint32_t guard_id, uint32_t maxiter)` (extern.h)
    unsafe fn _g(&self, guard_id: u32, maxiter: u32) -> i32 {
        unsafe { crate::api::_g(guard_id, maxiter) }
    }

    /// C: `int64_t accept(uint32_t read_ptr, uint32_t read_len, int64_t error_code)` (extern.h)
    unsafe fn accept(&self, read_ptr: u32, read_len: u32, error_code: i64) -> i64 {
        unsafe { crate::api::accept(read_ptr, read_len, error_code) }
    }

    /// C: `int64_t rollback(uint32_t read_ptr, uint32_t read_len, int64_t error_code)` (extern.h)
    unsafe fn rollback(&self, read_ptr: u32, read_len: u32, error_code: i64) -> i64 {
        unsafe { crate::api::rollback(read_ptr, read_len, error_code) }
    }

    /// C: `int64_t util_raddr(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn util_raddr(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64 {
        unsafe { crate::api::util_raddr(write_ptr, write_len, read_ptr, read_len) }
    }

    /// C: `int64_t util_accid(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn util_accid(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64 {
        unsafe { crate::api::util_accid(write_ptr, write_len, read_ptr, read_len) }
    }

    /// C: `int64_t util_verify(uint32_t dread_ptr, uint32_t dread_len, uint32_t sread_ptr, uint32_t sread_len, uint32_t kread_ptr, uint32_t kread_len)` (extern.h)
    unsafe fn util_verify(
        &self,
        dread_ptr: u32,
        dread_len: u32,
        sread_ptr: u32,
        sread_len: u32,
        kread_ptr: u32,
        kread_len: u32,
    ) -> i64 {
        unsafe {
            crate::api::util_verify(
                dread_ptr, dread_len, sread_ptr, sread_len, kread_ptr, kread_len,
            )
        }
    }

    /// C: `int64_t util_sha512h(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn util_sha512h(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64 {
        unsafe { crate::api::util_sha512h(write_ptr, write_len, read_ptr, read_len) }
    }

    /// C: `int64_t util_keylet(uint32_t write_ptr, uint32_t write_len, uint32_t keylet_type, uint32_t a, uint32_t b, uint32_t c, uint32_t d, uint32_t e, uint32_t f)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn util_keylet(
        &self,
        write_ptr: u32,
        write_len: u32,
        keylet_type: u32,
        a: u32,
        b: u32,
        c: u32,
        d: u32,
        e: u32,
        f: u32,
    ) -> i64 {
        unsafe { crate::api::util_keylet(write_ptr, write_len, keylet_type, a, b, c, d, e, f) }
    }

    /// C: `int64_t sto_validate(uint32_t tread_ptr, uint32_t tread_len)` (extern.h)
    unsafe fn sto_validate(&self, tread_ptr: u32, tread_len: u32) -> i64 {
        unsafe { crate::api::sto_validate(tread_ptr, tread_len) }
    }

    /// C: `int64_t sto_subfield(uint32_t read_ptr, uint32_t read_len, uint32_t field_id)` (extern.h)
    unsafe fn sto_subfield(&self, read_ptr: u32, read_len: u32, field_id: u32) -> i64 {
        unsafe { crate::api::sto_subfield(read_ptr, read_len, field_id) }
    }

    /// C: `int64_t sto_subarray(uint32_t read_ptr, uint32_t read_len, uint32_t array_id)` (extern.h)
    unsafe fn sto_subarray(&self, read_ptr: u32, read_len: u32, array_id: u32) -> i64 {
        unsafe { crate::api::sto_subarray(read_ptr, read_len, array_id) }
    }

    /// C: `int64_t sto_emplace(uint32_t write_ptr, uint32_t write_len, uint32_t sread_ptr, uint32_t sread_len, uint32_t fread_ptr, uint32_t fread_len, uint32_t field_id)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn sto_emplace(
        &self,
        write_ptr: u32,
        write_len: u32,
        sread_ptr: u32,
        sread_len: u32,
        fread_ptr: u32,
        fread_len: u32,
        field_id: u32,
    ) -> i64 {
        unsafe {
            crate::api::sto_emplace(
                write_ptr, write_len, sread_ptr, sread_len, fread_ptr, fread_len, field_id,
            )
        }
    }

    /// C: `int64_t sto_erase(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len, uint32_t field_id)` (extern.h)
    unsafe fn sto_erase(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
        field_id: u32,
    ) -> i64 {
        unsafe { crate::api::sto_erase(write_ptr, write_len, read_ptr, read_len, field_id) }
    }

    /// C: `int64_t etxn_burden()` (extern.h)
    unsafe fn etxn_burden(&self) -> i64 {
        unsafe { crate::api::etxn_burden() }
    }

    /// C: `int64_t etxn_details(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn etxn_details(&self, write_ptr: u32, write_len: u32) -> i64 {
        unsafe { crate::api::etxn_details(write_ptr, write_len) }
    }

    /// C: `int64_t etxn_fee_base(uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn etxn_fee_base(&self, read_ptr: u32, read_len: u32) -> i64 {
        unsafe { crate::api::etxn_fee_base(read_ptr, read_len) }
    }

    /// C: `int64_t etxn_reserve(uint32_t count)` (extern.h)
    unsafe fn etxn_reserve(&self, count: u32) -> i64 {
        unsafe { crate::api::etxn_reserve(count) }
    }

    /// C: `int64_t etxn_generation()` (extern.h)
    unsafe fn etxn_generation(&self) -> i64 {
        unsafe { crate::api::etxn_generation() }
    }

    /// C: `int64_t etxn_nonce(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn etxn_nonce(&self, write_ptr: u32, write_len: u32) -> i64 {
        unsafe { crate::api::etxn_nonce(write_ptr, write_len) }
    }

    /// C: `int64_t emit(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn emit(&self, write_ptr: u32, write_len: u32, read_ptr: u32, read_len: u32) -> i64 {
        unsafe { crate::api::emit(write_ptr, write_len, read_ptr, read_len) }
    }

    /// C: `int64_t float_set(int32_t exponent, int64_t mantissa)` (extern.h)
    unsafe fn float_set(&self, exponent: i32, mantissa: i64) -> i64 {
        unsafe { crate::api::float_set(exponent, mantissa) }
    }

    /// C: `int64_t float_multiply(int64_t float1, int64_t float2)` (extern.h)
    unsafe fn float_multiply(&self, float1: i64, float2: i64) -> i64 {
        unsafe { crate::api::float_multiply(float1, float2) }
    }

    /// C: `int64_t float_mulratio(int64_t float1, uint32_t round_up, uint32_t numerator, uint32_t denominator)` (extern.h)
    unsafe fn float_mulratio(
        &self,
        float1: i64,
        round_up: u32,
        numerator: u32,
        denominator: u32,
    ) -> i64 {
        unsafe { crate::api::float_mulratio(float1, round_up, numerator, denominator) }
    }

    /// C: `int64_t float_negate(int64_t float1)` (extern.h)
    unsafe fn float_negate(&self, float1: i64) -> i64 {
        unsafe { crate::api::float_negate(float1) }
    }

    /// C: `int64_t float_compare(int64_t float1, int64_t float2, uint32_t mode)` (extern.h)
    unsafe fn float_compare(&self, float1: i64, float2: i64, mode: u32) -> i64 {
        unsafe { crate::api::float_compare(float1, float2, mode) }
    }

    /// C: `int64_t float_sum(int64_t float1, int64_t float2)` (extern.h)
    unsafe fn float_sum(&self, float1: i64, float2: i64) -> i64 {
        unsafe { crate::api::float_sum(float1, float2) }
    }

    /// C: `int64_t float_sto(uint32_t write_ptr, uint32_t write_len, uint32_t cread_ptr, uint32_t cread_len, uint32_t iread_ptr, uint32_t iread_len, int64_t float1, uint32_t field_code)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn float_sto(
        &self,
        write_ptr: u32,
        write_len: u32,
        cread_ptr: u32,
        cread_len: u32,
        iread_ptr: u32,
        iread_len: u32,
        float1: i64,
        field_code: u32,
    ) -> i64 {
        unsafe {
            crate::api::float_sto(
                write_ptr, write_len, cread_ptr, cread_len, iread_ptr, iread_len, float1,
                field_code,
            )
        }
    }

    /// C: `int64_t float_sto_set(uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn float_sto_set(&self, read_ptr: u32, read_len: u32) -> i64 {
        unsafe { crate::api::float_sto_set(read_ptr, read_len) }
    }

    /// C: `int64_t float_invert(int64_t float1)` (extern.h)
    unsafe fn float_invert(&self, float1: i64) -> i64 {
        unsafe { crate::api::float_invert(float1) }
    }

    /// C: `int64_t float_divide(int64_t float1, int64_t float2)` (extern.h)
    unsafe fn float_divide(&self, float1: i64, float2: i64) -> i64 {
        unsafe { crate::api::float_divide(float1, float2) }
    }

    /// C: `int64_t float_one()` (extern.h)
    unsafe fn float_one(&self) -> i64 {
        unsafe { crate::api::float_one() }
    }

    /// C: `int64_t float_mantissa(int64_t float1)` (extern.h)
    unsafe fn float_mantissa(&self, float1: i64) -> i64 {
        unsafe { crate::api::float_mantissa(float1) }
    }

    /// C: `int64_t float_sign(int64_t float1)` (extern.h)
    unsafe fn float_sign(&self, float1: i64) -> i64 {
        unsafe { crate::api::float_sign(float1) }
    }

    /// C: `int64_t float_int(int64_t float1, uint32_t decimal_places, uint32_t abs)` (extern.h)
    unsafe fn float_int(&self, float1: i64, decimal_places: u32, abs: u32) -> i64 {
        unsafe { crate::api::float_int(float1, decimal_places, abs) }
    }

    /// C: `int64_t float_log(int64_t float1)` (extern.h)
    unsafe fn float_log(&self, float1: i64) -> i64 {
        unsafe { crate::api::float_log(float1) }
    }

    /// C: `int64_t float_root(int64_t float1, uint32_t n)` (extern.h)
    unsafe fn float_root(&self, float1: i64, n: u32) -> i64 {
        unsafe { crate::api::float_root(float1, n) }
    }

    /// C: `int64_t fee_base()` (extern.h)
    unsafe fn fee_base(&self) -> i64 {
        unsafe { crate::api::fee_base() }
    }

    /// C: `int64_t ledger_seq()` (extern.h)
    unsafe fn ledger_seq(&self) -> i64 {
        unsafe { crate::api::ledger_seq() }
    }

    /// C: `int64_t ledger_last_time()` (extern.h)
    unsafe fn ledger_last_time(&self) -> i64 {
        unsafe { crate::api::ledger_last_time() }
    }

    /// C: `int64_t ledger_last_hash(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn ledger_last_hash(&self, write_ptr: u32, write_len: u32) -> i64 {
        unsafe { crate::api::ledger_last_hash(write_ptr, write_len) }
    }

    /// C: `int64_t ledger_nonce(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn ledger_nonce(&self, write_ptr: u32, write_len: u32) -> i64 {
        unsafe { crate::api::ledger_nonce(write_ptr, write_len) }
    }

    /// C: `int64_t ledger_keylet(uint32_t write_ptr, uint32_t write_len, uint32_t lread_ptr, uint32_t lread_len, uint32_t hread_ptr, uint32_t hread_len)` (extern.h)
    unsafe fn ledger_keylet(
        &self,
        write_ptr: u32,
        write_len: u32,
        lread_ptr: u32,
        lread_len: u32,
        hread_ptr: u32,
        hread_len: u32,
    ) -> i64 {
        unsafe {
            crate::api::ledger_keylet(
                write_ptr, write_len, lread_ptr, lread_len, hread_ptr, hread_len,
            )
        }
    }

    /// C: `int64_t hook_account(uint32_t write_ptr, uint32_t write_len)` (extern.h)
    unsafe fn hook_account(&self, write_ptr: u32, write_len: u32) -> i64 {
        unsafe { crate::api::hook_account(write_ptr, write_len) }
    }

    /// C: `int64_t hook_hash(uint32_t write_ptr, uint32_t write_len, int32_t hook_no)` (extern.h)
    unsafe fn hook_hash(&self, write_ptr: u32, write_len: u32, hook_no: i32) -> i64 {
        unsafe { crate::api::hook_hash(write_ptr, write_len, hook_no) }
    }

    /// C: `int64_t hook_param_set(uint32_t read_ptr, uint32_t read_len, uint32_t kread_ptr, uint32_t kread_len, uint32_t hread_ptr, uint32_t hread_len)` (extern.h)
    unsafe fn hook_param_set(
        &self,
        read_ptr: u32,
        read_len: u32,
        kread_ptr: u32,
        kread_len: u32,
        hread_ptr: u32,
        hread_len: u32,
    ) -> i64 {
        unsafe {
            crate::api::hook_param_set(
                read_ptr, read_len, kread_ptr, kread_len, hread_ptr, hread_len,
            )
        }
    }

    /// C: `int64_t hook_param(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn hook_param(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64 {
        unsafe { crate::api::hook_param(write_ptr, write_len, read_ptr, read_len) }
    }

    /// C: `int64_t hook_again()` (extern.h)
    unsafe fn hook_again(&self) -> i64 {
        unsafe { crate::api::hook_again() }
    }

    /// C: `int64_t hook_skip(uint32_t read_ptr, uint32_t read_len, uint32_t flags)` (extern.h)
    unsafe fn hook_skip(&self, read_ptr: u32, read_len: u32, flags: u32) -> i64 {
        unsafe { crate::api::hook_skip(read_ptr, read_len, flags) }
    }

    /// C: `int64_t hook_pos()` (extern.h)
    unsafe fn hook_pos(&self) -> i64 {
        unsafe { crate::api::hook_pos() }
    }

    /// C: `int64_t slot(uint32_t write_ptr, uint32_t write_len, uint32_t slot)` (extern.h)
    unsafe fn slot(&self, write_ptr: u32, write_len: u32, slot: u32) -> i64 {
        unsafe { crate::api::slot(write_ptr, write_len, slot) }
    }

    /// C: `int64_t slot_clear(uint32_t slot)` (extern.h)
    unsafe fn slot_clear(&self, slot: u32) -> i64 {
        unsafe { crate::api::slot_clear(slot) }
    }

    /// C: `int64_t slot_count(uint32_t slot)` (extern.h)
    unsafe fn slot_count(&self, slot: u32) -> i64 {
        unsafe { crate::api::slot_count(slot) }
    }

    /// C: `int64_t slot_set(uint32_t read_ptr, uint32_t read_len, uint32_t slot)` (extern.h)
    unsafe fn slot_set(&self, read_ptr: u32, read_len: u32, slot: u32) -> i64 {
        unsafe { crate::api::slot_set(read_ptr, read_len, slot) }
    }

    /// C: `int64_t slot_size(uint32_t slot)` (extern.h)
    unsafe fn slot_size(&self, slot: u32) -> i64 {
        unsafe { crate::api::slot_size(slot) }
    }

    /// C: `int64_t slot_subarray(uint32_t parent_slot, uint32_t array_id, uint32_t new_slot)` (extern.h)
    unsafe fn slot_subarray(&self, parent_slot: u32, array_id: u32, new_slot: u32) -> i64 {
        unsafe { crate::api::slot_subarray(parent_slot, array_id, new_slot) }
    }

    /// C: `int64_t slot_subfield(uint32_t parent_slot, uint32_t field_id, uint32_t new_slot)` (extern.h)
    unsafe fn slot_subfield(&self, parent_slot: u32, field_id: u32, new_slot: u32) -> i64 {
        unsafe { crate::api::slot_subfield(parent_slot, field_id, new_slot) }
    }

    /// C: `int64_t slot_type(uint32_t slot_no, uint32_t flags)` (extern.h)
    unsafe fn slot_type(&self, slot_no: u32, flags: u32) -> i64 {
        unsafe { crate::api::slot_type(slot_no, flags) }
    }

    /// C: `int64_t slot_float(uint32_t slot_no)` (extern.h)
    unsafe fn slot_float(&self, slot_no: u32) -> i64 {
        unsafe { crate::api::slot_float(slot_no) }
    }

    /// C: `int64_t state_set(uint32_t read_ptr, uint32_t read_len, uint32_t kread_ptr, uint32_t kread_len)` (extern.h)
    unsafe fn state_set(
        &self,
        read_ptr: u32,
        read_len: u32,
        kread_ptr: u32,
        kread_len: u32,
    ) -> i64 {
        unsafe { crate::api::state_set(read_ptr, read_len, kread_ptr, kread_len) }
    }

    /// C: `int64_t state_foreign_set(uint32_t read_ptr, uint32_t read_len, uint32_t kread_ptr, uint32_t kread_len, uint32_t nread_ptr, uint32_t nread_len, uint32_t aread_ptr, uint32_t aread_len)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn state_foreign_set(
        &self,
        read_ptr: u32,
        read_len: u32,
        kread_ptr: u32,
        kread_len: u32,
        nread_ptr: u32,
        nread_len: u32,
        aread_ptr: u32,
        aread_len: u32,
    ) -> i64 {
        unsafe {
            crate::api::state_foreign_set(
                read_ptr, read_len, kread_ptr, kread_len, nread_ptr, nread_len, aread_ptr,
                aread_len,
            )
        }
    }

    /// C: `int64_t state(uint32_t write_ptr, uint32_t write_len, uint32_t kread_ptr, uint32_t kread_len)` (extern.h)
    unsafe fn state(&self, write_ptr: u32, write_len: u32, kread_ptr: u32, kread_len: u32) -> i64 {
        unsafe { crate::api::state(write_ptr, write_len, kread_ptr, kread_len) }
    }

    /// C: `int64_t state_foreign(uint32_t write_ptr, uint32_t write_len, uint32_t kread_ptr, uint32_t kread_len, uint32_t nread_ptr, uint32_t nread_len, uint32_t aread_ptr, uint32_t aread_len)` (extern.h)
    #[allow(clippy::too_many_arguments)]
    unsafe fn state_foreign(
        &self,
        write_ptr: u32,
        write_len: u32,
        kread_ptr: u32,
        kread_len: u32,
        nread_ptr: u32,
        nread_len: u32,
        aread_ptr: u32,
        aread_len: u32,
    ) -> i64 {
        unsafe {
            crate::api::state_foreign(
                write_ptr, write_len, kread_ptr, kread_len, nread_ptr, nread_len, aread_ptr,
                aread_len,
            )
        }
    }

    /// C: `int64_t trace(uint32_t mread_ptr, uint32_t mread_len, uint32_t dread_ptr, uint32_t dread_len, uint32_t as_hex)` (extern.h)
    unsafe fn trace(
        &self,
        mread_ptr: u32,
        mread_len: u32,
        dread_ptr: u32,
        dread_len: u32,
        as_hex: u32,
    ) -> i64 {
        unsafe { crate::api::trace(mread_ptr, mread_len, dread_ptr, dread_len, as_hex) }
    }

    /// C: `int64_t trace_num(uint32_t read_ptr, uint32_t read_len, int64_t number)` (extern.h)
    unsafe fn trace_num(&self, read_ptr: u32, read_len: u32, number: i64) -> i64 {
        unsafe { crate::api::trace_num(read_ptr, read_len, number) }
    }

    /// C: `int64_t trace_float(uint32_t read_ptr, uint32_t read_len, int64_t float1)` (extern.h)
    unsafe fn trace_float(&self, read_ptr: u32, read_len: u32, float1: i64) -> i64 {
        unsafe { crate::api::trace_float(read_ptr, read_len, float1) }
    }

    /// C: `int64_t otxn_burden()` (extern.h)
    unsafe fn otxn_burden(&self) -> i64 {
        unsafe { crate::api::otxn_burden() }
    }

    /// C: `int64_t otxn_field(uint32_t write_ptr, uint32_t write_len, uint32_t field_id)` (extern.h)
    unsafe fn otxn_field(&self, write_ptr: u32, write_len: u32, field_id: u32) -> i64 {
        unsafe { crate::api::otxn_field(write_ptr, write_len, field_id) }
    }

    /// C: `int64_t otxn_generation()` (extern.h)
    unsafe fn otxn_generation(&self) -> i64 {
        unsafe { crate::api::otxn_generation() }
    }

    /// C: `int64_t otxn_id(uint32_t write_ptr, uint32_t write_len, uint32_t flags)` (extern.h)
    unsafe fn otxn_id(&self, write_ptr: u32, write_len: u32, flags: u32) -> i64 {
        unsafe { crate::api::otxn_id(write_ptr, write_len, flags) }
    }

    /// C: `int64_t otxn_type()` (extern.h)
    unsafe fn otxn_type(&self) -> i64 {
        unsafe { crate::api::otxn_type() }
    }

    /// C: `int64_t otxn_slot(uint32_t slot_no)` (extern.h)
    unsafe fn otxn_slot(&self, slot_no: u32) -> i64 {
        unsafe { crate::api::otxn_slot(slot_no) }
    }

    /// C: `int64_t otxn_param(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn otxn_param(
        &self,
        write_ptr: u32,
        write_len: u32,
        read_ptr: u32,
        read_len: u32,
    ) -> i64 {
        unsafe { crate::api::otxn_param(write_ptr, write_len, read_ptr, read_len) }
    }

    /// C: `int64_t meta_slot(uint32_t slot_no)` (extern.h)
    unsafe fn meta_slot(&self, slot_no: u32) -> i64 {
        unsafe { crate::api::meta_slot(slot_no) }
    }

    /// C: `int64_t xpop_slot(uint32_t slot_no_tx, uint32_t slot_no_meta)` (extern.h)
    unsafe fn xpop_slot(&self, slot_no_tx: u32, slot_no_meta: u32) -> i64 {
        unsafe { crate::api::xpop_slot(slot_no_tx, slot_no_meta) }
    }

    /// C: `int64_t prepare(uint32_t write_ptr, uint32_t write_len, uint32_t read_ptr, uint32_t read_len)` (extern.h)
    unsafe fn prepare(&self, write_ptr: u32, write_len: u32, read_ptr: u32, read_len: u32) -> i64 {
        unsafe { crate::api::prepare(write_ptr, write_len, read_ptr, read_len) }
    }
}
