// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-protocol/ledger_entries.macro — DO NOT EDIT BY HAND.
//! Ledger entry type (`ltXXX`) codes.
//!
//! The values [`sfLedgerEntryType`](crate::sfcodes::sfLedgerEntryType)
//! carries, and what
//! [`slot_type`](crate::api::slot_type)-style checks compare against.
//!
//! Upstream: `Xahau/xahaud`, branch `release`,
//! `include/xrpl/protocol/detail/ledger_entries.macro`, vendored at
//! `crates/rshooks-core/vendor/xahaud-protocol/ledger_entries.macro`.
//!
//! # Rendering
//!
//! Upstream writes most of these values as 4-digit hex and three of them
//! (`ltHOOK_DEFINITION`, `ltEMITTED_TXN`, `ltHOOK`) as character literals
//! (`'D'`, `'E'`, `'H'`). They are all one number on the wire, so they are
//! rendered uniformly as 4-digit hex here — `ltHOOK` is `0x0048`, the code
//! of `'H'`.

/// C: `ltNFTOKEN_OFFER` (ledger_entries.macro) — the `NFTokenOffer` ledger entry.
pub const ltNFTOKEN_OFFER: u16 = 0x0037;
/// C: `ltCRON` (ledger_entries.macro) — the `Cron` ledger entry.
pub const ltCRON: u16 = 0x0041;
/// C: `ltCHECK` (ledger_entries.macro) — the `Check` ledger entry.
pub const ltCHECK: u16 = 0x0043;
/// C: `ltHOOK_DEFINITION` (ledger_entries.macro) — the `HookDefinition` ledger entry.
pub const ltHOOK_DEFINITION: u16 = 0x0044;
/// C: `ltEMITTED_TXN` (ledger_entries.macro) — the `EmittedTxn` ledger entry.
pub const ltEMITTED_TXN: u16 = 0x0045;
/// C: `ltHOOK` (ledger_entries.macro) — the `Hook` ledger entry.
pub const ltHOOK: u16 = 0x0048;
/// C: `ltIMPORT_VLSEQ` (ledger_entries.macro) — the `ImportVLSequence` ledger entry.
pub const ltIMPORT_VLSEQ: u16 = 0x0049;
/// C: `ltNEGATIVE_UNL` (ledger_entries.macro) — the `NegativeUNL` ledger entry.
pub const ltNEGATIVE_UNL: u16 = 0x004e;
/// C: `ltNFTOKEN_PAGE` (ledger_entries.macro) — the `NFTokenPage` ledger entry.
pub const ltNFTOKEN_PAGE: u16 = 0x0050;
/// C: `ltUNL_REPORT` (ledger_entries.macro) — the `UNLReport` ledger entry.
pub const ltUNL_REPORT: u16 = 0x0052;
/// C: `ltSIGNER_LIST` (ledger_entries.macro) — the `SignerList` ledger entry.
pub const ltSIGNER_LIST: u16 = 0x0053;
/// C: `ltTICKET` (ledger_entries.macro) — the `Ticket` ledger entry.
pub const ltTICKET: u16 = 0x0054;
/// C: `ltURI_TOKEN` (ledger_entries.macro) — the `URIToken` ledger entry.
pub const ltURI_TOKEN: u16 = 0x0055;
/// C: `ltACCOUNT_ROOT` (ledger_entries.macro) — the `AccountRoot` ledger entry.
pub const ltACCOUNT_ROOT: u16 = 0x0061;
/// C: `ltDIR_NODE` (ledger_entries.macro) — the `DirectoryNode` ledger entry.
pub const ltDIR_NODE: u16 = 0x0064;
/// C: `ltAMENDMENTS` (ledger_entries.macro) — the `Amendments` ledger entry.
pub const ltAMENDMENTS: u16 = 0x0066;
/// C: `ltLEDGER_HASHES` (ledger_entries.macro) — the `LedgerHashes` ledger entry.
pub const ltLEDGER_HASHES: u16 = 0x0068;
/// C: `ltBRIDGE` (ledger_entries.macro) — the `Bridge` ledger entry.
pub const ltBRIDGE: u16 = 0x0069;
/// C: `ltOFFER` (ledger_entries.macro) — the `Offer` ledger entry.
pub const ltOFFER: u16 = 0x006f;
/// C: `ltDEPOSIT_PREAUTH` (ledger_entries.macro) — the `DepositPreauth` ledger entry.
pub const ltDEPOSIT_PREAUTH: u16 = 0x0070;
/// C: `ltXCHAIN_OWNED_CLAIM_ID` (ledger_entries.macro) — the `XChainOwnedClaimID` ledger entry.
pub const ltXCHAIN_OWNED_CLAIM_ID: u16 = 0x0071;
/// C: `ltRIPPLE_STATE` (ledger_entries.macro) — the `RippleState` ledger entry.
pub const ltRIPPLE_STATE: u16 = 0x0072;
/// C: `ltFEE_SETTINGS` (ledger_entries.macro) — the `FeeSettings` ledger entry.
pub const ltFEE_SETTINGS: u16 = 0x0073;
/// C: `ltXCHAIN_OWNED_CREATE_ACCOUNT_CLAIM_ID` (ledger_entries.macro) — the `XChainOwnedCreateAccountClaimID` ledger entry.
pub const ltXCHAIN_OWNED_CREATE_ACCOUNT_CLAIM_ID: u16 = 0x0074;
/// C: `ltESCROW` (ledger_entries.macro) — the `Escrow` ledger entry.
pub const ltESCROW: u16 = 0x0075;
/// C: `ltHOOK_STATE` (ledger_entries.macro) — the `HookState` ledger entry.
pub const ltHOOK_STATE: u16 = 0x0076;
/// C: `ltPAYCHAN` (ledger_entries.macro) — the `PayChannel` ledger entry.
pub const ltPAYCHAN: u16 = 0x0078;
/// C: `ltAMM` (ledger_entries.macro) — the `AMM` ledger entry.
pub const ltAMM: u16 = 0x0079;
/// C: `ltORACLE` (ledger_entries.macro) — the `Oracle` ledger entry.
pub const ltORACLE: u16 = 0x0080;
/// C: `ltMPTOKEN_ISSUANCE` (ledger_entries.macro) — the `MPTokenIssuance` ledger entry.
pub const ltMPTOKEN_ISSUANCE: u16 = 0x007e;
/// C: `ltMPTOKEN` (ledger_entries.macro) — the `MPToken` ledger entry.
pub const ltMPTOKEN: u16 = 0x007f;
/// C: `ltCREDENTIAL` (ledger_entries.macro) — the `Credential` ledger entry.
pub const ltCREDENTIAL: u16 = 0x0081;
/// C: `ltPERMISSIONED_DOMAIN` (ledger_entries.macro) — the `PermissionedDomain` ledger entry.
pub const ltPERMISSIONED_DOMAIN: u16 = 0x0082;
/// C: `ltDID` (ledger_entries.macro) — the `DID` ledger entry.
pub const ltDID: u16 = 0x008d;
