// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-hook/sfcodes.h — DO NOT EDIT BY HAND.
//! Serialized field (`sfXxx`) codes.
//!
//! Upstream: `Xahau/xahaud`, branch `release`, `hook/sfcodes.h`, vendored at
//! `crates/rshooks-core/vendor/xahaud-hook/sfcodes.h`.
//!
//! Each code packs a type code and a field index: `(type << 16) + index`,
//! mirrored verbatim from the header.

/// C: `sfCloseResolution` (sfcodes.h)
pub const sfCloseResolution: u32 = (16 << 16) + 1;
/// C: `sfMethod` (sfcodes.h)
pub const sfMethod: u32 = (16 << 16) + 2;
/// C: `sfTransactionResult` (sfcodes.h)
pub const sfTransactionResult: u32 = (16 << 16) + 3;
/// C: `sfScale` (sfcodes.h)
pub const sfScale: u32 = (16 << 16) + 4;
/// C: `sfAssetScale` (sfcodes.h)
pub const sfAssetScale: u32 = (16 << 16) + 5;
/// C: `sfTickSize` (sfcodes.h)
pub const sfTickSize: u32 = (16 << 16) + 16;
/// C: `sfUNLModifyDisabling` (sfcodes.h)
pub const sfUNLModifyDisabling: u32 = (16 << 16) + 17;
/// C: `sfHookResult` (sfcodes.h)
pub const sfHookResult: u32 = (16 << 16) + 18;
/// C: `sfWasLockingChainSend` (sfcodes.h)
pub const sfWasLockingChainSend: u32 = (16 << 16) + 19;
/// C: `sfLedgerEntryType` (sfcodes.h)
pub const sfLedgerEntryType: u32 = (1 << 16) + 1;
/// C: `sfTransactionType` (sfcodes.h)
pub const sfTransactionType: u32 = (1 << 16) + 2;
/// C: `sfSignerWeight` (sfcodes.h)
pub const sfSignerWeight: u32 = (1 << 16) + 3;
/// C: `sfTransferFee` (sfcodes.h)
pub const sfTransferFee: u32 = (1 << 16) + 4;
/// C: `sfTradingFee` (sfcodes.h)
pub const sfTradingFee: u32 = (1 << 16) + 5;
/// C: `sfDiscountedFee` (sfcodes.h)
pub const sfDiscountedFee: u32 = (1 << 16) + 6;
/// C: `sfVersion` (sfcodes.h)
pub const sfVersion: u32 = (1 << 16) + 16;
/// C: `sfHookStateChangeCount` (sfcodes.h)
pub const sfHookStateChangeCount: u32 = (1 << 16) + 17;
/// C: `sfHookEmitCount` (sfcodes.h)
pub const sfHookEmitCount: u32 = (1 << 16) + 18;
/// C: `sfHookExecutionIndex` (sfcodes.h)
pub const sfHookExecutionIndex: u32 = (1 << 16) + 19;
/// C: `sfHookApiVersion` (sfcodes.h)
pub const sfHookApiVersion: u32 = (1 << 16) + 20;
/// C: `sfHookStateScale` (sfcodes.h)
pub const sfHookStateScale: u32 = (1 << 16) + 21;
/// C: `sfLedgerFixType` (sfcodes.h)
pub const sfLedgerFixType: u32 = (1 << 16) + 22;
/// C: `sfNetworkID` (sfcodes.h)
pub const sfNetworkID: u32 = (2 << 16) + 1;
/// C: `sfFlags` (sfcodes.h)
pub const sfFlags: u32 = (2 << 16) + 2;
/// C: `sfSourceTag` (sfcodes.h)
pub const sfSourceTag: u32 = (2 << 16) + 3;
/// C: `sfSequence` (sfcodes.h)
pub const sfSequence: u32 = (2 << 16) + 4;
/// C: `sfPreviousTxnLgrSeq` (sfcodes.h)
pub const sfPreviousTxnLgrSeq: u32 = (2 << 16) + 5;
/// C: `sfLedgerSequence` (sfcodes.h)
pub const sfLedgerSequence: u32 = (2 << 16) + 6;
/// C: `sfCloseTime` (sfcodes.h)
pub const sfCloseTime: u32 = (2 << 16) + 7;
/// C: `sfParentCloseTime` (sfcodes.h)
pub const sfParentCloseTime: u32 = (2 << 16) + 8;
/// C: `sfSigningTime` (sfcodes.h)
pub const sfSigningTime: u32 = (2 << 16) + 9;
/// C: `sfExpiration` (sfcodes.h)
pub const sfExpiration: u32 = (2 << 16) + 10;
/// C: `sfTransferRate` (sfcodes.h)
pub const sfTransferRate: u32 = (2 << 16) + 11;
/// C: `sfWalletSize` (sfcodes.h)
pub const sfWalletSize: u32 = (2 << 16) + 12;
/// C: `sfOwnerCount` (sfcodes.h)
pub const sfOwnerCount: u32 = (2 << 16) + 13;
/// C: `sfDestinationTag` (sfcodes.h)
pub const sfDestinationTag: u32 = (2 << 16) + 14;
/// C: `sfLastUpdateTime` (sfcodes.h)
pub const sfLastUpdateTime: u32 = (2 << 16) + 15;
/// C: `sfHighQualityIn` (sfcodes.h)
pub const sfHighQualityIn: u32 = (2 << 16) + 16;
/// C: `sfHighQualityOut` (sfcodes.h)
pub const sfHighQualityOut: u32 = (2 << 16) + 17;
/// C: `sfLowQualityIn` (sfcodes.h)
pub const sfLowQualityIn: u32 = (2 << 16) + 18;
/// C: `sfLowQualityOut` (sfcodes.h)
pub const sfLowQualityOut: u32 = (2 << 16) + 19;
/// C: `sfQualityIn` (sfcodes.h)
pub const sfQualityIn: u32 = (2 << 16) + 20;
/// C: `sfQualityOut` (sfcodes.h)
pub const sfQualityOut: u32 = (2 << 16) + 21;
/// C: `sfStampEscrow` (sfcodes.h)
pub const sfStampEscrow: u32 = (2 << 16) + 22;
/// C: `sfBondAmount` (sfcodes.h)
pub const sfBondAmount: u32 = (2 << 16) + 23;
/// C: `sfLoadFee` (sfcodes.h)
pub const sfLoadFee: u32 = (2 << 16) + 24;
/// C: `sfOfferSequence` (sfcodes.h)
pub const sfOfferSequence: u32 = (2 << 16) + 25;
/// C: `sfFirstLedgerSequence` (sfcodes.h)
pub const sfFirstLedgerSequence: u32 = (2 << 16) + 26;
/// C: `sfLastLedgerSequence` (sfcodes.h)
pub const sfLastLedgerSequence: u32 = (2 << 16) + 27;
/// C: `sfTransactionIndex` (sfcodes.h)
pub const sfTransactionIndex: u32 = (2 << 16) + 28;
/// C: `sfOperationLimit` (sfcodes.h)
pub const sfOperationLimit: u32 = (2 << 16) + 29;
/// C: `sfReferenceFeeUnits` (sfcodes.h)
pub const sfReferenceFeeUnits: u32 = (2 << 16) + 30;
/// C: `sfReserveBase` (sfcodes.h)
pub const sfReserveBase: u32 = (2 << 16) + 31;
/// C: `sfReserveIncrement` (sfcodes.h)
pub const sfReserveIncrement: u32 = (2 << 16) + 32;
/// C: `sfSetFlag` (sfcodes.h)
pub const sfSetFlag: u32 = (2 << 16) + 33;
/// C: `sfClearFlag` (sfcodes.h)
pub const sfClearFlag: u32 = (2 << 16) + 34;
/// C: `sfSignerQuorum` (sfcodes.h)
pub const sfSignerQuorum: u32 = (2 << 16) + 35;
/// C: `sfCancelAfter` (sfcodes.h)
pub const sfCancelAfter: u32 = (2 << 16) + 36;
/// C: `sfFinishAfter` (sfcodes.h)
pub const sfFinishAfter: u32 = (2 << 16) + 37;
/// C: `sfSignerListID` (sfcodes.h)
pub const sfSignerListID: u32 = (2 << 16) + 38;
/// C: `sfSettleDelay` (sfcodes.h)
pub const sfSettleDelay: u32 = (2 << 16) + 39;
/// C: `sfTicketCount` (sfcodes.h)
pub const sfTicketCount: u32 = (2 << 16) + 40;
/// C: `sfTicketSequence` (sfcodes.h)
pub const sfTicketSequence: u32 = (2 << 16) + 41;
/// C: `sfNFTokenTaxon` (sfcodes.h)
pub const sfNFTokenTaxon: u32 = (2 << 16) + 42;
/// C: `sfMintedNFTokens` (sfcodes.h)
pub const sfMintedNFTokens: u32 = (2 << 16) + 43;
/// C: `sfBurnedNFTokens` (sfcodes.h)
pub const sfBurnedNFTokens: u32 = (2 << 16) + 44;
/// C: `sfHookStateCount` (sfcodes.h)
pub const sfHookStateCount: u32 = (2 << 16) + 45;
/// C: `sfEmitGeneration` (sfcodes.h)
pub const sfEmitGeneration: u32 = (2 << 16) + 46;
/// C: `sfVoteWeight` (sfcodes.h)
pub const sfVoteWeight: u32 = (2 << 16) + 48;
/// C: `sfLockCount` (sfcodes.h)
pub const sfLockCount: u32 = (2 << 16) + 49;
/// C: `sfFirstNFTokenSequence` (sfcodes.h)
pub const sfFirstNFTokenSequence: u32 = (2 << 16) + 50;
/// C: `sfOracleDocumentID` (sfcodes.h)
pub const sfOracleDocumentID: u32 = (2 << 16) + 51;
/// C: `sfStartTime` (sfcodes.h)
pub const sfStartTime: u32 = (2 << 16) + 93;
/// C: `sfRepeatCount` (sfcodes.h)
pub const sfRepeatCount: u32 = (2 << 16) + 94;
/// C: `sfDelaySeconds` (sfcodes.h)
pub const sfDelaySeconds: u32 = (2 << 16) + 95;
/// C: `sfXahauActivationLgrSeq` (sfcodes.h)
pub const sfXahauActivationLgrSeq: u32 = (2 << 16) + 96;
/// C: `sfImportSequence` (sfcodes.h)
pub const sfImportSequence: u32 = (2 << 16) + 97;
/// C: `sfRewardTime` (sfcodes.h)
pub const sfRewardTime: u32 = (2 << 16) + 98;
/// C: `sfRewardLgrFirst` (sfcodes.h)
pub const sfRewardLgrFirst: u32 = (2 << 16) + 99;
/// C: `sfRewardLgrLast` (sfcodes.h)
pub const sfRewardLgrLast: u32 = (2 << 16) + 100;
/// C: `sfIndexNext` (sfcodes.h)
pub const sfIndexNext: u32 = (3 << 16) + 1;
/// C: `sfIndexPrevious` (sfcodes.h)
pub const sfIndexPrevious: u32 = (3 << 16) + 2;
/// C: `sfBookNode` (sfcodes.h)
pub const sfBookNode: u32 = (3 << 16) + 3;
/// C: `sfOwnerNode` (sfcodes.h)
pub const sfOwnerNode: u32 = (3 << 16) + 4;
/// C: `sfBaseFee` (sfcodes.h)
pub const sfBaseFee: u32 = (3 << 16) + 5;
/// C: `sfExchangeRate` (sfcodes.h)
pub const sfExchangeRate: u32 = (3 << 16) + 6;
/// C: `sfLowNode` (sfcodes.h)
pub const sfLowNode: u32 = (3 << 16) + 7;
/// C: `sfHighNode` (sfcodes.h)
pub const sfHighNode: u32 = (3 << 16) + 8;
/// C: `sfDestinationNode` (sfcodes.h)
pub const sfDestinationNode: u32 = (3 << 16) + 9;
/// C: `sfCookie` (sfcodes.h)
pub const sfCookie: u32 = (3 << 16) + 10;
/// C: `sfServerVersion` (sfcodes.h)
pub const sfServerVersion: u32 = (3 << 16) + 11;
/// C: `sfNFTokenOfferNode` (sfcodes.h)
pub const sfNFTokenOfferNode: u32 = (3 << 16) + 12;
/// C: `sfEmitBurden` (sfcodes.h)
pub const sfEmitBurden: u32 = (3 << 16) + 13;
/// C: `sfHookInstructionCount` (sfcodes.h)
pub const sfHookInstructionCount: u32 = (3 << 16) + 17;
/// C: `sfHookReturnCode` (sfcodes.h)
pub const sfHookReturnCode: u32 = (3 << 16) + 18;
/// C: `sfReferenceCount` (sfcodes.h)
pub const sfReferenceCount: u32 = (3 << 16) + 19;
/// C: `sfXChainClaimID` (sfcodes.h)
pub const sfXChainClaimID: u32 = (3 << 16) + 20;
/// C: `sfXChainAccountCreateCount` (sfcodes.h)
pub const sfXChainAccountCreateCount: u32 = (3 << 16) + 21;
/// C: `sfXChainAccountClaimCount` (sfcodes.h)
pub const sfXChainAccountClaimCount: u32 = (3 << 16) + 22;
/// C: `sfAssetPrice` (sfcodes.h)
pub const sfAssetPrice: u32 = (3 << 16) + 23;
/// C: `sfMaximumAmount` (sfcodes.h)
pub const sfMaximumAmount: u32 = (3 << 16) + 24;
/// C: `sfOutstandingAmount` (sfcodes.h)
pub const sfOutstandingAmount: u32 = (3 << 16) + 25;
/// C: `sfMPTAmount` (sfcodes.h)
pub const sfMPTAmount: u32 = (3 << 16) + 26;
/// C: `sfIssuerNode` (sfcodes.h)
pub const sfIssuerNode: u32 = (3 << 16) + 27;
/// C: `sfSubjectNode` (sfcodes.h)
pub const sfSubjectNode: u32 = (3 << 16) + 28;
/// C: `sfTouchCount` (sfcodes.h)
pub const sfTouchCount: u32 = (3 << 16) + 97;
/// C: `sfAccountIndex` (sfcodes.h)
pub const sfAccountIndex: u32 = (3 << 16) + 98;
/// C: `sfAccountCount` (sfcodes.h)
pub const sfAccountCount: u32 = (3 << 16) + 99;
/// C: `sfRewardAccumulator` (sfcodes.h)
pub const sfRewardAccumulator: u32 = (3 << 16) + 100;
/// C: `sfEmailHash` (sfcodes.h)
pub const sfEmailHash: u32 = (4 << 16) + 1;
/// C: `sfTakerPaysCurrency` (sfcodes.h)
pub const sfTakerPaysCurrency: u32 = (17 << 16) + 1;
/// C: `sfTakerPaysIssuer` (sfcodes.h)
pub const sfTakerPaysIssuer: u32 = (17 << 16) + 2;
/// C: `sfTakerGetsCurrency` (sfcodes.h)
pub const sfTakerGetsCurrency: u32 = (17 << 16) + 3;
/// C: `sfTakerGetsIssuer` (sfcodes.h)
pub const sfTakerGetsIssuer: u32 = (17 << 16) + 4;
/// C: `sfMPTokenIssuanceID` (sfcodes.h)
pub const sfMPTokenIssuanceID: u32 = (21 << 16) + 1;
/// C: `sfLedgerHash` (sfcodes.h)
pub const sfLedgerHash: u32 = (5 << 16) + 1;
/// C: `sfParentHash` (sfcodes.h)
pub const sfParentHash: u32 = (5 << 16) + 2;
/// C: `sfTransactionHash` (sfcodes.h)
pub const sfTransactionHash: u32 = (5 << 16) + 3;
/// C: `sfAccountHash` (sfcodes.h)
pub const sfAccountHash: u32 = (5 << 16) + 4;
/// C: `sfPreviousTxnID` (sfcodes.h)
pub const sfPreviousTxnID: u32 = (5 << 16) + 5;
/// C: `sfLedgerIndex` (sfcodes.h)
pub const sfLedgerIndex: u32 = (5 << 16) + 6;
/// C: `sfWalletLocator` (sfcodes.h)
pub const sfWalletLocator: u32 = (5 << 16) + 7;
/// C: `sfRootIndex` (sfcodes.h)
pub const sfRootIndex: u32 = (5 << 16) + 8;
/// C: `sfAccountTxnID` (sfcodes.h)
pub const sfAccountTxnID: u32 = (5 << 16) + 9;
/// C: `sfNFTokenID` (sfcodes.h)
pub const sfNFTokenID: u32 = (5 << 16) + 10;
/// C: `sfEmitParentTxnID` (sfcodes.h)
pub const sfEmitParentTxnID: u32 = (5 << 16) + 11;
/// C: `sfEmitNonce` (sfcodes.h)
pub const sfEmitNonce: u32 = (5 << 16) + 12;
/// C: `sfEmitHookHash` (sfcodes.h)
pub const sfEmitHookHash: u32 = (5 << 16) + 13;
/// C: `sfObjectID` (sfcodes.h)
pub const sfObjectID: u32 = (5 << 16) + 14;
/// C: `sfAMMID` (sfcodes.h)
pub const sfAMMID: u32 = (5 << 16) + 15;
/// C: `sfBookDirectory` (sfcodes.h)
pub const sfBookDirectory: u32 = (5 << 16) + 16;
/// C: `sfInvoiceID` (sfcodes.h)
pub const sfInvoiceID: u32 = (5 << 16) + 17;
/// C: `sfNickname` (sfcodes.h)
pub const sfNickname: u32 = (5 << 16) + 18;
/// C: `sfAmendment` (sfcodes.h)
pub const sfAmendment: u32 = (5 << 16) + 19;
/// C: `sfHookOn` (sfcodes.h)
pub const sfHookOn: u32 = (5 << 16) + 20;
/// C: `sfDigest` (sfcodes.h)
pub const sfDigest: u32 = (5 << 16) + 21;
/// C: `sfChannel` (sfcodes.h)
pub const sfChannel: u32 = (5 << 16) + 22;
/// C: `sfConsensusHash` (sfcodes.h)
pub const sfConsensusHash: u32 = (5 << 16) + 23;
/// C: `sfCheckID` (sfcodes.h)
pub const sfCheckID: u32 = (5 << 16) + 24;
/// C: `sfValidatedHash` (sfcodes.h)
pub const sfValidatedHash: u32 = (5 << 16) + 25;
/// C: `sfPreviousPageMin` (sfcodes.h)
pub const sfPreviousPageMin: u32 = (5 << 16) + 26;
/// C: `sfNextPageMin` (sfcodes.h)
pub const sfNextPageMin: u32 = (5 << 16) + 27;
/// C: `sfNFTokenBuyOffer` (sfcodes.h)
pub const sfNFTokenBuyOffer: u32 = (5 << 16) + 28;
/// C: `sfNFTokenSellOffer` (sfcodes.h)
pub const sfNFTokenSellOffer: u32 = (5 << 16) + 29;
/// C: `sfHookStateKey` (sfcodes.h)
pub const sfHookStateKey: u32 = (5 << 16) + 30;
/// C: `sfHookHash` (sfcodes.h)
pub const sfHookHash: u32 = (5 << 16) + 31;
/// C: `sfHookNamespace` (sfcodes.h)
pub const sfHookNamespace: u32 = (5 << 16) + 32;
/// C: `sfHookSetTxnID` (sfcodes.h)
pub const sfHookSetTxnID: u32 = (5 << 16) + 33;
/// C: `sfOfferID` (sfcodes.h)
pub const sfOfferID: u32 = (5 << 16) + 34;
/// C: `sfEscrowID` (sfcodes.h)
pub const sfEscrowID: u32 = (5 << 16) + 35;
/// C: `sfURITokenID` (sfcodes.h)
pub const sfURITokenID: u32 = (5 << 16) + 36;
/// C: `sfDomainID` (sfcodes.h)
pub const sfDomainID: u32 = (5 << 16) + 37;
/// C: `sfHookOnOutgoing` (sfcodes.h)
pub const sfHookOnOutgoing: u32 = (5 << 16) + 93;
/// C: `sfHookOnIncoming` (sfcodes.h)
pub const sfHookOnIncoming: u32 = (5 << 16) + 94;
/// C: `sfCron` (sfcodes.h)
pub const sfCron: u32 = (5 << 16) + 95;
/// C: `sfHookCanEmit` (sfcodes.h)
pub const sfHookCanEmit: u32 = (5 << 16) + 96;
/// C: `sfEmittedTxnID` (sfcodes.h)
pub const sfEmittedTxnID: u32 = (5 << 16) + 97;
/// C: `sfGovernanceMarks` (sfcodes.h)
pub const sfGovernanceMarks: u32 = (5 << 16) + 98;
/// C: `sfGovernanceFlags` (sfcodes.h)
pub const sfGovernanceFlags: u32 = (5 << 16) + 99;
/// C: `sfNumber` (sfcodes.h)
pub const sfNumber: u32 = (9 << 16) + 1;
/// C: `sfAmount` (sfcodes.h)
pub const sfAmount: u32 = (6 << 16) + 1;
/// C: `sfBalance` (sfcodes.h)
pub const sfBalance: u32 = (6 << 16) + 2;
/// C: `sfLimitAmount` (sfcodes.h)
pub const sfLimitAmount: u32 = (6 << 16) + 3;
/// C: `sfTakerPays` (sfcodes.h)
pub const sfTakerPays: u32 = (6 << 16) + 4;
/// C: `sfTakerGets` (sfcodes.h)
pub const sfTakerGets: u32 = (6 << 16) + 5;
/// C: `sfLowLimit` (sfcodes.h)
pub const sfLowLimit: u32 = (6 << 16) + 6;
/// C: `sfHighLimit` (sfcodes.h)
pub const sfHighLimit: u32 = (6 << 16) + 7;
/// C: `sfFee` (sfcodes.h)
pub const sfFee: u32 = (6 << 16) + 8;
/// C: `sfSendMax` (sfcodes.h)
pub const sfSendMax: u32 = (6 << 16) + 9;
/// C: `sfDeliverMin` (sfcodes.h)
pub const sfDeliverMin: u32 = (6 << 16) + 10;
/// C: `sfAmount2` (sfcodes.h)
pub const sfAmount2: u32 = (6 << 16) + 11;
/// C: `sfBidMin` (sfcodes.h)
pub const sfBidMin: u32 = (6 << 16) + 12;
/// C: `sfBidMax` (sfcodes.h)
pub const sfBidMax: u32 = (6 << 16) + 13;
/// C: `sfMinimumOffer` (sfcodes.h)
pub const sfMinimumOffer: u32 = (6 << 16) + 16;
/// C: `sfRippleEscrow` (sfcodes.h)
pub const sfRippleEscrow: u32 = (6 << 16) + 17;
/// C: `sfDeliveredAmount` (sfcodes.h)
pub const sfDeliveredAmount: u32 = (6 << 16) + 18;
/// C: `sfNFTokenBrokerFee` (sfcodes.h)
pub const sfNFTokenBrokerFee: u32 = (6 << 16) + 19;
/// C: `sfHookCallbackFee` (sfcodes.h)
pub const sfHookCallbackFee: u32 = (6 << 16) + 20;
/// C: `sfLockedBalance` (sfcodes.h)
pub const sfLockedBalance: u32 = (6 << 16) + 21;
/// C: `sfBaseFeeDrops` (sfcodes.h)
pub const sfBaseFeeDrops: u32 = (6 << 16) + 22;
/// C: `sfReserveBaseDrops` (sfcodes.h)
pub const sfReserveBaseDrops: u32 = (6 << 16) + 23;
/// C: `sfReserveIncrementDrops` (sfcodes.h)
pub const sfReserveIncrementDrops: u32 = (6 << 16) + 24;
/// C: `sfLPTokenOut` (sfcodes.h)
pub const sfLPTokenOut: u32 = (6 << 16) + 25;
/// C: `sfLPTokenIn` (sfcodes.h)
pub const sfLPTokenIn: u32 = (6 << 16) + 26;
/// C: `sfEPrice` (sfcodes.h)
pub const sfEPrice: u32 = (6 << 16) + 27;
/// C: `sfPrice` (sfcodes.h)
pub const sfPrice: u32 = (6 << 16) + 28;
/// C: `sfSignatureReward` (sfcodes.h)
pub const sfSignatureReward: u32 = (6 << 16) + 29;
/// C: `sfMinAccountCreateAmount` (sfcodes.h)
pub const sfMinAccountCreateAmount: u32 = (6 << 16) + 30;
/// C: `sfLPTokenBalance` (sfcodes.h)
pub const sfLPTokenBalance: u32 = (6 << 16) + 31;
/// C: `sfTrustLineRewardAccumulator` (sfcodes.h)
pub const sfTrustLineRewardAccumulator: u32 = (6 << 16) + 99;
/// C: `sfPublicKey` (sfcodes.h)
pub const sfPublicKey: u32 = (7 << 16) + 1;
/// C: `sfMessageKey` (sfcodes.h)
pub const sfMessageKey: u32 = (7 << 16) + 2;
/// C: `sfSigningPubKey` (sfcodes.h)
pub const sfSigningPubKey: u32 = (7 << 16) + 3;
/// C: `sfTxnSignature` (sfcodes.h)
pub const sfTxnSignature: u32 = (7 << 16) + 4;
/// C: `sfURI` (sfcodes.h)
pub const sfURI: u32 = (7 << 16) + 5;
/// C: `sfSignature` (sfcodes.h)
pub const sfSignature: u32 = (7 << 16) + 6;
/// C: `sfDomain` (sfcodes.h)
pub const sfDomain: u32 = (7 << 16) + 7;
/// C: `sfFundCode` (sfcodes.h)
pub const sfFundCode: u32 = (7 << 16) + 8;
/// C: `sfRemoveCode` (sfcodes.h)
pub const sfRemoveCode: u32 = (7 << 16) + 9;
/// C: `sfExpireCode` (sfcodes.h)
pub const sfExpireCode: u32 = (7 << 16) + 10;
/// C: `sfCreateCode` (sfcodes.h)
pub const sfCreateCode: u32 = (7 << 16) + 11;
/// C: `sfMemoType` (sfcodes.h)
pub const sfMemoType: u32 = (7 << 16) + 12;
/// C: `sfMemoData` (sfcodes.h)
pub const sfMemoData: u32 = (7 << 16) + 13;
/// C: `sfMemoFormat` (sfcodes.h)
pub const sfMemoFormat: u32 = (7 << 16) + 14;
/// C: `sfFulfillment` (sfcodes.h)
pub const sfFulfillment: u32 = (7 << 16) + 16;
/// C: `sfCondition` (sfcodes.h)
pub const sfCondition: u32 = (7 << 16) + 17;
/// C: `sfMasterSignature` (sfcodes.h)
pub const sfMasterSignature: u32 = (7 << 16) + 18;
/// C: `sfUNLModifyValidator` (sfcodes.h)
pub const sfUNLModifyValidator: u32 = (7 << 16) + 19;
/// C: `sfValidatorToDisable` (sfcodes.h)
pub const sfValidatorToDisable: u32 = (7 << 16) + 20;
/// C: `sfValidatorToReEnable` (sfcodes.h)
pub const sfValidatorToReEnable: u32 = (7 << 16) + 21;
/// C: `sfHookStateData` (sfcodes.h)
pub const sfHookStateData: u32 = (7 << 16) + 22;
/// C: `sfHookReturnString` (sfcodes.h)
pub const sfHookReturnString: u32 = (7 << 16) + 23;
/// C: `sfHookParameterName` (sfcodes.h)
pub const sfHookParameterName: u32 = (7 << 16) + 24;
/// C: `sfHookParameterValue` (sfcodes.h)
pub const sfHookParameterValue: u32 = (7 << 16) + 25;
/// C: `sfBlob` (sfcodes.h)
pub const sfBlob: u32 = (7 << 16) + 26;
/// C: `sfDIDDocument` (sfcodes.h)
pub const sfDIDDocument: u32 = (7 << 16) + 27;
/// C: `sfData` (sfcodes.h)
pub const sfData: u32 = (7 << 16) + 28;
/// C: `sfAssetClass` (sfcodes.h)
pub const sfAssetClass: u32 = (7 << 16) + 29;
/// C: `sfProvider` (sfcodes.h)
pub const sfProvider: u32 = (7 << 16) + 30;
/// C: `sfMPTokenMetadata` (sfcodes.h)
pub const sfMPTokenMetadata: u32 = (7 << 16) + 31;
/// C: `sfCredentialType` (sfcodes.h)
pub const sfCredentialType: u32 = (7 << 16) + 32;
/// C: `sfHookName` (sfcodes.h)
pub const sfHookName: u32 = (7 << 16) + 97;
/// C: `sfRemarkValue` (sfcodes.h)
pub const sfRemarkValue: u32 = (7 << 16) + 98;
/// C: `sfRemarkName` (sfcodes.h)
pub const sfRemarkName: u32 = (7 << 16) + 99;
/// C: `sfAccount` (sfcodes.h)
pub const sfAccount: u32 = (8 << 16) + 1;
/// C: `sfOwner` (sfcodes.h)
pub const sfOwner: u32 = (8 << 16) + 2;
/// C: `sfDestination` (sfcodes.h)
pub const sfDestination: u32 = (8 << 16) + 3;
/// C: `sfIssuer` (sfcodes.h)
pub const sfIssuer: u32 = (8 << 16) + 4;
/// C: `sfAuthorize` (sfcodes.h)
pub const sfAuthorize: u32 = (8 << 16) + 5;
/// C: `sfUnauthorize` (sfcodes.h)
pub const sfUnauthorize: u32 = (8 << 16) + 6;
/// C: `sfRegularKey` (sfcodes.h)
pub const sfRegularKey: u32 = (8 << 16) + 8;
/// C: `sfNFTokenMinter` (sfcodes.h)
pub const sfNFTokenMinter: u32 = (8 << 16) + 9;
/// C: `sfEmitCallback` (sfcodes.h)
pub const sfEmitCallback: u32 = (8 << 16) + 10;
/// C: `sfHolder` (sfcodes.h)
pub const sfHolder: u32 = (8 << 16) + 11;
/// C: `sfHookAccount` (sfcodes.h)
pub const sfHookAccount: u32 = (8 << 16) + 16;
/// C: `sfOtherChainSource` (sfcodes.h)
pub const sfOtherChainSource: u32 = (8 << 16) + 18;
/// C: `sfOtherChainDestination` (sfcodes.h)
pub const sfOtherChainDestination: u32 = (8 << 16) + 19;
/// C: `sfAttestationSignerAccount` (sfcodes.h)
pub const sfAttestationSignerAccount: u32 = (8 << 16) + 20;
/// C: `sfAttestationRewardAccount` (sfcodes.h)
pub const sfAttestationRewardAccount: u32 = (8 << 16) + 21;
/// C: `sfLockingChainDoor` (sfcodes.h)
pub const sfLockingChainDoor: u32 = (8 << 16) + 22;
/// C: `sfIssuingChainDoor` (sfcodes.h)
pub const sfIssuingChainDoor: u32 = (8 << 16) + 23;
/// C: `sfSubject` (sfcodes.h)
pub const sfSubject: u32 = (8 << 16) + 24;
/// C: `sfInform` (sfcodes.h)
pub const sfInform: u32 = (8 << 16) + 99;
/// C: `sfIndexes` (sfcodes.h)
pub const sfIndexes: u32 = (19 << 16) + 1;
/// C: `sfHashes` (sfcodes.h)
pub const sfHashes: u32 = (19 << 16) + 2;
/// C: `sfAmendments` (sfcodes.h)
pub const sfAmendments: u32 = (19 << 16) + 3;
/// C: `sfNFTokenOffers` (sfcodes.h)
pub const sfNFTokenOffers: u32 = (19 << 16) + 4;
/// C: `sfHookNamespaces` (sfcodes.h)
pub const sfHookNamespaces: u32 = (19 << 16) + 5;
/// C: `sfCredentialIDs` (sfcodes.h)
pub const sfCredentialIDs: u32 = (19 << 16) + 6;
/// C: `sfURITokenIDs` (sfcodes.h)
pub const sfURITokenIDs: u32 = (19 << 16) + 99;
/// C: `sfPaths` (sfcodes.h)
pub const sfPaths: u32 = (18 << 16) + 1;
/// C: `sfBaseAsset` (sfcodes.h)
pub const sfBaseAsset: u32 = (26 << 16) + 1;
/// C: `sfQuoteAsset` (sfcodes.h)
pub const sfQuoteAsset: u32 = (26 << 16) + 2;
/// C: `sfLockingChainIssue` (sfcodes.h)
pub const sfLockingChainIssue: u32 = (24 << 16) + 1;
/// C: `sfIssuingChainIssue` (sfcodes.h)
pub const sfIssuingChainIssue: u32 = (24 << 16) + 2;
/// C: `sfAsset` (sfcodes.h)
pub const sfAsset: u32 = (24 << 16) + 3;
/// C: `sfAsset2` (sfcodes.h)
pub const sfAsset2: u32 = (24 << 16) + 4;
/// C: `sfClaimCurrency` (sfcodes.h)
pub const sfClaimCurrency: u32 = (24 << 16) + 5;
/// C: `sfXChainBridge` (sfcodes.h)
pub const sfXChainBridge: u32 = (25 << 16) + 1;
/// C: `sfTransactionMetaData` (sfcodes.h)
pub const sfTransactionMetaData: u32 = (14 << 16) + 2;
/// C: `sfCreatedNode` (sfcodes.h)
pub const sfCreatedNode: u32 = (14 << 16) + 3;
/// C: `sfDeletedNode` (sfcodes.h)
pub const sfDeletedNode: u32 = (14 << 16) + 4;
/// C: `sfModifiedNode` (sfcodes.h)
pub const sfModifiedNode: u32 = (14 << 16) + 5;
/// C: `sfPreviousFields` (sfcodes.h)
pub const sfPreviousFields: u32 = (14 << 16) + 6;
/// C: `sfFinalFields` (sfcodes.h)
pub const sfFinalFields: u32 = (14 << 16) + 7;
/// C: `sfNewFields` (sfcodes.h)
pub const sfNewFields: u32 = (14 << 16) + 8;
/// C: `sfTemplateEntry` (sfcodes.h)
pub const sfTemplateEntry: u32 = (14 << 16) + 9;
/// C: `sfMemo` (sfcodes.h)
pub const sfMemo: u32 = (14 << 16) + 10;
/// C: `sfSignerEntry` (sfcodes.h)
pub const sfSignerEntry: u32 = (14 << 16) + 11;
/// C: `sfNFToken` (sfcodes.h)
pub const sfNFToken: u32 = (14 << 16) + 12;
/// C: `sfEmitDetails` (sfcodes.h)
pub const sfEmitDetails: u32 = (14 << 16) + 13;
/// C: `sfHook` (sfcodes.h)
pub const sfHook: u32 = (14 << 16) + 14;
/// C: `sfSigner` (sfcodes.h)
pub const sfSigner: u32 = (14 << 16) + 16;
/// C: `sfMajority` (sfcodes.h)
pub const sfMajority: u32 = (14 << 16) + 18;
/// C: `sfDisabledValidator` (sfcodes.h)
pub const sfDisabledValidator: u32 = (14 << 16) + 19;
/// C: `sfEmittedTxn` (sfcodes.h)
pub const sfEmittedTxn: u32 = (14 << 16) + 20;
/// C: `sfHookExecution` (sfcodes.h)
pub const sfHookExecution: u32 = (14 << 16) + 21;
/// C: `sfHookParameter` (sfcodes.h)
pub const sfHookParameter: u32 = (14 << 16) + 23;
/// C: `sfHookGrant` (sfcodes.h)
pub const sfHookGrant: u32 = (14 << 16) + 24;
/// C: `sfVoteEntry` (sfcodes.h)
pub const sfVoteEntry: u32 = (14 << 16) + 25;
/// C: `sfAuctionSlot` (sfcodes.h)
pub const sfAuctionSlot: u32 = (14 << 16) + 26;
/// C: `sfAuthAccount` (sfcodes.h)
pub const sfAuthAccount: u32 = (14 << 16) + 27;
/// C: `sfXChainClaimProofSig` (sfcodes.h)
pub const sfXChainClaimProofSig: u32 = (14 << 16) + 28;
/// C: `sfXChainCreateAccountProofSig` (sfcodes.h)
pub const sfXChainCreateAccountProofSig: u32 = (14 << 16) + 29;
/// C: `sfXChainClaimAttestationCollectionElement` (sfcodes.h)
pub const sfXChainClaimAttestationCollectionElement: u32 = (14 << 16) + 30;
/// C: `sfXChainCreateAccountAttestationCollectionElement` (sfcodes.h)
pub const sfXChainCreateAccountAttestationCollectionElement: u32 = (14 << 16) + 31;
/// C: `sfPriceData` (sfcodes.h)
pub const sfPriceData: u32 = (14 << 16) + 32;
/// C: `sfCredential` (sfcodes.h)
pub const sfCredential: u32 = (14 << 16) + 33;
/// C: `sfAmountEntry` (sfcodes.h)
pub const sfAmountEntry: u32 = (14 << 16) + 91;
/// C: `sfMintURIToken` (sfcodes.h)
pub const sfMintURIToken: u32 = (14 << 16) + 92;
/// C: `sfHookEmission` (sfcodes.h)
pub const sfHookEmission: u32 = (14 << 16) + 93;
/// C: `sfImportVLKey` (sfcodes.h)
pub const sfImportVLKey: u32 = (14 << 16) + 94;
/// C: `sfActiveValidator` (sfcodes.h)
pub const sfActiveValidator: u32 = (14 << 16) + 95;
/// C: `sfGenesisMint` (sfcodes.h)
pub const sfGenesisMint: u32 = (14 << 16) + 96;
/// C: `sfRemark` (sfcodes.h)
pub const sfRemark: u32 = (14 << 16) + 97;
/// C: `sfHighReward` (sfcodes.h)
pub const sfHighReward: u32 = (14 << 16) + 98;
/// C: `sfLowReward` (sfcodes.h)
pub const sfLowReward: u32 = (14 << 16) + 99;
/// C: `sfSigners` (sfcodes.h)
pub const sfSigners: u32 = (15 << 16) + 3;
/// C: `sfSignerEntries` (sfcodes.h)
pub const sfSignerEntries: u32 = (15 << 16) + 4;
/// C: `sfTemplate` (sfcodes.h)
pub const sfTemplate: u32 = (15 << 16) + 5;
/// C: `sfNecessary` (sfcodes.h)
pub const sfNecessary: u32 = (15 << 16) + 6;
/// C: `sfSufficient` (sfcodes.h)
pub const sfSufficient: u32 = (15 << 16) + 7;
/// C: `sfAffectedNodes` (sfcodes.h)
pub const sfAffectedNodes: u32 = (15 << 16) + 8;
/// C: `sfMemos` (sfcodes.h)
pub const sfMemos: u32 = (15 << 16) + 9;
/// C: `sfNFTokens` (sfcodes.h)
pub const sfNFTokens: u32 = (15 << 16) + 10;
/// C: `sfHooks` (sfcodes.h)
pub const sfHooks: u32 = (15 << 16) + 11;
/// C: `sfVoteSlots` (sfcodes.h)
pub const sfVoteSlots: u32 = (15 << 16) + 12;
/// C: `sfMajorities` (sfcodes.h)
pub const sfMajorities: u32 = (15 << 16) + 16;
/// C: `sfDisabledValidators` (sfcodes.h)
pub const sfDisabledValidators: u32 = (15 << 16) + 17;
/// C: `sfHookExecutions` (sfcodes.h)
pub const sfHookExecutions: u32 = (15 << 16) + 18;
/// C: `sfHookParameters` (sfcodes.h)
pub const sfHookParameters: u32 = (15 << 16) + 19;
/// C: `sfHookGrants` (sfcodes.h)
pub const sfHookGrants: u32 = (15 << 16) + 20;
/// C: `sfXChainClaimAttestations` (sfcodes.h)
pub const sfXChainClaimAttestations: u32 = (15 << 16) + 21;
/// C: `sfXChainCreateAccountAttestations` (sfcodes.h)
pub const sfXChainCreateAccountAttestations: u32 = (15 << 16) + 22;
/// C: `sfPriceDataSeries` (sfcodes.h)
pub const sfPriceDataSeries: u32 = (15 << 16) + 24;
/// C: `sfAuthAccounts` (sfcodes.h)
pub const sfAuthAccounts: u32 = (15 << 16) + 25;
/// C: `sfAuthorizeCredentials` (sfcodes.h)
pub const sfAuthorizeCredentials: u32 = (15 << 16) + 26;
/// C: `sfUnauthorizeCredentials` (sfcodes.h)
pub const sfUnauthorizeCredentials: u32 = (15 << 16) + 27;
/// C: `sfAcceptedCredentials` (sfcodes.h)
pub const sfAcceptedCredentials: u32 = (15 << 16) + 28;
/// C: `sfAmounts` (sfcodes.h)
pub const sfAmounts: u32 = (15 << 16) + 92;
/// C: `sfHookEmissions` (sfcodes.h)
pub const sfHookEmissions: u32 = (15 << 16) + 93;
/// C: `sfImportVLKeys` (sfcodes.h)
pub const sfImportVLKeys: u32 = (15 << 16) + 94;
/// C: `sfActiveValidators` (sfcodes.h)
pub const sfActiveValidators: u32 = (15 << 16) + 95;
/// C: `sfGenesisMints` (sfcodes.h)
pub const sfGenesisMints: u32 = (15 << 16) + 96;
/// C: `sfRemarks` (sfcodes.h)
pub const sfRemarks: u32 = (15 << 16) + 97;
