// @generated by `cargo xtask gen-core` from crates/rshooks-core/vendor/xahaud-protocol/InnerObjectFormats.cpp — DO NOT EDIT BY HAND.
//! Inner-object views: one struct per inner-object format xahaud declares.
//!
//! These are the object-typed fields that carry a format of their own —
//! [`EmitDetails`], [`Signer`], [`HookParameter`], [`HookExecution`], … — reached by
//! navigating into a parent slot, typically the `…_slot` accessor of a
//! [`crate::views::tx`] or [`crate::views::ledger`] view, or an element of
//! an `STArray`.
//!
//! `from_slot` here verifies nothing and cannot fail: an inner object
//! carries no type field to check, so this is a plain typed wrapper. That is
//! the one thing that distinguishes these from the ledger views; presence,
//! value types and slot lifetime are identical.

use crate::views::source::FieldSource as _;

/// View of the `sfEmitDetails` inner object (STObject).
///
/// Wrap a child slot with [`EmitDetails::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct EmitDetails {
    src: crate::views::source::SlotSource,
}

impl EmitDetails {
    /// Views an already-navigated child slot as `EmitDetails`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfEmitGeneration` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn emit_generation(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfEmitGeneration)
    }

    /// `sfEmitBurden` — UInt64, `soeREQUIRED`.
    #[inline(always)]
    pub fn emit_burden(&self) -> crate::error::Result<u64> {
        self.src.read(crate::sfield::sfEmitBurden)
    }

    /// `sfEmitParentTxnID` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn emit_parent_txn_id(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfEmitParentTxnID)
    }

    /// `sfEmitNonce` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn emit_nonce(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfEmitNonce)
    }

    /// `sfEmitCallback` — AccountID, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn emit_callback(&self) -> crate::error::Result<Option<crate::types::AccountId>> {
        self.src.read_opt(crate::sfield::sfEmitCallback)
    }

    /// `sfEmitHookHash` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn emit_hook_hash(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfEmitHookHash)
    }
}

/// View of the `sfSignerEntry` inner object (STObject).
///
/// Wrap a child slot with [`SignerEntry::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct SignerEntry {
    src: crate::views::source::SlotSource,
}

impl SignerEntry {
    /// Views an already-navigated child slot as `SignerEntry`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }

    /// `sfSignerWeight` — UInt16, `soeREQUIRED`.
    #[inline(always)]
    pub fn signer_weight(&self) -> crate::error::Result<u16> {
        self.src.read(crate::sfield::sfSignerWeight)
    }

    /// `sfWalletLocator` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn wallet_locator(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfWalletLocator)
    }
}

/// View of the `sfSigner` inner object (STObject).
///
/// Wrap a child slot with [`Signer::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct Signer {
    src: crate::views::source::SlotSource,
}

impl Signer {
    /// Views an already-navigated child slot as `Signer`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }

    /// `sfSigningPubKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn signing_pub_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src
            .read_raw(crate::sfield::sfSigningPubKey.code(), out)
    }

    /// `sfTxnSignature` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn txn_signature_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfTxnSignature.code(), out)
    }
}

/// View of the `sfMajority` inner object (STObject).
///
/// Wrap a child slot with [`Majority::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct Majority {
    src: crate::views::source::SlotSource,
}

impl Majority {
    /// Views an already-navigated child slot as `Majority`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAmendment` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn amendment(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfAmendment)
    }

    /// `sfCloseTime` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn close_time(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfCloseTime)
    }
}

/// View of the `sfDisabledValidator` inner object (STObject).
///
/// Wrap a child slot with [`DisabledValidator::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct DisabledValidator {
    src: crate::views::source::SlotSource,
}

impl DisabledValidator {
    /// Views an already-navigated child slot as `DisabledValidator`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfFirstLedgerSequence` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn first_ledger_sequence(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfFirstLedgerSequence)
    }
}

/// View of the `sfHookExecution` inner object (STObject).
///
/// Wrap a child slot with [`HookExecution::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct HookExecution {
    src: crate::views::source::SlotSource,
}

impl HookExecution {
    /// Views an already-navigated child slot as `HookExecution`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfHookResult` — UInt8, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_result(&self) -> crate::error::Result<u8> {
        self.src.read(crate::sfield::sfHookResult)
    }

    /// `sfHookHash` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_hash(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfHookHash)
    }

    /// `sfHookAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfHookAccount)
    }

    /// `sfHookReturnCode` — UInt64, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_return_code(&self) -> crate::error::Result<u64> {
        self.src.read(crate::sfield::sfHookReturnCode)
    }

    /// `sfHookReturnString` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn hook_return_string_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src
            .read_raw(crate::sfield::sfHookReturnString.code(), out)
    }

    /// `sfHookInstructionCount` — UInt64, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_instruction_count(&self) -> crate::error::Result<u64> {
        self.src.read(crate::sfield::sfHookInstructionCount)
    }

    /// `sfHookExecutionIndex` — UInt16, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_execution_index(&self) -> crate::error::Result<u16> {
        self.src.read(crate::sfield::sfHookExecutionIndex)
    }

    /// `sfHookStateChangeCount` — UInt16, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_state_change_count(&self) -> crate::error::Result<u16> {
        self.src.read(crate::sfield::sfHookStateChangeCount)
    }

    /// `sfHookEmitCount` — UInt16, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_emit_count(&self) -> crate::error::Result<u16> {
        self.src.read(crate::sfield::sfHookEmitCount)
    }

    /// `sfFlags` — UInt32, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn flags(&self) -> crate::error::Result<Option<u32>> {
        self.src.read_opt(crate::sfield::sfFlags)
    }
}

/// View of the `sfHookEmission` inner object (STObject).
///
/// Wrap a child slot with [`HookEmission::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct HookEmission {
    src: crate::views::source::SlotSource,
}

impl HookEmission {
    /// Views an already-navigated child slot as `HookEmission`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfHookHash` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_hash(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfHookHash)
    }

    /// `sfHookAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfHookAccount)
    }

    /// `sfEmittedTxnID` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn emitted_txn_id(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfEmittedTxnID)
    }

    /// `sfEmitNonce` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn emit_nonce(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfEmitNonce)
    }
}

/// View of the `sfHook` inner object (STObject).
///
/// Wrap a child slot with [`Hook::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct Hook {
    src: crate::views::source::SlotSource,
}

impl Hook {
    /// Views an already-navigated child slot as `Hook`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfHookHash` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_hash(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfHookHash)
    }

    /// `sfCreateCode` — Blob, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn create_code_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src
            .read_raw_opt(crate::sfield::sfCreateCode.code(), out)
    }

    /// `sfHookGrants` — STArray, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    /// This is the whole container serialized; navigating *into* it needs
    /// `hook_grants_slot`, which only a slot-backed view has.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_grants_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src
            .read_raw_opt(crate::sfield::sfHookGrants.code(), out)
    }

    /// `sfHookGrants` — STArray, `soeOPTIONAL`.
    ///
    /// Navigates to the field and hands its **child slot** to the caller, who
    /// owns it from here (the one place a view does not clear what it opens —
    /// a container has no terminal read to clear after). Clear it, or read a
    /// value out of it with the `take_*` family, before deriving many more.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_grants_slot(
        &self,
    ) -> crate::error::Result<Option<crate::slot_obj::SlotObject<crate::types::STArray>>> {
        self.src.subobject_opt(crate::sfield::sfHookGrants)
    }

    /// `sfHookNamespace` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_namespace(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfHookNamespace)
    }

    /// `sfHookParameters` — STArray, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    /// This is the whole container serialized; navigating *into* it needs
    /// `hook_parameters_slot`, which only a slot-backed view has.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_parameters_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src
            .read_raw_opt(crate::sfield::sfHookParameters.code(), out)
    }

    /// `sfHookParameters` — STArray, `soeOPTIONAL`.
    ///
    /// Navigates to the field and hands its **child slot** to the caller, who
    /// owns it from here (the one place a view does not clear what it opens —
    /// a container has no terminal read to clear after). Clear it, or read a
    /// value out of it with the `take_*` family, before deriving many more.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_parameters_slot(
        &self,
    ) -> crate::error::Result<Option<crate::slot_obj::SlotObject<crate::types::STArray>>> {
        self.src.subobject_opt(crate::sfield::sfHookParameters)
    }

    /// `sfHookOn` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_on(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfHookOn)
    }

    /// `sfHookOnIncoming` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_on_incoming(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfHookOnIncoming)
    }

    /// `sfHookOnOutgoing` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_on_outgoing(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfHookOnOutgoing)
    }

    /// `sfHookCanEmit` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_can_emit(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfHookCanEmit)
    }

    /// `sfHookApiVersion` — UInt16, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_api_version(&self) -> crate::error::Result<Option<u16>> {
        self.src.read_opt(crate::sfield::sfHookApiVersion)
    }

    /// `sfHookName` — Blob, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_name_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src.read_raw_opt(crate::sfield::sfHookName.code(), out)
    }

    /// `sfFlags` — UInt32, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn flags(&self) -> crate::error::Result<Option<u32>> {
        self.src.read_opt(crate::sfield::sfFlags)
    }
}

/// View of the `sfHookGrant` inner object (STObject).
///
/// Wrap a child slot with [`HookGrant::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct HookGrant {
    src: crate::views::source::SlotSource,
}

impl HookGrant {
    /// Views an already-navigated child slot as `HookGrant`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfHookHash` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn hook_hash(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfHookHash)
    }

    /// `sfAuthorize` — AccountID, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn authorize(&self) -> crate::error::Result<Option<crate::types::AccountId>> {
        self.src.read_opt(crate::sfield::sfAuthorize)
    }

    /// `sfFlags` — UInt32, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn flags(&self) -> crate::error::Result<Option<u32>> {
        self.src.read_opt(crate::sfield::sfFlags)
    }
}

/// View of the `sfHookParameter` inner object (STObject).
///
/// Wrap a child slot with [`HookParameter::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct HookParameter {
    src: crate::views::source::SlotSource,
}

impl HookParameter {
    /// Views an already-navigated child slot as `HookParameter`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfHookParameterName` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn hook_parameter_name_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src
            .read_raw(crate::sfield::sfHookParameterName.code(), out)
    }

    /// `sfHookParameterValue` — Blob, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn hook_parameter_value_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src
            .read_raw_opt(crate::sfield::sfHookParameterValue.code(), out)
    }
}

/// View of the `sfNFToken` inner object (STObject).
///
/// Wrap a child slot with [`NFToken::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct NFToken {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl NFToken {
    /// Views an already-navigated child slot as `NFToken`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfNFTokenID` — Hash256, `soeREQUIRED`.
    #[inline(always)]
    pub fn nftoken_id(&self) -> crate::error::Result<crate::types::Hash> {
        self.src.read(crate::sfield::sfNFTokenID)
    }

    /// `sfURI` — Blob, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn uri_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src.read_raw_opt(crate::sfield::sfURI.code(), out)
    }
}

/// View of the `sfGenesisMint` inner object (STObject).
///
/// Wrap a child slot with [`GenesisMint::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct GenesisMint {
    src: crate::views::source::SlotSource,
}

impl GenesisMint {
    /// Views an already-navigated child slot as `GenesisMint`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfDestination` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn destination(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfDestination)
    }

    /// `sfAmount` — Amount, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn amount(&self) -> crate::error::Result<Option<crate::slot_obj::AmountBytes>> {
        self.src.read_opt(crate::sfield::sfAmount)
    }

    /// `sfGovernanceFlags` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn governance_flags(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfGovernanceFlags)
    }

    /// `sfGovernanceMarks` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn governance_marks(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfGovernanceMarks)
    }
}

/// View of the `sfActiveValidator` inner object (STObject).
///
/// Wrap a child slot with [`ActiveValidator::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct ActiveValidator {
    src: crate::views::source::SlotSource,
}

impl ActiveValidator {
    /// Views an already-navigated child slot as `ActiveValidator`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfAccount` — AccountID, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<Option<crate::types::AccountId>> {
        self.src.read_opt(crate::sfield::sfAccount)
    }
}

/// View of the `sfImportVLKey` inner object (STObject).
///
/// Wrap a child slot with [`ImportVLKey::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct ImportVLKey {
    src: crate::views::source::SlotSource,
}

impl ImportVLKey {
    /// Views an already-navigated child slot as `ImportVLKey`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfAccount` — AccountID, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<Option<crate::types::AccountId>> {
        self.src.read_opt(crate::sfield::sfAccount)
    }
}

/// View of the `sfAmountEntry` inner object (STObject).
///
/// Wrap a child slot with [`AmountEntry::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct AmountEntry {
    src: crate::views::source::SlotSource,
}

impl AmountEntry {
    /// Views an already-navigated child slot as `AmountEntry`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAmount` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn amount(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfAmount)
    }
}

/// View of the `sfMintURIToken` inner object (STObject).
///
/// Wrap a child slot with [`MintURIToken::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct MintURIToken {
    src: crate::views::source::SlotSource,
}

impl MintURIToken {
    /// Views an already-navigated child slot as `MintURIToken`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfURI` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn uri_into<B: AsMut<[u8]> + ?Sized>(&self, out: &mut B) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfURI.code(), out)
    }

    /// `sfDigest` — Hash256, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn digest(&self) -> crate::error::Result<Option<crate::types::Hash>> {
        self.src.read_opt(crate::sfield::sfDigest)
    }

    /// `sfFlags` — UInt32, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn flags(&self) -> crate::error::Result<Option<u32>> {
        self.src.read_opt(crate::sfield::sfFlags)
    }
}

/// View of the `sfRemark` inner object (STObject).
///
/// Wrap a child slot with [`Remark::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct Remark {
    src: crate::views::source::SlotSource,
}

impl Remark {
    /// Views an already-navigated child slot as `Remark`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfRemarkName` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn remark_name_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfRemarkName.code(), out)
    }

    /// `sfRemarkValue` — Blob, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn remark_value_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src
            .read_raw_opt(crate::sfield::sfRemarkValue.code(), out)
    }

    /// `sfFlags` — UInt32, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn flags(&self) -> crate::error::Result<Option<u32>> {
        self.src.read_opt(crate::sfield::sfFlags)
    }
}

/// View of the `sfVoteEntry` inner object (STObject).
///
/// Wrap a child slot with [`VoteEntry::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct VoteEntry {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl VoteEntry {
    /// Views an already-navigated child slot as `VoteEntry`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }

    /// `sfTradingFee` — UInt16, `soeDEFAULT`.
    ///
    /// `Ok(None)` when the field is absent. `soeDEFAULT` means only that
    /// upstream allows it to be left off the wire — there is no default
    /// value to substitute, so absence is reported, not filled in.
    #[inline(always)]
    pub fn trading_fee(&self) -> crate::error::Result<Option<u16>> {
        self.src.read_opt(crate::sfield::sfTradingFee)
    }

    /// `sfVoteWeight` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn vote_weight(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfVoteWeight)
    }
}

/// View of the `sfAuctionSlot` inner object (STObject).
///
/// Wrap a child slot with [`AuctionSlot::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct AuctionSlot {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl AuctionSlot {
    /// Views an already-navigated child slot as `AuctionSlot`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }

    /// `sfExpiration` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn expiration(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfExpiration)
    }

    /// `sfDiscountedFee` — UInt16, `soeDEFAULT`.
    ///
    /// `Ok(None)` when the field is absent. `soeDEFAULT` means only that
    /// upstream allows it to be left off the wire — there is no default
    /// value to substitute, so absence is reported, not filled in.
    #[inline(always)]
    pub fn discounted_fee(&self) -> crate::error::Result<Option<u16>> {
        self.src.read_opt(crate::sfield::sfDiscountedFee)
    }

    /// `sfPrice` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn price(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfPrice)
    }

    /// `sfAuthAccounts` — STArray, `soeOPTIONAL`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    /// This is the whole container serialized; navigating *into* it needs
    /// `auth_accounts_slot`, which only a slot-backed view has.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn auth_accounts_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<Option<usize>> {
        self.src
            .read_raw_opt(crate::sfield::sfAuthAccounts.code(), out)
    }

    /// `sfAuthAccounts` — STArray, `soeOPTIONAL`.
    ///
    /// Navigates to the field and hands its **child slot** to the caller, who
    /// owns it from here (the one place a view does not clear what it opens —
    /// a container has no terminal read to clear after). Clear it, or read a
    /// value out of it with the `take_*` family, before deriving many more.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn auth_accounts_slot(
        &self,
    ) -> crate::error::Result<Option<crate::slot_obj::SlotObject<crate::types::STArray>>> {
        self.src.subobject_opt(crate::sfield::sfAuthAccounts)
    }
}

/// View of the `sfXChainClaimAttestationCollectionElement` inner object (STObject).
///
/// Wrap a child slot with [`XChainClaimAttestationCollectionElement::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct XChainClaimAttestationCollectionElement {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl XChainClaimAttestationCollectionElement {
    /// Views an already-navigated child slot as `XChainClaimAttestationCollectionElement`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAttestationSignerAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_signer_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationSignerAccount)
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfSignature` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn signature_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfSignature.code(), out)
    }

    /// `sfAmount` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn amount(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfAmount)
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }

    /// `sfAttestationRewardAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_reward_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationRewardAccount)
    }

    /// `sfWasLockingChainSend` — UInt8, `soeREQUIRED`.
    #[inline(always)]
    pub fn was_locking_chain_send(&self) -> crate::error::Result<u8> {
        self.src.read(crate::sfield::sfWasLockingChainSend)
    }

    /// `sfXChainClaimID` — UInt64, `soeREQUIRED`.
    #[inline(always)]
    pub fn xchain_claim_id(&self) -> crate::error::Result<u64> {
        self.src.read(crate::sfield::sfXChainClaimID)
    }

    /// `sfDestination` — AccountID, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn destination(&self) -> crate::error::Result<Option<crate::types::AccountId>> {
        self.src.read_opt(crate::sfield::sfDestination)
    }
}

/// View of the `sfXChainCreateAccountAttestationCollectionElement` inner object (STObject).
///
/// Wrap a child slot with [`XChainCreateAccountAttestationCollectionElement::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct XChainCreateAccountAttestationCollectionElement {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl XChainCreateAccountAttestationCollectionElement {
    /// Views an already-navigated child slot as `XChainCreateAccountAttestationCollectionElement`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAttestationSignerAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_signer_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationSignerAccount)
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfSignature` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn signature_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfSignature.code(), out)
    }

    /// `sfAmount` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn amount(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfAmount)
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }

    /// `sfAttestationRewardAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_reward_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationRewardAccount)
    }

    /// `sfWasLockingChainSend` — UInt8, `soeREQUIRED`.
    #[inline(always)]
    pub fn was_locking_chain_send(&self) -> crate::error::Result<u8> {
        self.src.read(crate::sfield::sfWasLockingChainSend)
    }

    /// `sfXChainAccountCreateCount` — UInt64, `soeREQUIRED`.
    #[inline(always)]
    pub fn xchain_account_create_count(&self) -> crate::error::Result<u64> {
        self.src.read(crate::sfield::sfXChainAccountCreateCount)
    }

    /// `sfDestination` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn destination(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfDestination)
    }

    /// `sfSignatureReward` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn signature_reward(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfSignatureReward)
    }
}

/// View of the `sfXChainClaimProofSig` inner object (STObject).
///
/// Wrap a child slot with [`XChainClaimProofSig::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct XChainClaimProofSig {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl XChainClaimProofSig {
    /// Views an already-navigated child slot as `XChainClaimProofSig`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAttestationSignerAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_signer_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationSignerAccount)
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfAmount` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn amount(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfAmount)
    }

    /// `sfAttestationRewardAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_reward_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationRewardAccount)
    }

    /// `sfWasLockingChainSend` — UInt8, `soeREQUIRED`.
    #[inline(always)]
    pub fn was_locking_chain_send(&self) -> crate::error::Result<u8> {
        self.src.read(crate::sfield::sfWasLockingChainSend)
    }

    /// `sfDestination` — AccountID, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn destination(&self) -> crate::error::Result<Option<crate::types::AccountId>> {
        self.src.read_opt(crate::sfield::sfDestination)
    }
}

/// View of the `sfXChainCreateAccountProofSig` inner object (STObject).
///
/// Wrap a child slot with [`XChainCreateAccountProofSig::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct XChainCreateAccountProofSig {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl XChainCreateAccountProofSig {
    /// Views an already-navigated child slot as `XChainCreateAccountProofSig`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAttestationSignerAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_signer_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationSignerAccount)
    }

    /// `sfPublicKey` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn public_key_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src.read_raw(crate::sfield::sfPublicKey.code(), out)
    }

    /// `sfAmount` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn amount(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfAmount)
    }

    /// `sfSignatureReward` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn signature_reward(&self) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfSignatureReward)
    }

    /// `sfAttestationRewardAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn attestation_reward_account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAttestationRewardAccount)
    }

    /// `sfWasLockingChainSend` — UInt8, `soeREQUIRED`.
    #[inline(always)]
    pub fn was_locking_chain_send(&self) -> crate::error::Result<u8> {
        self.src.read(crate::sfield::sfWasLockingChainSend)
    }

    /// `sfDestination` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn destination(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfDestination)
    }
}

/// View of the `sfAuthAccount` inner object (STObject).
///
/// Wrap a child slot with [`AuthAccount::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct AuthAccount {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl AuthAccount {
    /// Views an already-navigated child slot as `AuthAccount`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfAccount` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn account(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfAccount)
    }
}

/// View of the `sfPriceData` inner object (STObject).
///
/// Wrap a child slot with [`PriceData::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct PriceData {
    src: crate::views::source::SlotSource,
}

impl PriceData {
    /// Views an already-navigated child slot as `PriceData`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfBaseAsset` — Currency, `soeREQUIRED`.
    #[inline(always)]
    pub fn base_asset(&self) -> crate::error::Result<crate::types::CurrencyCode> {
        self.src.read(crate::sfield::sfBaseAsset)
    }

    /// `sfQuoteAsset` — Currency, `soeREQUIRED`.
    #[inline(always)]
    pub fn quote_asset(&self) -> crate::error::Result<crate::types::CurrencyCode> {
        self.src.read(crate::sfield::sfQuoteAsset)
    }

    /// `sfAssetPrice` — UInt64, `soeOPTIONAL`.
    ///
    /// `Ok(None)` when the field is absent.
    #[inline(always)]
    pub fn asset_price(&self) -> crate::error::Result<Option<u64>> {
        self.src.read_opt(crate::sfield::sfAssetPrice)
    }

    /// `sfScale` — UInt8, `soeDEFAULT`.
    ///
    /// `Ok(None)` when the field is absent. `soeDEFAULT` means only that
    /// upstream allows it to be left off the wire — there is no default
    /// value to substitute, so absence is reported, not filled in.
    #[inline(always)]
    pub fn scale(&self) -> crate::error::Result<Option<u8>> {
        self.src.read_opt(crate::sfield::sfScale)
    }
}

/// View of the `sfCredential` inner object (STObject).
///
/// Wrap a child slot with [`Credential::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
///
/// **Gated by an amendment xahaud marks `Supported::no`**, so it cannot
/// appear on Xahau mainnet — activating it would amendment-block the node.
/// Needs the `all-amendments` cargo feature, which is there for a custom network
/// whose operator knows otherwise. Enable it at your own judgment.
#[cfg(feature = "all-amendments")]
pub struct Credential {
    src: crate::views::source::SlotSource,
}

#[cfg(feature = "all-amendments")]
impl Credential {
    /// Views an already-navigated child slot as `Credential`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfIssuer` — AccountID, `soeREQUIRED`.
    #[inline(always)]
    pub fn issuer(&self) -> crate::error::Result<crate::types::AccountId> {
        self.src.read(crate::sfield::sfIssuer)
    }

    /// `sfCredentialType` — Blob, `soeREQUIRED`.
    ///
    /// **Raw wire bytes**, not a typed value: written into `out`, big-endian,
    /// exactly as the host holds them. Returns the number of bytes written.
    #[inline(always)]
    pub fn credential_type_into<B: AsMut<[u8]> + ?Sized>(
        &self,
        out: &mut B,
    ) -> crate::error::Result<usize> {
        self.src
            .read_raw(crate::sfield::sfCredentialType.code(), out)
    }
}

/// View of the `sfHighReward` inner object (STObject).
///
/// Wrap a child slot with [`HighReward::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct HighReward {
    src: crate::views::source::SlotSource,
}

impl HighReward {
    /// Views an already-navigated child slot as `HighReward`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfRewardLgrFirst` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn reward_lgr_first(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfRewardLgrFirst)
    }

    /// `sfRewardLgrLast` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn reward_lgr_last(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfRewardLgrLast)
    }

    /// `sfRewardTime` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn reward_time(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfRewardTime)
    }

    /// `sfTrustLineRewardAccumulator` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn trust_line_reward_accumulator(
        &self,
    ) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfTrustLineRewardAccumulator)
    }
}

/// View of the `sfLowReward` inner object (STObject).
///
/// Wrap a child slot with [`LowReward::from_slot`] — typically one an
/// enclosing view's `…_slot` accessor handed back, or an `STArray` element.
pub struct LowReward {
    src: crate::views::source::SlotSource,
}

impl LowReward {
    /// Views an already-navigated child slot as `LowReward`, taking ownership of
    /// the slot.
    ///
    /// Infallible: an inner object carries no type field, so there is nothing
    /// to verify. Wrapping the wrong slot produces read errors, not a wrong
    /// answer.
    #[inline(always)]
    #[must_use]
    pub fn from_slot(obj: crate::slot_obj::SlotObject<crate::types::STObject>) -> Self {
        Self {
            src: crate::views::source::SlotSource::new(obj),
        }
    }

    /// Hands the underlying slot back, consuming the view.
    #[inline(always)]
    pub fn into_slot(self) -> crate::slot_obj::SlotObject<crate::types::STObject> {
        self.src.into_slot()
    }

    /// `sfRewardLgrFirst` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn reward_lgr_first(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfRewardLgrFirst)
    }

    /// `sfRewardLgrLast` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn reward_lgr_last(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfRewardLgrLast)
    }

    /// `sfRewardTime` — UInt32, `soeREQUIRED`.
    #[inline(always)]
    pub fn reward_time(&self) -> crate::error::Result<u32> {
        self.src.read(crate::sfield::sfRewardTime)
    }

    /// `sfTrustLineRewardAccumulator` — Amount, `soeREQUIRED`.
    #[inline(always)]
    pub fn trust_line_reward_accumulator(
        &self,
    ) -> crate::error::Result<crate::slot_obj::AmountBytes> {
        self.src.read(crate::sfield::sfTrustLineRewardAccumulator)
    }
}
